-- ============================================================================
-- Gestión GTH · Reclutamiento — Evaluación de entrevista y finalistas
--
--  1) gth_candidato_resultado: catálogo del resultado de la entrevista por
--     candidato (PENDIENTE / PASO / NO_PASO). RF-REC-21 del requerimiento v2.
--  2) gth_candidato_evaluacion: por candidato entrevistado, los cuatro puntajes
--     (entrevista, psicotécnico, técnica y resultado), los tres comentarios
--     (resultado de entrevista, informe psicotécnico y recomendación GTH), el
--     resultado alcanzado y la trazabilidad del correo de agradecimiento que se
--     le envía cuando no continúa (RF-REC-22 / RG-12: un candidato que no supera
--     la entrevista debe recibir el correo antes de cerrar su resultado).
--
-- Hay como máximo una evaluación vigente por candidato: guardar de nuevo
-- actualiza esa misma fila (igual que gth_entrevista).
--
-- Idempotente: se puede correr más de una vez.
-- ============================================================================

BEGIN;

-- ── 1) Catálogo del resultado de la entrevista ──────────────────────────────
CREATE TABLE IF NOT EXISTS gth_candidato_resultado (
    gth_candidato_resultado_id integer      GENERATED BY DEFAULT AS IDENTITY,
    codigo                     text         NOT NULL,
    nombre                     text         NOT NULL,
    orden                      integer      NOT NULL DEFAULT 0,
    created_date_time          timestamptz  NOT NULL DEFAULT now(),
    created_user_id            integer      NULL,
    updated_date_time          timestamptz  NULL,
    updated_user_id            integer      NULL,
    active                     boolean      NOT NULL DEFAULT true,
    state                      boolean      NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_candidato_resultado PRIMARY KEY (gth_candidato_resultado_id)
);

-- Un solo registro vigente por código (los dados de baja quedan con state = false).
CREATE UNIQUE INDEX IF NOT EXISTS ux_gth_candidato_resultado_codigo
    ON gth_candidato_resultado (codigo) WHERE state = true;

INSERT INTO gth_candidato_resultado (codigo, nombre, orden)
VALUES
    ('PENDIENTE', 'Pendiente', 1),
    ('PASO',      'Pasó',      2),
    ('NO_PASO',   'No pasó',   3)
ON CONFLICT (codigo) WHERE state = true
DO UPDATE SET
    nombre            = EXCLUDED.nombre,
    orden             = EXCLUDED.orden,
    active            = true,
    updated_date_time = now();

-- ── 2) Evaluación de la entrevista por candidato ────────────────────────────
CREATE TABLE IF NOT EXISTS gth_candidato_evaluacion (
    gth_candidato_evaluacion_id integer      GENERATED BY DEFAULT AS IDENTITY,
    gth_candidato_id            integer      NOT NULL,
    gth_candidato_resultado_id  integer      NOT NULL,

    -- Puntajes en porcentaje (0-100). Null mientras GTH no los registre.
    puntaje_entrevista          integer      NULL,
    puntaje_psicotecnico        integer      NULL,
    puntaje_tecnica             integer      NULL,
    puntaje_resultado           integer      NULL,

    -- Comentarios del informe que se comparte con el área solicitante.
    comentario_entrevista       text         NULL,
    comentario_psicotecnico     text         NULL,
    comentario_recomendacion    text         NULL,

    -- Correo de agradecimiento (no continuidad): a quién, cuándo y quién lo envió.
    agradecimiento_correo       text         NULL,
    agradecimiento_date_time    timestamptz  NULL,
    agradecimiento_user_id      integer      NULL,

    created_date_time           timestamptz  NOT NULL DEFAULT now(),
    created_user_id             integer      NULL,
    updated_date_time           timestamptz  NULL,
    updated_user_id             integer      NULL,
    active                      boolean      NOT NULL DEFAULT true,
    state                       boolean      NOT NULL DEFAULT true,

    CONSTRAINT pk_gth_candidato_evaluacion PRIMARY KEY (gth_candidato_evaluacion_id),
    CONSTRAINT fk_gth_candidato_evaluacion_candidato FOREIGN KEY (gth_candidato_id)
        REFERENCES gth_candidato (gth_candidato_id),
    CONSTRAINT fk_gth_candidato_evaluacion_resultado FOREIGN KEY (gth_candidato_resultado_id)
        REFERENCES gth_candidato_resultado (gth_candidato_resultado_id),
    CONSTRAINT ck_gth_candidato_evaluacion_puntajes CHECK (
        (puntaje_entrevista   IS NULL OR puntaje_entrevista   BETWEEN 0 AND 100) AND
        (puntaje_psicotecnico IS NULL OR puntaje_psicotecnico BETWEEN 0 AND 100) AND
        (puntaje_tecnica      IS NULL OR puntaje_tecnica      BETWEEN 0 AND 100) AND
        (puntaje_resultado    IS NULL OR puntaje_resultado    BETWEEN 0 AND 100)
    )
);

-- Una sola evaluación vigente por candidato (guardar de nuevo actualiza esa fila).
CREATE UNIQUE INDEX IF NOT EXISTS ux_gth_candidato_evaluacion_candidato
    ON gth_candidato_evaluacion (gth_candidato_id) WHERE state = true;

COMMENT ON TABLE gth_candidato_evaluacion IS
    'Evaluación de la entrevista de un candidato: puntajes, comentarios del informe, resultado y correo de agradecimiento cuando no continúa.';

COMMIT;
