-- ============================================================================
-- Gestión GTH · Onboarding — Carpeta de cartas oferta en BD (no en appsettings)
-- Fecha: 2026-08-17
--
-- Hasta ahora Onboarding subía la carta oferta a la MISMA carpeta que los sustentos
-- de Reclutamiento (gth_sustento_folder). Se separa en su propia tabla singleton
-- gth_carta_oferta_folder porque la carta oferta es un documento del colaborador, no
-- un sustento de la solicitud de personal, y va a otra biblioteca de SharePoint.
--
-- El link se define POR BASE DE DATOS y se puede cambiar sin redeploy: basta con el
-- UPDATE del pie de este archivo. El servicio lee la primera fila vigente
-- (state = true, active = true) en CADA envío y la resuelve vía Graph al subir.
--
-- IMPORTANTE — las cartas ya subidas NO se ven afectadas al cambiar el link:
-- cada onboarding guarda en su propia fila (gth_onboarding) el carta_oferta_url,
-- carta_oferta_item_id y carta_oferta_drive_id con los que se subió, y la pantalla
-- abre la carta con esa url. Este link solo decide dónde se suben las cartas NUEVAS.
--
-- Idempotente: CREATE TABLE IF NOT EXISTS + insert guardado por NOT EXISTS.
-- Seguro de correr tal cual en dev y en producción.
-- ============================================================================

-- 1) Tabla singleton ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS gth_carta_oferta_folder (
    gth_carta_oferta_folder_id integer GENERATED BY DEFAULT AS IDENTITY,
    link_url          text    NOT NULL,
    folder_name       text    NULL,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer NULL,
    updated_date_time timestamptz NULL,
    updated_user_id   integer NULL,
    active            boolean NOT NULL DEFAULT true,
    state             boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_carta_oferta_folder PRIMARY KEY (gth_carta_oferta_folder_id)
);

-- 2) Seed: biblioteca "Cartas ofertas" del sitio bibliotecanm -----------------
-- Va igual en dev y en producción (a diferencia de gth_sustento_folder, que separa
-- dev → "Desarrollo"). Si más adelante se quiere que dev NO escriba en la biblioteca
-- real, usar el UPDATE del punto 3 sobre la BD de desarrollo.
INSERT INTO gth_carta_oferta_folder (link_url, folder_name)
SELECT
    'https://abrilinmob.sharepoint.com/sites/bibliotecanm/Cartas%20ofertas/Forms/AllItems.aspx',
    'Cartas ofertas'
WHERE NOT EXISTS (SELECT 1 FROM gth_carta_oferta_folder WHERE state = true);

-- 3) Cómo cambiar la carpeta más adelante (NO se ejecuta ahora) ---------------
-- Pegar el link de la nueva carpeta/biblioteca de SharePoint. Las cartas ya subidas
-- siguen abriéndose desde donde están; solo cambian las nuevas.
--
-- UPDATE gth_carta_oferta_folder
--    SET link_url          = '<nuevo link de SharePoint>',
--        folder_name       = '<nombre legible, solo referencia>',
--        updated_date_time = now()
--  WHERE state = true;
