-- ============================================================================
-- Gestión GTH · Reclutamiento — "Long list enviada" + tipificación de correos
-- Fecha: 2026-07-24
--
-- Dos cambios que habilitan el envío de la long list al solicitante:
--
-- 1) Estado del pipeline LONG_LIST_ENVIADA ("Long list enviada"): fase que sigue
--    a LONG_LIST. Se alcanza al presionar "Enviar long list y notificar por correo
--    al solicitante" en el modal de detalle de GTH. Se inserta en orden 6 y se
--    recorren las fases posteriores (Selección jefatura → Oferta y cierre).
--
-- 2) Tipificación de los destinatarios del correo (gth_correo_tipo): hasta ahora
--    gth_correo_destinatario guardaba UN solo juego de correos (el de "nueva
--    solicitud de personal"). Ahora hay DOS correos configurables:
--       - SOLICITUD  → nueva solicitud de personal (existente, va a GTH)
--       - LONG_LIST  → long list enviada (nuevo, va al solicitante)
--    Se agrega gth_correo_tipo (catálogo) + gth_correo_tipo_id en la tabla de
--    destinatarios, y el índice único de correo vivo pasa a ser (tipo, email).
--
-- Idempotente. Aplicar en dev y prod.
-- ============================================================================

-- ── 1) Estado LONG_LIST_ENVIADA ─────────────────────────────────────────────
-- Inserta la nueva fase (si no existe) y fija el orden de TODO el pipeline por
-- código (asignación explícita = idempotente; no hay unique sobre orden, así que
-- los duplicados temporales durante el UPDATE no son problema).
INSERT INTO gth_estado_requerimiento (codigo, nombre, orden, descripcion)
SELECT 'LONG_LIST_ENVIADA', 'Long list enviada', 6,
       'GTH envió la long list de CVs; el solicitante debe revisarla para continuar con la evaluación.'
WHERE NOT EXISTS (
    SELECT 1 FROM gth_estado_requerimiento WHERE codigo = 'LONG_LIST_ENVIADA' AND state
);

UPDATE gth_estado_requerimiento AS e SET orden = v.orden
FROM (VALUES
    ('NUEVO', 1),
    ('APROBACION_GG', 2),
    ('VALIDACION_GTH', 3),
    ('PUBLICACION', 4),
    ('LONG_LIST', 5),
    ('LONG_LIST_ENVIADA', 6),
    ('SELECCION_JEFATURA', 7),
    ('EVALUACION', 8),
    ('ENTREVISTAS', 9),
    ('OFERTA_CIERRE', 10)
) AS v(codigo, orden)
WHERE e.codigo = v.codigo AND e.state AND e.orden <> v.orden;

-- ── 2) Catálogo de tipos de correo ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS gth_correo_tipo (
    gth_correo_tipo_id integer GENERATED BY DEFAULT AS IDENTITY,
    codigo            text    NOT NULL,
    nombre            text    NOT NULL,
    orden             integer NOT NULL DEFAULT 0,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer NULL,
    updated_date_time timestamptz NULL,
    updated_user_id   integer NULL,
    active            boolean NOT NULL DEFAULT true,
    state             boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_correo_tipo PRIMARY KEY (gth_correo_tipo_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_correo_tipo_codigo_vivo
    ON gth_correo_tipo (codigo) WHERE state = true;

INSERT INTO gth_correo_tipo (codigo, nombre, orden)
SELECT v.codigo, v.nombre, v.orden
FROM (VALUES
    ('SOLICITUD', 'Nueva solicitud de personal', 1),
    ('LONG_LIST', 'Long list enviada al solicitante', 2)
) AS v(codigo, nombre, orden)
WHERE NOT EXISTS (SELECT 1 FROM gth_correo_tipo t WHERE t.codigo = v.codigo AND t.state);

-- ── 3) gth_correo_destinatario: columna de tipo + FK + índice por (tipo, email) ─
ALTER TABLE gth_correo_destinatario
    ADD COLUMN IF NOT EXISTS gth_correo_tipo_id integer NULL;

-- Backfill: todos los destinatarios existentes son del correo de SOLICITUD.
UPDATE gth_correo_destinatario d
SET gth_correo_tipo_id = t.gth_correo_tipo_id
FROM gth_correo_tipo t
WHERE t.codigo = 'SOLICITUD' AND t.state
  AND d.gth_correo_tipo_id IS NULL;

-- NOT NULL + FK (una vez que ya no hay nulos).
ALTER TABLE gth_correo_destinatario
    ALTER COLUMN gth_correo_tipo_id SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'fk_gth_correo_destinatario_tipo'
          AND table_name = 'gth_correo_destinatario'
    ) THEN
        ALTER TABLE gth_correo_destinatario
            ADD CONSTRAINT fk_gth_correo_destinatario_tipo
            FOREIGN KEY (gth_correo_tipo_id) REFERENCES gth_correo_tipo (gth_correo_tipo_id);
    END IF;
END $$;

-- El índice único de "correo vivo" ahora es por tipo: el mismo correo puede estar
-- configurado en el correo de SOLICITUD y en el de LONG_LIST a la vez.
DROP INDEX IF EXISTS ix_gth_correo_destinatario_email_vivo;
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_correo_destinatario_tipo_email_vivo
    ON gth_correo_destinatario (gth_correo_tipo_id, email) WHERE state = true;

-- ── 4) Seed de destinatarios del correo de LONG_LIST ────────────────────────
-- Solo si aún no hay destinatarios vigentes para ese tipo (no pisa lo editado en UI).
-- dev (BD != 'abril') → correo de pruebas del desarrollador; prod → gth@abril.pe.
INSERT INTO gth_correo_destinatario (email, es_copia, gth_correo_tipo_id)
SELECT 'calvarez@abril.pe', false, t.gth_correo_tipo_id
FROM gth_correo_tipo t
WHERE t.codigo = 'LONG_LIST' AND t.state
  AND current_database() <> 'abril'
  AND NOT EXISTS (
      SELECT 1 FROM gth_correo_destinatario d
      WHERE d.gth_correo_tipo_id = t.gth_correo_tipo_id AND d.state = true
  );

INSERT INTO gth_correo_destinatario (email, es_copia, gth_correo_tipo_id)
SELECT 'gth@abril.pe', false, t.gth_correo_tipo_id
FROM gth_correo_tipo t
WHERE t.codigo = 'LONG_LIST' AND t.state
  AND current_database() = 'abril'
  AND NOT EXISTS (
      SELECT 1 FROM gth_correo_destinatario d
      WHERE d.gth_correo_tipo_id = t.gth_correo_tipo_id AND d.state = true
  );
