-- ============================================================================
-- Centro de aprendizaje y guías (videos-guía agrupados por área/módulo).
--
-- Crea el esquema, siembra los videos actuales (contratistas del login +
-- lecciones aprendidas) y los nuevos de Gestión de Salidas, y registra el
-- feature del admin (configuracion.aprendizaje) para ADMINISTRADOR DEL SISTEMA.
--
-- Idempotente: se puede correr varias veces sin duplicar. El module_id se
-- resuelve por NOMBRE (no hardcodear: difiere entre dev y prod).
-- ============================================================================

BEGIN;

-- 1) Catálogo de superficies: dónde se muestra una categoría (login vs inicio).
CREATE TABLE IF NOT EXISTS learning_surface (
    learning_surface_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                varchar(20)  NOT NULL,
    name                varchar(60)  NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_learning_surface_code ON learning_surface (code);

INSERT INTO learning_surface (code, name)
SELECT 'LOGIN', 'Login (público)'
WHERE NOT EXISTS (SELECT 1 FROM learning_surface WHERE code = 'LOGIN');

INSERT INTO learning_surface (code, name)
SELECT 'INICIO', 'Inicio'
WHERE NOT EXISTS (SELECT 1 FROM learning_surface WHERE code = 'INICIO');

-- 2) Grupos/áreas del centro de aprendizaje.
CREATE TABLE IF NOT EXISTS learning_category (
    learning_category_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    learning_surface_id  integer      NOT NULL REFERENCES learning_surface (learning_surface_id),
    name                 varchar(120) NOT NULL,
    accent_color         varchar(20),
    display_order        integer      NOT NULL DEFAULT 0,
    es_publico_interno   boolean      NOT NULL DEFAULT false,
    active               boolean      NOT NULL DEFAULT true,
    state                boolean      NOT NULL DEFAULT true,
    created_date_time    timestamptz  NOT NULL DEFAULT now(),
    updated_date_time    timestamptz
);
-- Un solo grupo vigente (state) por superficie + nombre (case-insensitive).
CREATE UNIQUE INDEX IF NOT EXISTS ux_learning_category_surface_name
    ON learning_category (learning_surface_id, lower(name)) WHERE state;

-- 3) Videos-guía.
CREATE TABLE IF NOT EXISTS learning_video (
    learning_video_id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    learning_category_id integer      NOT NULL REFERENCES learning_category (learning_category_id),
    title                varchar(200) NOT NULL,
    url                  varchar(500) NOT NULL,
    thumbnail_url        varchar(500),
    display_order        integer      NOT NULL DEFAULT 0,
    active               boolean      NOT NULL DEFAULT true,
    state                boolean      NOT NULL DEFAULT true,
    created_date_time    timestamptz  NOT NULL DEFAULT now(),
    updated_date_time    timestamptz
);
CREATE INDEX IF NOT EXISTS ix_learning_video_category ON learning_video (learning_category_id);

-- 4) Visibilidad por rol en /inicio (solo se consulta si NO es público interno).
CREATE TABLE IF NOT EXISTS learning_category_role (
    learning_category_id integer NOT NULL REFERENCES learning_category (learning_category_id),
    role_id              integer NOT NULL REFERENCES role (role_id),
    PRIMARY KEY (learning_category_id, role_id)
);

-- ============================================================================
-- Seed de categorías
-- ============================================================================

-- Contratistas → LOGIN (público).
INSERT INTO learning_category (learning_surface_id, name, accent_color, display_order, es_publico_interno)
SELECT s.learning_surface_id, 'Contratistas', NULL, 1, false
FROM learning_surface s
WHERE s.code = 'LOGIN'
  AND NOT EXISTS (
      SELECT 1 FROM learning_category c
      WHERE c.learning_surface_id = s.learning_surface_id AND lower(c.name) = lower('Contratistas') AND c.state
  );

-- Gestión de Salidas → INICIO, visible para TODO Abril (público interno).
INSERT INTO learning_category (learning_surface_id, name, accent_color, display_order, es_publico_interno)
SELECT s.learning_surface_id, 'Gestión de Salidas', NULL, 1, true
FROM learning_surface s
WHERE s.code = 'INICIO'
  AND NOT EXISTS (
      SELECT 1 FROM learning_category c
      WHERE c.learning_surface_id = s.learning_surface_id AND lower(c.name) = lower('Gestión de Salidas') AND c.state
  );

-- Lecciones Aprendidas → INICIO, solo roles Mejora Continua (48) y Usuario de Abril (12).
INSERT INTO learning_category (learning_surface_id, name, accent_color, display_order, es_publico_interno)
SELECT s.learning_surface_id, 'Lecciones Aprendidas', NULL, 2, false
FROM learning_surface s
WHERE s.code = 'INICIO'
  AND NOT EXISTS (
      SELECT 1 FROM learning_category c
      WHERE c.learning_surface_id = s.learning_surface_id AND lower(c.name) = lower('Lecciones Aprendidas') AND c.state
  );

-- Roles de "Lecciones Aprendidas" (48 = Admin Mejora Continua, 12 = Usuario de Abril).
INSERT INTO learning_category_role (learning_category_id, role_id)
SELECT c.learning_category_id, r.role_id
FROM learning_category c
JOIN learning_surface s ON s.learning_surface_id = c.learning_surface_id AND s.code = 'INICIO'
JOIN (VALUES (48), (12)) AS r(role_id) ON true
WHERE lower(c.name) = lower('Lecciones Aprendidas') AND c.state
  AND EXISTS (SELECT 1 FROM role rr WHERE rr.role_id = r.role_id)
  AND NOT EXISTS (
      SELECT 1 FROM learning_category_role lcr
      WHERE lcr.learning_category_id = c.learning_category_id AND lcr.role_id = r.role_id
  );

-- ============================================================================
-- Seed de videos
-- ============================================================================

-- Contratistas (los 7 que ya salían hardcodeados en el login).
INSERT INTO learning_video (learning_category_id, title, url, display_order)
SELECT c.learning_category_id, v.title, v.url, v.ord
FROM (VALUES
    ('Activación de cuentas para contratistas',      'https://www.loom.com/share/aac2201e68a54a7bb5fb15deeb91f174', 1),
    ('Gestión de trabajadores, bajas y reingresos',  'https://www.loom.com/share/a9993b1550f7411f8895988900decccf', 2),
    ('Gestión de empresas',                          'https://www.loom.com/share/d9a285cd5c0f4466988ebecc089f6b4c', 3),
    ('Activar nuevos proyectos',                     'https://www.loom.com/share/e3f1e631086d41bca2ce8290b122e04d', 4),
    ('Ingreso de nuevos equipos y máquinas',         'https://www.loom.com/share/7a48bd8a143a4f90816aa98efbf1f05a', 5),
    ('Subir póliza SCTR y Vida Ley',                 'https://www.loom.com/share/3513c6a50d2c4c86b92de2c26d780348', 6),
    ('Programar inducción y validar asistencia',     'https://www.loom.com/share/68e3ae6cccb147c988d2056accad707c', 7)
) AS v(title, url, ord)
JOIN learning_category c ON lower(c.name) = lower('Contratistas') AND c.state
JOIN learning_surface s ON s.learning_surface_id = c.learning_surface_id AND s.code = 'LOGIN'
WHERE NOT EXISTS (
    SELECT 1 FROM learning_video lv WHERE lv.learning_category_id = c.learning_category_id AND lv.url = v.url
);

-- Gestión de Salidas (los 4 nuevos, para todo Abril).
INSERT INTO learning_video (learning_category_id, title, url, display_order)
SELECT c.learning_category_id, v.title, v.url, v.ord
FROM (VALUES
    ('Cómo gestionar tu salida en Abril One',           'https://www.loom.com/share/027472ce117e465189eb830aa1c89b55', 1),
    ('Aprueba solicitudes de salida de colaboradores',  'https://www.loom.com/share/81820471beef4b889906fc485fa0186a', 2),
    ('Cómo rendir cuentas y solicitar reembolso',       'https://www.loom.com/share/c182d6e558394a998849b2261ba4c6a7', 3),
    ('Cómo cancelar una salida pendiente',              'https://www.loom.com/share/494c69444a3d4657800a5b3a767f12e5', 4)
) AS v(title, url, ord)
JOIN learning_category c ON lower(c.name) = lower('Gestión de Salidas') AND c.state
JOIN learning_surface s ON s.learning_surface_id = c.learning_surface_id AND s.code = 'INICIO'
WHERE NOT EXISTS (
    SELECT 1 FROM learning_video lv WHERE lv.learning_category_id = c.learning_category_id AND lv.url = v.url
);

-- Lecciones Aprendidas (el que ya se mostraba en /inicio).
INSERT INTO learning_video (learning_category_id, title, url, display_order)
SELECT c.learning_category_id, v.title, v.url, v.ord
FROM (VALUES
    ('Cómo registrar una lección aprendida', 'https://www.loom.com/share/67cad49dbd9c405db058538da7fa1710', 1)
) AS v(title, url, ord)
JOIN learning_category c ON lower(c.name) = lower('Lecciones Aprendidas') AND c.state
JOIN learning_surface s ON s.learning_surface_id = c.learning_surface_id AND s.code = 'INICIO'
WHERE NOT EXISTS (
    SELECT 1 FROM learning_video lv WHERE lv.learning_category_id = c.learning_category_id AND lv.url = v.url
);

-- ============================================================================
-- Feature del admin (Configuración → Centro de aprendizaje) + grant al admin.
-- ============================================================================

INSERT INTO feature (feature_key, module_id)
SELECT 'configuracion.aprendizaje', m.module_id
FROM module m
WHERE m.module_name = 'Configuración'
  AND NOT EXISTS (SELECT 1 FROM feature WHERE feature_key = 'configuracion.aprendizaje');

-- Solo ADMINISTRADOR DEL SISTEMA (role_id = 1).
INSERT INTO role_feature (role_id, feature_id)
SELECT 1, f.feature_id
FROM feature f
WHERE f.feature_key = 'configuracion.aprendizaje'
  AND NOT EXISTS (
      SELECT 1 FROM role_feature rf
      JOIN feature f2 ON f2.feature_id = rf.feature_id
      WHERE rf.role_id = 1 AND f2.feature_key = 'configuracion.aprendizaje'
  );

COMMIT;
