-- ============================================================================
-- Salidas: revisor por proyecto + pertenencia trabajador->proyecto
-- Fecha: 2026-07-15
--
-- 1) area_revisores.project_id (nullable): NULL = revisor de area (como hoy),
--    con valor = revisor por proyecto. Se reemplaza el indice unico vivo para
--    incluir project_id con NULLS NOT DISTINCT (PG15+), de modo que solo pueda
--    haber UNA fila viva (area_scope_id, NULL, revisor_id).
-- 2) ga_salidas_area_config: flag "filtrar por proyecto" por area (default OFF).
-- 3) ga_salidas_workers_project: proyecto al que pertenece un trabajador
--    (un proyecto por trabajador por ahora).
--
-- Todas las columnas de auditoria siguen el estilo de area_revisores/
-- workers_revisores (created_at/updated_at timestamptz UTC).
-- ============================================================================

BEGIN;

-- 1) area_revisores.project_id --------------------------------------------------
ALTER TABLE area_revisores
    ADD COLUMN IF NOT EXISTS project_id integer NULL
    REFERENCES project(project_id);

-- Reemplazar el indice unico vivo para contemplar el proyecto.
DROP INDEX IF EXISTS ux_area_revisores_vivo;
CREATE UNIQUE INDEX ux_area_revisores_vivo
    ON area_revisores (area_scope_id, project_id, revisor_id)
    NULLS NOT DISTINCT
    WHERE state = true;

-- Indice de apoyo para resolver revisores por proyecto.
CREATE INDEX IF NOT EXISTS ix_area_revisores_proyecto
    ON area_revisores (area_scope_id, project_id)
    WHERE state = true;

-- 2) ga_salidas_area_config -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ga_salidas_area_config (
    id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_scope_id        integer NOT NULL REFERENCES area_scope(area_scope_id),
    filtra_por_proyecto  boolean NOT NULL DEFAULT false,
    created_at           timestamptz NOT NULL DEFAULT now(),
    updated_at           timestamptz NULL,
    active               boolean NOT NULL DEFAULT true,
    state                boolean NOT NULL DEFAULT true
);

-- Una sola fila viva por area.
CREATE UNIQUE INDEX IF NOT EXISTS ux_ga_salidas_area_config_vivo
    ON ga_salidas_area_config (area_scope_id)
    WHERE state = true;

-- 3) ga_salidas_workers_project -------------------------------------------------
CREATE TABLE IF NOT EXISTS ga_salidas_workers_project (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  integer NOT NULL REFERENCES project(project_id),
    worker_id   integer NOT NULL REFERENCES workers(id),
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NULL,
    active      boolean NOT NULL DEFAULT true,
    state       boolean NOT NULL DEFAULT true
);

-- Un trabajador pertenece a un solo proyecto vivo.
CREATE UNIQUE INDEX IF NOT EXISTS ux_ga_salidas_workers_project_vivo
    ON ga_salidas_workers_project (worker_id)
    WHERE state = true;

CREATE INDEX IF NOT EXISTS ix_ga_salidas_workers_project_proyecto
    ON ga_salidas_workers_project (project_id)
    WHERE state = true;

COMMIT;
