-- Fase 2a de Planeamiento BIM: metas semanales de Plan Maestro por macro-actividad.
-- Extraído a mano de la migración EF "AddBimMetaSemanal" (que además arrastra drift
-- no relacionado acumulado en el snapshot — no se corre `dotnet ef database update`
-- con ella, solo sirve para mantener el modelo EF sincronizado). Idempotente: seguro
-- de re-ejecutar.

CREATE TABLE IF NOT EXISTS bim_meta_semanal (
    id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id         integer NOT NULL REFERENCES project(project_id) ON DELETE CASCADE,
    macro_actividad_id integer NOT NULL REFERENCES bim_macro_actividad(id) ON DELETE RESTRICT,
    fecha_inicio_semana date NOT NULL,
    fecha_fin_semana    date NOT NULL,
    meta_avance        numeric NOT NULL,
    created_user_id    integer NOT NULL,
    created_date_time  timestamptz NOT NULL,
    updated_user_id    integer,
    updated_date_time  timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_bim_meta_semanal_unico
    ON bim_meta_semanal (project_id, macro_actividad_id, fecha_inicio_semana);

CREATE INDEX IF NOT EXISTS ix_bim_meta_semanal_macro_actividad_id
    ON bim_meta_semanal (macro_actividad_id);
