-- ============================================================================
-- Gestión GTH · Reclutamiento — Multitest y programación de entrevistas
--
--  1) gth_candidato: check informativo del Multitest por candidato (+ trazabilidad).
--  2) gth_lugar_entrevista: catálogo del lugar donde se cita al candidato.
--  3) gth_entrevista: fecha/hora/lugar de la entrevista de un candidato (1 vigente
--     por candidato; reprogramar actualiza la misma fila y reenvía la invitación).
--  4) gth_estado_requerimiento: ENTREVISTAS pasa a ir inmediatamente después de
--     LONG_LIST_APROBADA (el PDF v2 ordena entrevistas → finalistas en evaluación →
--     decisión del solicitante; el catálogo las tenía al revés).
--
-- Idempotente: se puede correr más de una vez.
-- ============================================================================

BEGIN;

-- ── 1) Multitest por candidato ──────────────────────────────────────────────
ALTER TABLE gth_candidato
    ADD COLUMN IF NOT EXISTS multitest_realizado boolean      NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS multitest_date_time timestamptz  NULL,
    ADD COLUMN IF NOT EXISTS multitest_user_id   integer      NULL;

COMMENT ON COLUMN gth_candidato.multitest_realizado IS
    'Check informativo: el Multitest se rinde fuera de la plataforma; GTH solo marca si el candidato ya lo realizó.';

-- ── 2) Catálogo de lugares de entrevista ────────────────────────────────────
CREATE TABLE IF NOT EXISTS gth_lugar_entrevista (
    gth_lugar_entrevista_id integer      GENERATED BY DEFAULT AS IDENTITY,
    nombre                  text         NOT NULL,
    orden                   integer      NOT NULL DEFAULT 0,
    created_date_time       timestamptz  NOT NULL DEFAULT now(),
    created_user_id         integer      NULL,
    updated_date_time       timestamptz  NULL,
    updated_user_id         integer      NULL,
    active                  boolean      NOT NULL DEFAULT true,
    state                   boolean      NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_lugar_entrevista PRIMARY KEY (gth_lugar_entrevista_id)
);

-- Un solo lugar vigente por nombre (pueden quedar dados de baja con state = false).
CREATE UNIQUE INDEX IF NOT EXISTS ux_gth_lugar_entrevista_nombre
    ON gth_lugar_entrevista (nombre) WHERE state = true;

INSERT INTO gth_lugar_entrevista (nombre, orden)
SELECT 'Calle Mama Ocllo 2647', 1
WHERE NOT EXISTS (
    SELECT 1 FROM gth_lugar_entrevista WHERE nombre = 'Calle Mama Ocllo 2647' AND state = true
);

-- ── 3) Entrevista programada por candidato ──────────────────────────────────
CREATE TABLE IF NOT EXISTS gth_entrevista (
    gth_entrevista_id       integer      GENERATED BY DEFAULT AS IDENTITY,
    gth_candidato_id        integer      NOT NULL,
    fecha                   date         NOT NULL,
    hora                    time         NOT NULL,
    gth_lugar_entrevista_id integer      NOT NULL,
    correo_envio            text         NOT NULL,
    enviado_date_time       timestamptz  NULL,
    enviado_user_id         integer      NULL,
    created_date_time       timestamptz  NOT NULL DEFAULT now(),
    created_user_id         integer      NULL,
    updated_date_time       timestamptz  NULL,
    updated_user_id         integer      NULL,
    active                  boolean      NOT NULL DEFAULT true,
    state                   boolean      NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_entrevista PRIMARY KEY (gth_entrevista_id),
    CONSTRAINT fk_gth_entrevista_candidato FOREIGN KEY (gth_candidato_id)
        REFERENCES gth_candidato (gth_candidato_id),
    CONSTRAINT fk_gth_entrevista_lugar FOREIGN KEY (gth_lugar_entrevista_id)
        REFERENCES gth_lugar_entrevista (gth_lugar_entrevista_id)
);

-- Una sola entrevista vigente por candidato (reprogramar actualiza esta fila).
CREATE UNIQUE INDEX IF NOT EXISTS ux_gth_entrevista_candidato
    ON gth_entrevista (gth_candidato_id) WHERE state = true;

-- ── 4) Orden del pipeline: ENTREVISTAS antes de EVALUACION/SELECCION_JEFATURA ─
-- Se hace en dos pasos para no chocar con órdenes repetidas de forma transitoria.
UPDATE gth_estado_requerimiento SET orden = orden + 100 WHERE codigo IN
    ('ENTREVISTAS', 'EVALUACION', 'SELECCION_JEFATURA', 'OFERTA_CIERRE');

UPDATE gth_estado_requerimiento SET orden =  8 WHERE codigo = 'ENTREVISTAS';
UPDATE gth_estado_requerimiento SET orden =  9 WHERE codigo = 'EVALUACION';
UPDATE gth_estado_requerimiento SET orden = 10 WHERE codigo = 'SELECCION_JEFATURA';
UPDATE gth_estado_requerimiento SET orden = 11 WHERE codigo = 'OFERTA_CIERRE';

COMMIT;
