-- ============================================================================
-- Descansos médicos — certificados a SharePoint con la carpeta configurable en BD
-- Fecha: 2026-08-11
--
-- Antes los certificados de un descanso médico se guardaban en dos sitios distintos
-- según quién registraba:
--   - Mi Salud (lo sube el trabajador) → SharePointHabService, biblioteca por defecto
--     del sitio SSOMAApps con la ruta hardcodeada "habilitacion/descanso-medico/…".
--   - Descansos (lo sube SSOMA)        → IFileStorageService (contenedor Azure Blob
--     "ssoma-descansos").
-- Ninguno de los dos era configurable y el sitio SSOMAApps está restringido, así que
-- el propio trabajador no podía ver su certificado.
--
-- Ahora ambos flujos suben a UNA sola carpeta de SharePoint cuyo link vive en la tabla
-- singleton ss_descanso_carpeta: se guarda el link tal cual y el backend lo resuelve a
-- driveId/folderId vía Graph al subir. Se puede cambiar sin redeploy y sin tocar
-- appsettings. Mismo patrón que ga_captura_folder (capturas de movilidad) y
-- gth_sustento_folder (Reclutamiento).
--
-- También se elimina la funcionalidad "Revisión de Descansos": la pantalla de
-- Descansos ya cubre lo mismo (y mejor), así que se quitan su feature y sus role_feature.
--
-- Idempotente: CREATE TABLE / ADD COLUMN IF NOT EXISTS + inserts guardados por NOT EXISTS.
-- Seguro de correr tal cual en dev y en producción (misma carpeta en ambos entornos).
-- ============================================================================

BEGIN;

-- 1) Carpeta única (singleton) donde se guardan los certificados médicos -------
CREATE TABLE IF NOT EXISTS ss_descanso_carpeta (
    id              integer GENERATED BY DEFAULT AS IDENTITY,
    link_url        text        NOT NULL,
    folder_name     text        NULL,
    active          boolean     NOT NULL DEFAULT true,
    state           boolean     NOT NULL DEFAULT true,
    created_at      timestamptz NOT NULL DEFAULT now(),
    created_user_id integer     NULL,
    updated_at      timestamptz NOT NULL DEFAULT now(),
    updated_user_id integer     NULL,
    CONSTRAINT pk_ss_descanso_carpeta PRIMARY KEY (id),
    CONSTRAINT fk_ss_descanso_carpeta_created_user
        FOREIGN KEY (created_user_id) REFERENCES app_user(user_id),
    CONSTRAINT fk_ss_descanso_carpeta_updated_user
        FOREIGN KEY (updated_user_id) REFERENCES app_user(user_id)
);

COMMENT ON TABLE ss_descanso_carpeta IS
    'Carpeta de SharePoint donde se guardan los certificados de los descansos médicos. '
    'Solo una fila vigente (state = true); el backend resuelve link_url a driveId/folderId vía Graph.';

-- Garantiza que solo haya una fila vigente (state = true) a la vez.
CREATE UNIQUE INDEX IF NOT EXISTS ux_ss_descanso_carpeta_singleton
    ON ss_descanso_carpeta ((true)) WHERE state = true;

INSERT INTO ss_descanso_carpeta (link_url, folder_name)
SELECT
    'https://abrilinmob.sharepoint.com/sites/bibliotecanm/Descansos%20mdicos/Forms/AllItems.aspx',
    'Descansos médicos'
WHERE NOT EXISTS (SELECT 1 FROM ss_descanso_carpeta WHERE state = true);

-- 2) Ubicación estable del archivo subido -------------------------------------
-- url sigue guardando la webUrl de SharePoint (lo que se muestra), pero para
-- descargarlo vía Graph sin depender de la sesión de Microsoft 365 del navegador se
-- necesita driveId + itemId. Nullable: los adjuntos anteriores (Azure Blob o ruta
-- relativa del sitio SSOMAApps) se siguen sirviendo por su url.
ALTER TABLE ss_descanso_medico_adjunto
    ADD COLUMN IF NOT EXISTS drive_id varchar(500) NULL,
    ADD COLUMN IF NOT EXISTS item_id  varchar(500) NULL;

-- 3) Normalización de los certificados históricos ------------------------------
-- Los descansos anteriores a ss_descanso_medico_adjunto guardaban su único archivo en
-- url_certificado / url_documento. Se les crea su fila de adjunto para que las pantallas
-- listen y descarguen SIEMPRE por adjunto (el backend ya sabe servir esas urls viejas:
-- absoluta de Azure Blob o ruta relativa del sitio SSOMAApps). url_certificado se conserva
-- como espejo del primer adjunto, igual que hace el alta de un descanso nuevo.
INSERT INTO ss_descanso_medico_adjunto (descanso_id, url, nombre_archivo, state, created_at, updated_at)
SELECT
    d.id,
    coalesce(nullif(d.url_certificado, ''), nullif(d.url_documento, '')),
    -- Nombre visible: el último segmento de la ruta/URL guardada.
    regexp_replace(
        split_part(coalesce(nullif(d.url_certificado, ''), nullif(d.url_documento, '')), '?', 1),
        '^.*/', ''),
    true,
    d.created_at,
    d.created_at
FROM ss_descanso_medico d
WHERE d.state
  AND coalesce(nullif(d.url_certificado, ''), nullif(d.url_documento, '')) IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM ss_descanso_medico_adjunto a
      WHERE a.descanso_id = d.id AND a.state
  );

-- 4) Baja de la funcionalidad "Revisión de Descansos" -------------------------
DELETE FROM role_feature
WHERE feature_id IN (
    SELECT feature_id FROM feature
    WHERE feature_key = 'ssoma.salud-ocupacional.revision-descansos'
);

DELETE FROM feature
WHERE feature_key = 'ssoma.salud-ocupacional.revision-descansos';

COMMIT;
