-- ============================================================================
-- Gestión de Salidas — Carpeta de planillas de rendición (PDF) en BD (no en appsettings)
-- Fecha: 2026-07-24
--
-- Antes las planillas de rendición (PDF) se subían a un sitio fijo (CostosyPresupuestos)
-- tomado de appsettings + carpeta hardcodeada ("Solicitudes rendidas"). Ese sitio está
-- restringido a costos/admins. Ahora el destino se define POR BASE DE DATOS en la tabla
-- singleton ga_rendicion_folder y se puede cambiar sin redeploy:
--   - dev  (BD != 'abril')  → biblioteca "Desarrollo" / App Solicitud de Salidas / Solicitudes rendidas
--   - prod (BD  = 'abril')  → biblioteca "App Solicitud de Salidas" / Solicitudes rendidas
-- ambas en el sitio /sites/bibliotecanm.
--
-- El servicio lee la primera fila vigente (state = true, active = true) y resuelve el
-- link vía Graph al subir. Mismo patrón que ga_captura_folder y gth_sustento_folder.
--
-- Idempotente: CREATE TABLE IF NOT EXISTS + inserts guardados por NOT EXISTS.
-- El seed se auto-selecciona por current_database(): la carpeta de PRODUCCIÓN solo se
-- inserta en la BD llamada 'abril'; cualquier otra BD recibe la de desarrollo.
-- Seguro de correr tal cual en ambos entornos.
-- ============================================================================

-- 1) Tabla singleton ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS ga_rendicion_folder (
    ga_rendicion_folder_id integer GENERATED BY DEFAULT AS IDENTITY,
    link_url          text    NOT NULL,
    folder_name       text    NULL,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer NULL,
    updated_date_time timestamptz NULL,
    updated_user_id   integer NULL,
    active            boolean NOT NULL DEFAULT true,
    state             boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_ga_rendicion_folder PRIMARY KEY (ga_rendicion_folder_id)
);

-- Garantiza que solo haya una fila vigente (state = true) a la vez.
CREATE UNIQUE INDEX IF NOT EXISTS ux_ga_rendicion_folder_singleton
    ON ga_rendicion_folder ((true)) WHERE state = true;

-- 2) Seed de DESARROLLO (cualquier BD que no sea la de producción) ------------
INSERT INTO ga_rendicion_folder (link_url, folder_name)
SELECT
    'https://abrilinmob.sharepoint.com/sites/bibliotecanm/Desarrollo/Forms/AllItems.aspx?id=%2Fsites%2Fbibliotecanm%2FDesarrollo%2FApp%20Solicitud%20de%20Salidas%2FSolicitudes%20rendidas&viewid=087a516f%2Da398%2D433d%2Db208%2Df4aa51591a4d',
    'Desarrollo / App Solicitud de Salidas / Solicitudes rendidas'
WHERE current_database() <> 'abril'
  AND NOT EXISTS (SELECT 1 FROM ga_rendicion_folder WHERE state = true);

-- 3) Seed de PRODUCCIÓN (solo en la BD 'abril') ------------------------------
INSERT INTO ga_rendicion_folder (link_url, folder_name)
SELECT
    'https://abrilinmob.sharepoint.com/sites/bibliotecanm/App%20Solicitud%20de%20Salidas/Forms/AllItems.aspx?id=%2Fsites%2Fbibliotecanm%2FApp%20Solicitud%20de%20Salidas%2FSolicitudes%20rendidas&viewid=413a3b2d%2Db4fd%2D4278%2Db87c%2De24587b6cf5c',
    'App Solicitud de Salidas / Solicitudes rendidas'
WHERE current_database() = 'abril'
  AND NOT EXISTS (SELECT 1 FROM ga_rendicion_folder WHERE state = true);
