-- ============================================================================
-- Gestión GTH · Reclutamiento — Portafolio/Anexos por candidato de la long list
-- Fecha: 2026-08-20
--
-- Nueva tabla gth_candidato_anexo: los N archivos que GTH puede adjuntar por
-- candidato al armar la long list (portafolio, certificados, cartas, etc.),
-- además del CV. Son una tabla aparte y no columnas de gth_candidato porque la
-- cantidad es variable por candidato.
--
-- Cada fila guarda la ubicación estable del archivo en SharePoint (drive_id +
-- item_id) y la url web, igual que las columnas cv_* de gth_candidato: el
-- solicitante los abre desde "Revisar long list y CVs" y también le llegan
-- adjuntos en el correo de la long list.
--
-- Se cuelga del candidato y no del requerimiento porque la long list se vuelve
-- a cargar cuando el solicitante rechaza a todos: cada vuelta tiene sus propias
-- filas de gth_candidato y sus anexos viajan con ellas (ver numero_long_list).
--
-- Idempotente. Aplicar en dev y prod.
-- ============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS gth_candidato_anexo (
    gth_candidato_anexo_id integer      GENERATED BY DEFAULT AS IDENTITY,
    gth_candidato_id       integer      NOT NULL,

    -- Nombre del archivo tal como quedó en SharePoint (el que ve el solicitante).
    nombre                 text         NOT NULL,
    -- Nombre con el que GTH lo subió, para mostrarlo tal cual lo reconoce el usuario.
    nombre_original        text         NULL,
    url                    text         NULL,
    item_id                text         NULL,
    drive_id               text         NULL,

    -- Orden de carga dentro del candidato (1, 2, 3…).
    orden                  integer      NOT NULL DEFAULT 0,

    created_date_time      timestamptz  NOT NULL DEFAULT now(),
    created_user_id        integer      NULL,
    updated_date_time      timestamptz  NULL,
    updated_user_id        integer      NULL,
    active                 boolean      NOT NULL DEFAULT true,
    state                  boolean      NOT NULL DEFAULT true,

    CONSTRAINT pk_gth_candidato_anexo PRIMARY KEY (gth_candidato_anexo_id),
    CONSTRAINT fk_gth_candidato_anexo_candidato FOREIGN KEY (gth_candidato_id)
        REFERENCES gth_candidato (gth_candidato_id)
);

-- Lectura de los anexos vivos de un candidato (revisión del solicitante).
CREATE INDEX IF NOT EXISTS ix_gth_candidato_anexo_candidato
    ON gth_candidato_anexo (gth_candidato_id) WHERE state = true;

COMMENT ON TABLE gth_candidato_anexo IS
    'Portafolio/anexos de un candidato de la long list: N archivos por candidato, además del CV.';

COMMIT;
