-- ============================================================================
-- Gestión GTH · Reclutamiento — Formulario "Nueva solicitud de personal"
-- Fecha: 2026-07-21
--
-- Crea el modelo de datos mínimo para el formulario de solicitud de personal:
--   - gth_puesto               (catálogo simple de puestos — solo nombres por ahora)
--   - gth_tipo_requerimiento   (Nuevo / Reemplazo)
--   - gth_estado_requerimiento (estado inicial NUEVO; el resto del pipeline vendrá después)
--   - gth_solicitud            (cabecera: área, justificación, sustento SharePoint)
--   - gth_requerimiento        (1 por vacante; código REQ-AAAA-NNNN)
-- + seeds de catálogos + módulo/feature/role_feature para la navegación y permisos.
--
-- Idempotente: CREATE TABLE IF NOT EXISTS + inserts guardados por NOT EXISTS.
-- Aplicar tal cual en producción (y ya aplicado en dev).
-- ============================================================================

-- 1) Catálogos ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS gth_puesto (
    gth_puesto_id     integer GENERATED BY DEFAULT AS IDENTITY,
    nombre            text    NOT NULL,
    orden             integer NOT NULL DEFAULT 0,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer NULL,
    updated_date_time timestamptz NULL,
    updated_user_id   integer NULL,
    active            boolean NOT NULL DEFAULT true,
    state             boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_puesto PRIMARY KEY (gth_puesto_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_puesto_nombre_vivo ON gth_puesto (nombre) WHERE state = true;

CREATE TABLE IF NOT EXISTS gth_tipo_requerimiento (
    gth_tipo_requerimiento_id integer GENERATED BY DEFAULT AS IDENTITY,
    nombre            text    NOT NULL,
    orden             integer NOT NULL DEFAULT 0,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer NULL,
    updated_date_time timestamptz NULL,
    updated_user_id   integer NULL,
    active            boolean NOT NULL DEFAULT true,
    state             boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_tipo_requerimiento PRIMARY KEY (gth_tipo_requerimiento_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_tipo_requerimiento_nombre_vivo ON gth_tipo_requerimiento (nombre) WHERE state = true;

CREATE TABLE IF NOT EXISTS gth_estado_requerimiento (
    gth_estado_requerimiento_id integer GENERATED BY DEFAULT AS IDENTITY,
    codigo            text    NOT NULL,
    nombre            text    NOT NULL,
    orden             integer NOT NULL DEFAULT 0,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer NULL,
    updated_date_time timestamptz NULL,
    updated_user_id   integer NULL,
    active            boolean NOT NULL DEFAULT true,
    state             boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_estado_requerimiento PRIMARY KEY (gth_estado_requerimiento_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_estado_requerimiento_codigo_vivo ON gth_estado_requerimiento (codigo) WHERE state = true;

-- 2) Cabecera de solicitud ---------------------------------------------------
CREATE TABLE IF NOT EXISTS gth_solicitud (
    gth_solicitud_id      integer GENERATED BY DEFAULT AS IDENTITY,
    area_scope_id         integer NULL,
    area_nombre           text    NULL,
    solicitante_user_id   integer NULL,
    solicitante_worker_id integer NULL,
    justificacion         text    NULL,
    sustento_nombre       text    NULL,
    sustento_url          text    NULL,
    sustento_item_id      text    NULL,
    sustento_drive_id     text    NULL,
    created_date_time     timestamptz NOT NULL DEFAULT now(),
    created_user_id       integer NULL,
    updated_date_time     timestamptz NULL,
    updated_user_id       integer NULL,
    active                boolean NOT NULL DEFAULT true,
    state                 boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_solicitud PRIMARY KEY (gth_solicitud_id)
);

-- 3) Requerimiento por vacante ----------------------------------------------
CREATE TABLE IF NOT EXISTS gth_requerimiento (
    gth_requerimiento_id        integer GENERATED BY DEFAULT AS IDENTITY,
    gth_solicitud_id            integer NOT NULL,
    codigo                      text    NOT NULL,
    anio                        integer NOT NULL,
    numero                      integer NOT NULL,
    gth_puesto_id               integer NOT NULL,
    gth_tipo_requerimiento_id   integer NOT NULL,
    project_id                  integer NOT NULL,
    fecha_requerida_ingreso     date    NOT NULL,
    gth_estado_requerimiento_id integer NOT NULL,
    created_date_time           timestamptz NOT NULL DEFAULT now(),
    created_user_id             integer NULL,
    updated_date_time           timestamptz NULL,
    updated_user_id             integer NULL,
    active                      boolean NOT NULL DEFAULT true,
    state                       boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_requerimiento PRIMARY KEY (gth_requerimiento_id),
    CONSTRAINT fk_gth_req_solicitud FOREIGN KEY (gth_solicitud_id)
        REFERENCES gth_solicitud (gth_solicitud_id) ON DELETE CASCADE,
    CONSTRAINT fk_gth_req_puesto FOREIGN KEY (gth_puesto_id)
        REFERENCES gth_puesto (gth_puesto_id),
    CONSTRAINT fk_gth_req_tipo FOREIGN KEY (gth_tipo_requerimiento_id)
        REFERENCES gth_tipo_requerimiento (gth_tipo_requerimiento_id),
    CONSTRAINT fk_gth_req_estado FOREIGN KEY (gth_estado_requerimiento_id)
        REFERENCES gth_estado_requerimiento (gth_estado_requerimiento_id),
    CONSTRAINT fk_gth_req_project FOREIGN KEY (project_id)
        REFERENCES project (project_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_requerimiento_codigo ON gth_requerimiento (codigo);
CREATE INDEX IF NOT EXISTS ix_gth_requerimiento_anio ON gth_requerimiento (anio);

-- 4) Seeds de catálogos ------------------------------------------------------
INSERT INTO gth_tipo_requerimiento (nombre, orden)
SELECT v.nombre, v.orden
FROM (VALUES ('Nuevo', 1), ('Reemplazo', 2)) AS v(nombre, orden)
WHERE NOT EXISTS (SELECT 1 FROM gth_tipo_requerimiento t WHERE t.nombre = v.nombre AND t.state);

INSERT INTO gth_estado_requerimiento (codigo, nombre, orden)
SELECT v.codigo, v.nombre, v.orden
FROM (VALUES ('NUEVO', 'Nuevo / Solicitud', 1)) AS v(codigo, nombre, orden)
WHERE NOT EXISTS (SELECT 1 FROM gth_estado_requerimiento e WHERE e.codigo = v.codigo AND e.state);

INSERT INTO gth_puesto (nombre, orden)
SELECT v.nombre, v.orden
FROM (VALUES
    ('Gerente de Proyectos', 1),
    ('Jefe de Obra', 2),
    ('Supervisor de Obra', 3),
    ('Supervisor de Instalaciones', 4),
    ('Ingeniero de Instalaciones', 5),
    ('Residente de Obra', 6),
    ('Arquitecto de Calidad', 7),
    ('Asistente de Obra', 8),
    ('Prevencionista de Obra', 9)
) AS v(nombre, orden)
WHERE NOT EXISTS (SELECT 1 FROM gth_puesto p WHERE p.nombre = v.nombre AND p.state);

-- 5) Navegación y permisos ---------------------------------------------------
-- 5.1) Módulo "Gestión GTH" (module_id se autoasigna; se referencia por nombre).
INSERT INTO module (module_name)
SELECT 'Gestión GTH'
WHERE NOT EXISTS (SELECT 1 FROM module WHERE module_name = 'Gestión GTH');

-- 5.2) Feature de Reclutamiento.
INSERT INTO feature (feature_key, module_id)
SELECT 'gestion-gth.reclutamiento', m.module_id
FROM module m
WHERE m.module_name = 'Gestión GTH'
  AND NOT EXISTS (SELECT 1 FROM feature WHERE feature_key = 'gestion-gth.reclutamiento');

-- 5.3) Acceso: rol 1 (ADMINISTRADOR DEL SISTEMA) para poder probar/registrar.
--      OJO: definir los roles reales (jefaturas/gerencias) con GTH y agregarlos aquí.
INSERT INTO role_feature (role_id, feature_id)
SELECT 1, f.feature_id
FROM feature f
WHERE f.feature_key = 'gestion-gth.reclutamiento'
  AND NOT EXISTS (
      SELECT 1 FROM role_feature rf WHERE rf.role_id = 1 AND rf.feature_id = f.feature_id
  );
