-- ============================================================================
-- Gestión GTH · Reclutamiento — Destinatarios del correo de "nueva solicitud"
-- Fecha: 2026-07-21
--
-- Tabla configurable desde la UI (botón Configuración de Reclutamiento) para
-- definir a quién se le envía el correo cuando se registra una nueva solicitud
-- de personal. Se puede alternar fácilmente entre un correo de pruebas y el de
-- GTH en producción, sin redeploy.
--   es_copia = false → destinatario principal (Para/To)
--   es_copia = true  → copia (CC)
--
-- Idempotente. El seed se auto-selecciona por current_database():
--   - dev  (cualquier BD != 'abril') → correo de pruebas del desarrollador
--   - prod (BD 'abril')              → gth@abril.pe
-- El seed solo entra si aún NO hay destinatarios vigentes (una vez editados
-- desde la UI, re-ejecutar este script no los pisa).
-- ============================================================================

CREATE TABLE IF NOT EXISTS gth_correo_destinatario (
    gth_correo_destinatario_id integer GENERATED BY DEFAULT AS IDENTITY,
    email             text    NOT NULL,
    es_copia          boolean NOT NULL DEFAULT false,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer NULL,
    updated_date_time timestamptz NULL,
    updated_user_id   integer NULL,
    active            boolean NOT NULL DEFAULT true,
    state             boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_correo_destinatario PRIMARY KEY (gth_correo_destinatario_id)
);

-- Un correo no puede repetirse entre los destinatarios vigentes.
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_correo_destinatario_email_vivo
    ON gth_correo_destinatario (email) WHERE state = true;

-- Seed DESARROLLO (correo de pruebas) — cualquier BD que no sea producción.
INSERT INTO gth_correo_destinatario (email, es_copia)
SELECT 'calvarez@abril.pe', false
WHERE current_database() <> 'abril'
  AND NOT EXISTS (SELECT 1 FROM gth_correo_destinatario WHERE state = true);

-- Seed PRODUCCIÓN (GTH) — solo en la BD 'abril'.
INSERT INTO gth_correo_destinatario (email, es_copia)
SELECT 'gth@abril.pe', false
WHERE current_database() = 'abril'
  AND NOT EXISTS (SELECT 1 FROM gth_correo_destinatario WHERE state = true);
