-- ============================================================================
-- Gestión GTH · Reclutamiento — Carpeta de sustentos en BD (no en appsettings)
-- Fecha: 2026-07-21
--
-- Reemplaza la config de appsettings (Gth:Reclutamiento:SustentosFolderUrlDev/Prod)
-- por una tabla singleton gth_sustento_folder. Así la biblioteca de SharePoint donde
-- se suben los sustentos se define POR BASE DE DATOS y se puede cambiar sin redeploy:
--   - dev  (abril_local_17 / cualquier BD != 'abril') → biblioteca "Desarrollo"
--   - prod (BD 'abril')                                → biblioteca "App Reclutamiento"
--
-- El servicio lee la primera fila vigente (state = true, active = true) y resuelve el
-- link vía Graph al subir. Mismo espíritu que ga_adjunto_folder (Salidas).
--
-- Idempotente: CREATE TABLE IF NOT EXISTS + inserts guardados por NOT EXISTS.
-- El seed se auto-selecciona por current_database(): la biblioteca de PRODUCCIÓN solo
-- se inserta en la BD llamada 'abril'; cualquier otra BD recibe la de desarrollo.
-- Seguro de correr tal cual en ambos entornos.
-- ============================================================================

-- 1) Tabla singleton ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS gth_sustento_folder (
    gth_sustento_folder_id integer GENERATED BY DEFAULT AS IDENTITY,
    link_url          text    NOT NULL,
    folder_name       text    NULL,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer NULL,
    updated_date_time timestamptz NULL,
    updated_user_id   integer NULL,
    active            boolean NOT NULL DEFAULT true,
    state             boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_sustento_folder PRIMARY KEY (gth_sustento_folder_id)
);

-- 2) Seed de DESARROLLO (cualquier BD que no sea la de producción) ------------
INSERT INTO gth_sustento_folder (link_url, folder_name)
SELECT
    'https://abrilinmob.sharepoint.com/sites/bibliotecanm/Desarrollo/Forms/AllItems.aspx?id=%2Fsites%2Fbibliotecanm%2FDesarrollo%2FGTH%20%2D%20Reclutamiento%2FSustentos&viewid=087a516f%2Da398%2D433d%2Db208%2Df4aa51591a4d',
    'Desarrollo / GTH - Reclutamiento / Sustentos'
WHERE current_database() <> 'abril'
  AND NOT EXISTS (SELECT 1 FROM gth_sustento_folder WHERE state = true);

-- 3) Seed de PRODUCCIÓN (solo en la BD 'abril') ------------------------------
INSERT INTO gth_sustento_folder (link_url, folder_name)
SELECT
    'https://abrilinmob.sharepoint.com/sites/bibliotecanm/App%20Reclutamiento/Forms/AllItems.aspx?id=%2Fsites%2Fbibliotecanm%2FApp%20Reclutamiento%2FSustentos&viewid=6ab057b6%2Ddc09%2D4f59%2D8de4%2D0d2000e65d15',
    'App Reclutamiento / Sustentos'
WHERE current_database() = 'abril'
  AND NOT EXISTS (SELECT 1 FROM gth_sustento_folder WHERE state = true);
