-- ============================================================================
-- Solicitud de Salidas — Carpeta de capturas de movilidad en BD (no en appsettings)
-- Fecha: 2026-07-24
--
-- Antes las capturas se subían a un sitio de SharePoint fijo (CostosyPresupuestos)
-- tomado de appsettings + carpeta hardcodeada ("Capturas de movilidades"). Ese sitio
-- está restringido a costos/admins, así que el resto de trabajadores no podía ver sus
-- capturas. Ahora el destino se define POR BASE DE DATOS en la tabla singleton
-- ga_captura_folder y se puede cambiar sin redeploy:
--   - dev  (BD != 'abril')  → biblioteca "Desarrollo" / App Solicitud de Salidas / Capturas de salidas
--   - prod (BD  = 'abril')  → biblioteca "App Solicitud de Salidas" / Capturas de salidas
-- ambas en el sitio /sites/bibliotecanm (accesible para todos).
--
-- El servicio lee la primera fila vigente (state = true, active = true) y resuelve el
-- link vía Graph al subir. Mismo patrón que gth_sustento_folder (Reclutamiento).
--
-- Idempotente: CREATE TABLE IF NOT EXISTS + inserts guardados por NOT EXISTS.
-- El seed se auto-selecciona por current_database(): la carpeta de PRODUCCIÓN solo se
-- inserta en la BD llamada 'abril'; cualquier otra BD recibe la de desarrollo.
-- Seguro de correr tal cual en ambos entornos.
-- ============================================================================

-- 1) Tabla singleton ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS ga_captura_folder (
    ga_captura_folder_id integer GENERATED BY DEFAULT AS IDENTITY,
    link_url          text    NOT NULL,
    folder_name       text    NULL,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer NULL,
    updated_date_time timestamptz NULL,
    updated_user_id   integer NULL,
    active            boolean NOT NULL DEFAULT true,
    state             boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_ga_captura_folder PRIMARY KEY (ga_captura_folder_id)
);

-- Garantiza que solo haya una fila vigente (state = true) a la vez.
CREATE UNIQUE INDEX IF NOT EXISTS ux_ga_captura_folder_singleton
    ON ga_captura_folder ((true)) WHERE state = true;

-- 2) Seed de DESARROLLO (cualquier BD que no sea la de producción) ------------
INSERT INTO ga_captura_folder (link_url, folder_name)
SELECT
    'https://abrilinmob.sharepoint.com/sites/bibliotecanm/Desarrollo/Forms/AllItems.aspx?id=%2Fsites%2Fbibliotecanm%2FDesarrollo%2FApp%20Solicitud%20de%20Salidas%2FCapturas%20de%20salidas&viewid=087a516f%2Da398%2D433d%2Db208%2Df4aa51591a4d',
    'Desarrollo / App Solicitud de Salidas / Capturas de salidas'
WHERE current_database() <> 'abril'
  AND NOT EXISTS (SELECT 1 FROM ga_captura_folder WHERE state = true);

-- 3) Seed de PRODUCCIÓN (solo en la BD 'abril') ------------------------------
INSERT INTO ga_captura_folder (link_url, folder_name)
SELECT
    'https://abrilinmob.sharepoint.com/sites/bibliotecanm/App%20Solicitud%20de%20Salidas/Forms/AllItems.aspx?id=%2Fsites%2Fbibliotecanm%2FApp%20Solicitud%20de%20Salidas%2FCapturas%20de%20salidas&viewid=413a3b2d%2Db4fd%2D4278%2Db87c%2De24587b6cf5c',
    'App Solicitud de Salidas / Capturas de salidas'
WHERE current_database() = 'abril'
  AND NOT EXISTS (SELECT 1 FROM ga_captura_folder WHERE state = true);
