namespace Abril_Backend.Features.Ssoma.Paso.Dtos;

public class PasoCategoriaDto { public int Id { get; set; } public string Nombre { get; set; } = ""; public string Ambito { get; set; } = ""; public string? Icono { get; set; } }
public class PasoEjecucionArchivoDto { public int Id { get; set; } public int EjecucionId { get; set; } public string ArchivoUrl { get; set; } = ""; public string ArchivoNombre { get; set; } = ""; public string? ArchivoSpId { get; set; } public int Orden { get; set; } public DateTime CreatedAt { get; set; } }
public class PasoEjecucionDto { public int Id { get; set; } public int ActividadId { get; set; } public DateOnly FechaProgramada { get; set; } public DateOnly? FechaVerificacion { get; set; } public DateOnly? FechaEjecutada { get; set; } public DateOnly? FechaReprogramada { get; set; } public string? MotivoReprogramacion { get; set; } public string Estado { get; set; } = "Programado"; public string? Observaciones { get; set; } public int? ParticipantesCount { get; set; } public string? EvidenciaNombre { get; set; } public string? EvidenciaUrl { get; set; } public string? EvidenciaSpId { get; set; } public string? RegistradoPorNombre { get; set; } public DateTime CreatedAt { get; set; } public List<PasoEjecucionArchivoDto> Archivos { get; set; } = new(); }
public class RegistrarEjecucionRequest { public int ActividadId { get; set; } public DateOnly FechaProgramada { get; set; } public DateOnly FechaEjecutada { get; set; } public DateOnly? FechaVerificacion { get; set; } public string? Observaciones { get; set; } public int? ParticipantesCount { get; set; } }
public class ReprogramarEjecucionRequest { public DateOnly NuevaFecha { get; set; } public string Motivo { get; set; } = ""; }
public class SubirEvidenciaRequest { public string EvidenciaNombre { get; set; } = ""; public string EvidenciaUrl { get; set; } = ""; public string EvidenciaSpId { get; set; } = ""; }
public class PasoActividadDto { public int Id { get; set; } public int PasoId { get; set; } public int CategoriaId { get; set; } public string CategoriaNombre { get; set; } = ""; public string CategoriaAmbito { get; set; } = ""; public string? CategoriaIcono { get; set; } public string Nombre { get; set; } = ""; public string? Descripcion { get; set; } public string? Alcance { get; set; } public string Frecuencia { get; set; } = ""; public int? ResponsableId { get; set; } public string? ResponsableNombre { get; set; } public string? ResponsableTexto { get; set; } public int MesInicio { get; set; } public int MesFin { get; set; } public int CantidadPlanificada { get; set; } public decimal? Horas { get; set; } public string? Recursos { get; set; } public string Indicador { get; set; } = ""; public string Meta { get; set; } = ""; public int? Orden { get; set; } public bool Activo { get; set; } public List<PasoEjecucionDto> Ejecuciones { get; set; } = new(); public int EjecucionesTotal { get; set; } public int EjecucionesCompletadas { get; set; } public int EjecucionesVencidas { get; set; } public decimal Spi { get; set; } }
public class EliminarActividadRequest { public string Motivo { get; set; } = ""; }
public class PasoAuditoriaDto { public int Id { get; set; } public string Tipo { get; set; } = ""; public string? Descripcion { get; set; } public string? Motivo { get; set; } public string? ValorAnterior { get; set; } public string? ValorNuevo { get; set; } public int? UsuarioId { get; set; } public string CreatedAt { get; set; } = ""; }
public class CrearActividadRequest { public int PasoId { get; set; } public int CategoriaId { get; set; } public string Nombre { get; set; } = ""; public string? Descripcion { get; set; } public string? Alcance { get; set; } public string Frecuencia { get; set; } = "Mensual"; public int? ResponsableId { get; set; } public string? ResponsableTexto { get; set; } public int MesInicio { get; set; } = 1; public int MesFin { get; set; } = 12; public int CantidadPlanificada { get; set; } = 1; public decimal? Horas { get; set; } public string? Recursos { get; set; } public string Indicador { get; set; } = "N° Actividades Ejecutadas/N°Programadas*100"; public string Meta { get; set; } = "100%"; public int? Orden { get; set; } }
public class EditarActividadRequest { public int CategoriaId { get; set; } public string Nombre { get; set; } = ""; public string? Descripcion { get; set; } public string? Alcance { get; set; } public string Frecuencia { get; set; } = "Mensual"; public int? ResponsableId { get; set; } public string? ResponsableTexto { get; set; } public int MesInicio { get; set; } public int MesFin { get; set; } public int CantidadPlanificada { get; set; } public decimal? Horas { get; set; } public string? Recursos { get; set; } public string Indicador { get; set; } = "N° Actividades Ejecutadas/N°Programadas*100"; public string Meta { get; set; } = "100%"; public int? Orden { get; set; } }
public class PasoListItemDto { public int Id { get; set; } public int? ProyectoId { get; set; } public string? ProyectoNombre { get; set; } public int? PlantillaId { get; set; } public string Nombre { get; set; } = ""; public int? Anio { get; set; } public int MesInicio { get; set; } public bool EsPlantilla { get; set; } public string Estado { get; set; } = ""; public string? AprobadoPorNombre { get; set; } public DateTime? AprobadoEn { get; set; } public DateTime CreatedAt { get; set; } public int TotalActividades { get; set; } public int TotalPlanificadas { get; set; } public int TotalEjecutadas { get; set; } public int TotalVencidas { get; set; } public decimal Spi { get; set; } public decimal PorcentajeAvance { get; set; } }
public class PasoDetalleDto : PasoListItemDto { public List<PasoActividadDto> Actividades { get; set; } = new(); }
public class CrearPasoRequest { public int? ProyectoId { get; set; } public string Nombre { get; set; } = ""; public int Anio { get; set; } public int MesInicio { get; set; } = 1; public bool EsPlantilla { get; set; } = false; }
public class EditarPasoRequest { public string Nombre { get; set; } = ""; public int Anio { get; set; } public int MesInicio { get; set; } = 1; }
public class InstanciarPasoRequest { public int ProyectoId { get; set; } public string Nombre { get; set; } = ""; public int Anio { get; set; } public int MesInicio { get; set; } = 1; }
public class GanttItemDto { public int Id { get; set; } public string Nombre { get; set; } = ""; public string Ambito { get; set; } = ""; public string Frecuencia { get; set; } = ""; public int MesInicio { get; set; } public int MesFin { get; set; } public string? ResponsableNombre { get; set; } public List<GanttMesDto> Meses { get; set; } = new(); }
public class GanttMesDto { public int Mes { get; set; } public bool Planificado { get; set; } public string Estado { get; set; } = ""; public int? EjecucionId { get; set; } }
public class ProgramarEjecucionRequest { public int ActividadId { get; set; } public DateOnly FechaProgramada { get; set; } }
public class PasoSpiDto { public decimal SpiGeneral { get; set; } public string SpiColor { get; set; } = ""; public decimal PorcentajeAvance { get; set; } public int PlanificadasAHoy { get; set; } public int EjecutadasAHoy { get; set; } public int TotalProgramadas { get; set; } public int TotalEjecutadas { get; set; } public int TotalVencidas { get; set; } public int ProximasAVencer { get; set; } public SpiPorAmbitoDto Seguridad { get; set; } = new(); public SpiPorAmbitoDto Salud { get; set; } = new(); public SpiPorAmbitoDto Ambiente { get; set; } = new(); public SpiPorAmbitoDto Ssoma { get; set; } = new(); }
public class SpiPorAmbitoDto { public decimal Spi { get; set; } public string Color { get; set; } = ""; public int Planificadas { get; set; } public int Ejecutadas { get; set; } public int Vencidas { get; set; } }
public class PasoDashboardDto { public int AnioActual { get; set; } public int TotalProgramas { get; set; } public int ProgramasActivos { get; set; } public decimal SpiConsolidado { get; set; } public string SpiColor { get; set; } = ""; public decimal PorcentajeAvanceConsolidado { get; set; } public int TotalVencidas { get; set; } public int TotalProximasVencer { get; set; } public List<PasoPorProyectoDto> PorProyecto { get; set; } = new(); public SpiPorAmbitoDto Seguridad { get; set; } = new(); public SpiPorAmbitoDto Salud { get; set; } = new(); public SpiPorAmbitoDto Ambiente { get; set; } = new(); }
public class PasoPorProyectoDto { public int ProyectoId { get; set; } public string ProyectoNombre { get; set; } = ""; public int PasoId { get; set; } public decimal Spi { get; set; } public string SpiColor { get; set; } = ""; public decimal PorcentajeAvance { get; set; } public int Vencidas { get; set; } }
public class PasoAlertaDto { public int EjecucionId { get; set; } public int ActividadId { get; set; } public string ActividadNombre { get; set; } = ""; public int PasoId { get; set; } public string PasoNombre { get; set; } = ""; public string? ProyectoNombre { get; set; } public DateOnly FechaProgramada { get; set; } public string TipoAlerta { get; set; } = ""; public string? ResponsableNombre { get; set; } }
public class PasoListQuery { public int? ProyectoId { get; set; } public int? Anio { get; set; } public string? Estado { get; set; } public bool? EsPlantilla { get; set; } public int Page { get; set; } = 1; public int PageSize { get; set; } = 20; }
public class PagedResult<T> { public List<T> Items { get; set; } = new(); public int Total { get; set; } public int Page { get; set; } public int PageSize { get; set; } public int TotalPages => (int)Math.Ceiling((double)Total / PageSize); }
public class PasoResumenMesAmbitoDto { public int Programadas { get; set; } public int Completadas { get; set; } public int Pendientes { get; set; } public int Vencidas { get; set; } }
public class PasoResumenMesActividadDto { public int ActividadId { get; set; } public string Nombre { get; set; } = ""; public string CategoriaNombre { get; set; } = ""; public string CategoriaAmbito { get; set; } = ""; public string Frecuencia { get; set; } = ""; public int? EjecucionId { get; set; } public DateOnly? FechaProgramada { get; set; } public string Estado { get; set; } = ""; public DateOnly? FechaEjecutada { get; set; } public string? Observaciones { get; set; } public string? EvidenciaNombre { get; set; } public string? EvidenciaUrl { get; set; } public List<PasoEjecucionArchivoDto> Archivos { get; set; } = new(); }
public class PasoResumenMesDto { public int Anio { get; set; } public int Mes { get; set; } public string NombreMes { get; set; } = ""; public int TotalProgramadas { get; set; } public int Completadas { get; set; } public int Pendientes { get; set; } public int Vencidas { get; set; } public int PorcentajeAvance { get; set; } public PasoResumenMesAmbitoDto Seguridad { get; set; } = new(); public PasoResumenMesAmbitoDto Salud { get; set; } = new(); public PasoResumenMesAmbitoDto Ambiente { get; set; } = new(); public PasoResumenMesAmbitoDto Ssoma { get; set; } = new(); public List<PasoResumenMesActividadDto> Actividades { get; set; } = new(); }
public class PasoHistoricoAnioDto { public int Anio { get; set; } public int TotalProgramadas { get; set; } public int TotalEjecutadas { get; set; } public int TotalVencidas { get; set; } public decimal SpiGeneral { get; set; } public string SpiColor { get; set; } = "rojo"; public decimal PorcentajeAvance { get; set; } }

public class PasoSaludListQuery { public int? ProyectoId { get; set; } public int? CategoriaId { get; set; } public int? Anio { get; set; } public int? Mes { get; set; } public bool? Cumplida { get; set; } public int Page { get; set; } = 1; public int PageSize { get; set; } = 20; }

public class PasoSaludActividadListItemDto
{
    public int EjecucionId { get; set; }
    public int ActividadId { get; set; }
    public int PasoId { get; set; }
    public int? ProyectoId { get; set; }
    public string ProyectoNombre { get; set; } = "";
    public int CategoriaId { get; set; }
    public string CategoriaNombre { get; set; } = "";
    public string? CategoriaIcono { get; set; }
    public string ActividadNombre { get; set; } = "";
    public string Frecuencia { get; set; } = "";
    public DateOnly FechaProgramada { get; set; }
    public DateOnly? FechaEjecutada { get; set; }
    public string Estado { get; set; } = "";
    public bool Cumplida { get; set; }
    public string? Observaciones { get; set; }
    public int? ParticipantesCount { get; set; }
    public string? EvidenciaUrl { get; set; }
    public string? EvidenciaNombre { get; set; }
    public string? ResponsableNombre { get; set; }
}
