-- Esquema del feature "Dossier Semanal" (habilitacion/gestion/dossier)
-- Ejecutar en pgAdmin. Es idempotente (usa IF NOT EXISTS) por si alguna parte ya existe.

CREATE TABLE IF NOT EXISTS ss_dossier_semana (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contributor_id  integer NOT NULL,
    proyecto_id     integer NOT NULL,
    anio            integer NOT NULL,
    numero_semana   integer NOT NULL,
    fecha_inicio    timestamp with time zone NOT NULL,
    fecha_fin       timestamp with time zone NOT NULL,
    estado          text NOT NULL,
    obs_revisor     text NULL,
    created_at      timestamp with time zone NOT NULL,
    updated_at      timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_ss_dossier_semana_contributor_id_proyecto_id_anio_numero_se
    ON ss_dossier_semana (contributor_id, proyecto_id, anio, numero_semana);

CREATE TABLE IF NOT EXISTS ss_dossier_documento (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dossier_id      integer NOT NULL,
    tipo_doc        text NOT NULL,
    nombre_archivo  text NULL,
    archivo_path    text NULL,
    estado          text NOT NULL,
    obs_revisor     text NULL,
    created_at      timestamp with time zone NOT NULL,
    updated_at      timestamp with time zone NOT NULL,
    CONSTRAINT fk_ss_dossier_documento_ss_dossier_semana_dossier_id
        FOREIGN KEY (dossier_id) REFERENCES ss_dossier_semana (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_ss_dossier_documento_dossier_id_tipo_doc
    ON ss_dossier_documento (dossier_id, tipo_doc);

CREATE TABLE IF NOT EXISTS ss_dossier_documento_archivo (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id    integer NOT NULL,
    nombre_archivo  text NOT NULL,
    archivo_path    text NOT NULL,
    created_at      timestamp with time zone NOT NULL,
    CONSTRAINT fk_ss_dossier_documento_archivo_ss_dossier_documento_documento
        FOREIGN KEY (documento_id) REFERENCES ss_dossier_documento (id) ON DELETE CASCADE
);
