using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Abril_Backend.Migrations
{
    /// <inheritdoc />
    public partial class AddSsomaProgInspeccionEmpresa : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DO $$ BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'ga_solicitud_salida' AND column_name = 'aprobador_email'
                    ) THEN
                        ALTER TABLE ga_solicitud_salida DROP COLUMN aprobador_email;
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$ BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'ga_solicitud_salida' AND column_name = 'aprobador_worker_id'
                    ) THEN
                        ALTER TABLE ga_solicitud_salida ADD aprobador_worker_id integer;
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ssoma_prog_inspeccion_empresa (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    proyecto_id integer NOT NULL,
                    empresa_id integer,
                    empresa_tipo text NOT NULL,
                    mes integer NOT NULL,
                    anio integer NOT NULL,
                    inspeccion_tipo_id integer NOT NULL,
                    creado_por integer,
                    created_at timestamp with time zone NOT NULL,
                    updated_at timestamp with time zone,
                    CONSTRAINT pk_ssoma_prog_inspeccion_empresa PRIMARY KEY (id),
                    CONSTRAINT fk_ssoma_prog_inspeccion_empresa_contributor_empresa_id
                        FOREIGN KEY (empresa_id) REFERENCES contributor(contributor_id),
                    CONSTRAINT fk_ssoma_prog_inspeccion_empresa_project_proyecto_id
                        FOREIGN KEY (proyecto_id) REFERENCES project(project_id) ON DELETE CASCADE,
                    CONSTRAINT fk_ssoma_prog_inspeccion_empresa_ssoma_inspeccion_tipo_inspecc
                        FOREIGN KEY (inspeccion_tipo_id) REFERENCES ssoma_inspeccion_tipo(id) ON DELETE CASCADE
                );
                CREATE UNIQUE INDEX IF NOT EXISTS ix_ssoma_prog_inspeccion_empresa_proyecto_id_empresa_id_empres
                    ON ssoma_prog_inspeccion_empresa (proyecto_id, empresa_id, empresa_tipo, mes, anio, inspeccion_tipo_id);
                CREATE INDEX IF NOT EXISTS ix_ssoma_prog_inspeccion_empresa_empresa_id
                    ON ssoma_prog_inspeccion_empresa (empresa_id);
                CREATE INDEX IF NOT EXISTS ix_ssoma_prog_inspeccion_empresa_inspeccion_tipo_id
                    ON ssoma_prog_inspeccion_empresa (inspeccion_tipo_id);
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS vecino_licencia (
                    vecino_licencia_id integer GENERATED BY DEFAULT AS IDENTITY,
                    archivo_url text NOT NULL,
                    original_file_name text,
                    fecha_vencimiento date NOT NULL,
                    fecha_recordatorio date NOT NULL,
                    dias_antes integer NOT NULL,
                    created_date_time timestamp with time zone NOT NULL,
                    created_user_id integer NOT NULL,
                    updated_date_time timestamp with time zone,
                    updated_user_id integer,
                    active boolean NOT NULL,
                    state boolean NOT NULL,
                    CONSTRAINT pk_vecino_licencia PRIMARY KEY (vecino_licencia_id)
                );
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ssoma_prog_inspeccion_empresa");

            migrationBuilder.DropTable(
                name: "vecino_licencia");

            migrationBuilder.DropColumn(
                name: "aprobador_worker_id",
                table: "ga_solicitud_salida");

            migrationBuilder.AddColumn<string>(
                name: "aprobador_email",
                table: "ga_solicitud_salida",
                type: "text",
                nullable: true);
        }
    }
}
