using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Abril_Backend.Migrations
{
    /// <inheritdoc />
    public partial class AddSsAlertaSsoma : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS ss_alertas_ssoma (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    tipo_alerta text NOT NULL,
                    referencia_id text NOT NULL,
                    fecha_alerta date NOT NULL,
                    enviado_email boolean NOT NULL,
                    fecha_envio timestamp with time zone,
                    destinatarios text,
                    created_at timestamp with time zone NOT NULL,
                    CONSTRAINT pk_ss_alertas_ssoma PRIMARY KEY (id)
                );
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ss_alertas_ssoma");
        }
    }
}
