using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Abril_Backend.Migrations
{
    /// <inheritdoc />
    public partial class AddContributorMigracionFields : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Idempotent: drop only if exists
            migrationBuilder.Sql(
                "ALTER TABLE project_sub_contractor DROP COLUMN IF EXISTS contract_origin_id;");

            // Idempotent rename: only if old name still exists
            migrationBuilder.Sql("""
                DO $$
                BEGIN
                  IF EXISTS (SELECT 1 FROM information_schema.columns
                             WHERE table_name='ga_solicitud_salida' AND column_name='estado') THEN
                    ALTER TABLE ga_solicitud_salida RENAME COLUMN estado TO estado_rendicion;
                  END IF;
                END $$;
                """);

            migrationBuilder.Sql("""
                DO $$
                BEGIN
                  IF EXISTS (SELECT 1 FROM information_schema.columns
                             WHERE table_name='ac_actividades' AND column_name='indice') THEN
                    IF EXISTS (SELECT 1 FROM information_schema.columns
                               WHERE table_name='ac_actividades' AND column_name='user_id2') THEN
                      ALTER TABLE ac_actividades DROP COLUMN indice;
                    ELSE
                      ALTER TABLE ac_actividades RENAME COLUMN indice TO user_id2;
                    END IF;
                  END IF;
                END $$;
                """);

            // Make motivo_id nullable if not already
            migrationBuilder.Sql("""
                ALTER TABLE ga_solicitud_salida ALTER COLUMN motivo_id DROP NOT NULL;
                """);

            // Idempotent AddColumn
            migrationBuilder.Sql("ALTER TABLE ga_solicitud_salida ADD COLUMN IF NOT EXISTS aprobador_email text;");
            migrationBuilder.Sql("ALTER TABLE ga_solicitud_salida ADD COLUMN IF NOT EXISTS estado_aprobacion text NOT NULL DEFAULT '';");
            migrationBuilder.Sql("ALTER TABLE ga_solicitud_salida ADD COLUMN IF NOT EXISTS fecha_decision timestamp with time zone;");
            migrationBuilder.Sql("ALTER TABLE ga_solicitud_salida ADD COLUMN IF NOT EXISTS motivo_libre text;");
            migrationBuilder.Sql("ALTER TABLE ga_solicitud_salida ADD COLUMN IF NOT EXISTS motivo_rechazo text;");
            migrationBuilder.Sql("ALTER TABLE contributor ADD COLUMN IF NOT EXISTS contributor_nombre_comercial text;");
            migrationBuilder.Sql("ALTER TABLE contributor ADD COLUMN IF NOT EXISTS sp_password_temp text;");
            migrationBuilder.Sql("ALTER TABLE ac_actividades ADD COLUMN IF NOT EXISTS orden integer;");
            migrationBuilder.Sql("ALTER TABLE ac_actividades ADD COLUMN IF NOT EXISTS spi numeric;");

            // Idempotent CreateTable
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS ac_avance_semanal (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    actividad_id integer NOT NULL,
                    semana date NOT NULL,
                    porcentaje_avance numeric NOT NULL,
                    spi numeric NOT NULL,
                    created_at timestamp with time zone
                );
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS costos_presupuestos_email (
                    costos_presupuestos_email_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    email text NOT NULL,
                    created_date_time timestamp with time zone NOT NULL,
                    created_user_id integer NOT NULL,
                    updated_date_time timestamp with time zone,
                    updated_user_id integer,
                    active boolean NOT NULL,
                    state boolean NOT NULL
                );
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ac_avance_semanal");

            migrationBuilder.DropTable(
                name: "costos_presupuestos_email");

            migrationBuilder.DropColumn(
                name: "aprobador_email",
                table: "ga_solicitud_salida");

            migrationBuilder.DropColumn(
                name: "estado_aprobacion",
                table: "ga_solicitud_salida");

            migrationBuilder.DropColumn(
                name: "fecha_decision",
                table: "ga_solicitud_salida");

            migrationBuilder.DropColumn(
                name: "motivo_libre",
                table: "ga_solicitud_salida");

            migrationBuilder.DropColumn(
                name: "motivo_rechazo",
                table: "ga_solicitud_salida");

            migrationBuilder.DropColumn(
                name: "contributor_nombre_comercial",
                table: "contributor");

            migrationBuilder.DropColumn(
                name: "sp_password_temp",
                table: "contributor");

            migrationBuilder.DropColumn(
                name: "orden",
                table: "ac_actividades");

            migrationBuilder.DropColumn(
                name: "spi",
                table: "ac_actividades");

            migrationBuilder.RenameColumn(
                name: "estado_rendicion",
                table: "ga_solicitud_salida",
                newName: "estado");

            migrationBuilder.RenameColumn(
                name: "user_id2",
                table: "ac_actividades",
                newName: "indice");

            migrationBuilder.AddColumn<int>(
                name: "contract_origin_id",
                table: "project_sub_contractor",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AlterColumn<int>(
                name: "motivo_id",
                table: "ga_solicitud_salida",
                type: "integer",
                nullable: false,
                defaultValue: 0,
                oldClrType: typeof(int),
                oldType: "integer",
                oldNullable: true);
        }
    }
}
