using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Abril_Backend.Migrations
{
    /// <inheritdoc />
    public partial class AddFotoBase64 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Todas las columnas y tablas se crean con IF NOT EXISTS para ser idempotentes
            migrationBuilder.Sql("""
                ALTER TABLE workers ADD COLUMN IF NOT EXISTS auto_approve_lesson boolean NOT NULL DEFAULT false;

                ALTER TABLE ssoma_amonestaciones ADD COLUMN IF NOT EXISTS documento_firmado_url text;
                ALTER TABLE ssoma_amonestaciones ADD COLUMN IF NOT EXISTS estado text NOT NULL DEFAULT '';
                ALTER TABLE ssoma_amonestaciones ADD COLUMN IF NOT EXISTS fecha_cierre timestamptz;

                ALTER TABLE ssoma_amonestacion_fotos ADD COLUMN IF NOT EXISTS base64data text;

                ALTER TABLE ss_entregable_tipo ADD COLUMN IF NOT EXISTS aplica_a text NOT NULL DEFAULT '';
                ALTER TABLE ss_descanso_medico ADD COLUMN IF NOT EXISTS es_recaida boolean NOT NULL DEFAULT false;

                ALTER TABLE ss_accidente_trabajo ADD COLUMN IF NOT EXISTS fecha_reinduccion date;
                ALTER TABLE ss_accidente_trabajo ADD COLUMN IF NOT EXISTS flash_report_id integer;
                ALTER TABLE ss_accidente_trabajo ADD COLUMN IF NOT EXISTS reinduccion_completada boolean NOT NULL DEFAULT false;
                ALTER TABLE ss_accidente_trabajo ADD COLUMN IF NOT EXISTS reinduccion_por_id integer;
                ALTER TABLE ss_accidente_trabajo ADD COLUMN IF NOT EXISTS requiere_reinduccion boolean NOT NULL DEFAULT false;

                ALTER TABLE ss_accidente_incidente ADD COLUMN IF NOT EXISTS atencion_medica text;
                ALTER TABLE ss_accidente_incidente ADD COLUMN IF NOT EXISTS centro_atencion text;
                ALTER TABLE ss_accidente_incidente ADD COLUMN IF NOT EXISTS danio_proceso_flag boolean NOT NULL DEFAULT false;
                ALTER TABLE ss_accidente_incidente ADD COLUMN IF NOT EXISTS tipo_contacto text;
                ALTER TABLE ss_accidente_incidente ADD COLUMN IF NOT EXISTS turno text;
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS invoice_document_type (
                    invoice_document_type_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    description text NOT NULL,
                    created_date_time timestamptz NOT NULL,
                    created_user_id integer,
                    updated_date_time timestamptz,
                    updated_user_id integer,
                    active boolean NOT NULL,
                    state boolean NOT NULL
                );
                CREATE TABLE IF NOT EXISTS invoice_folder (
                    invoice_folder_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name text NOT NULL,
                    link_url text NOT NULL,
                    drive_id text NOT NULL,
                    folder_id text NOT NULL,
                    folder_name text,
                    web_url text,
                    created_date_time timestamptz NOT NULL,
                    created_user_id integer NOT NULL,
                    updated_date_time timestamptz,
                    updated_user_id integer,
                    active boolean NOT NULL,
                    state boolean NOT NULL
                );
                CREATE TABLE IF NOT EXISTS invoice_payment_form (
                    invoice_payment_form_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    invoice_payment_form_description text NOT NULL,
                    created_date_time timestamptz NOT NULL,
                    created_user_id integer,
                    updated_date_time timestamptz,
                    updated_user_id integer,
                    active boolean NOT NULL,
                    state boolean NOT NULL
                );
                CREATE TABLE IF NOT EXISTS ss_accidente_trabajador (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    accidente_incidente_id integer NOT NULL REFERENCES ss_accidente_incidente(id) ON DELETE CASCADE,
                    worker_id integer,
                    trabajador_nombre text NOT NULL,
                    puesto_trabajo text,
                    edad integer,
                    anios_experiencia integer,
                    celular_trabajador text,
                    parte_afectada_id integer,
                    created_at timestamptz NOT NULL
                );
                CREATE INDEX IF NOT EXISTS ix_ss_accidente_trabajador_accidente_incidente_id ON ss_accidente_trabajador(accidente_incidente_id);
                CREATE TABLE IF NOT EXISTS invoice (
                    invoice_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    issue_date date NOT NULL,
                    serie text NOT NULL,
                    correlativo text NOT NULL,
                    invoice_number text,
                    proveedor_name text,
                    abril_name text,
                    payment_order_number text,
                    invoice_document_type_id integer REFERENCES invoice_document_type(invoice_document_type_id) ON DELETE RESTRICT,
                    authorized_amount numeric,
                    observation text,
                    contributor_id integer REFERENCES contributor(contributor_id) ON DELETE RESTRICT,
                    description text NOT NULL,
                    invoice_payment_form_id integer REFERENCES invoice_payment_form(invoice_payment_form_id) ON DELETE RESTRICT,
                    total numeric NOT NULL,
                    currency_id integer REFERENCES currency(currency_id) ON DELETE RESTRICT,
                    document_url text,
                    invoice_folder_id integer REFERENCES invoice_folder(invoice_folder_id) ON DELETE RESTRICT,
                    abril_contributor_id integer REFERENCES contributor(contributor_id) ON DELETE RESTRICT,
                    created_date_time timestamptz NOT NULL,
                    created_user_id integer,
                    updated_date_time timestamptz,
                    updated_user_id integer,
                    active boolean NOT NULL,
                    state boolean NOT NULL
                );
                CREATE INDEX IF NOT EXISTS ix_invoice_abril_contributor_id ON invoice(abril_contributor_id);
                CREATE INDEX IF NOT EXISTS ix_invoice_contributor_id ON invoice(contributor_id);
                CREATE INDEX IF NOT EXISTS ix_invoice_currency_id ON invoice(currency_id);
                CREATE INDEX IF NOT EXISTS ix_invoice_invoice_document_type_id ON invoice(invoice_document_type_id);
                CREATE INDEX IF NOT EXISTS ix_invoice_invoice_folder_id ON invoice(invoice_folder_id);
                CREATE INDEX IF NOT EXISTS ix_invoice_invoice_payment_form_id ON invoice(invoice_payment_form_id);
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS invoice;
                DROP TABLE IF EXISTS ss_accidente_trabajador;
                DROP TABLE IF EXISTS invoice_document_type;
                DROP TABLE IF EXISTS invoice_folder;
                DROP TABLE IF EXISTS invoice_payment_form;

                ALTER TABLE workers DROP COLUMN IF EXISTS auto_approve_lesson;
                ALTER TABLE ssoma_amonestaciones DROP COLUMN IF EXISTS documento_firmado_url;
                ALTER TABLE ssoma_amonestaciones DROP COLUMN IF EXISTS estado;
                ALTER TABLE ssoma_amonestaciones DROP COLUMN IF EXISTS fecha_cierre;
                ALTER TABLE ssoma_amonestacion_fotos DROP COLUMN IF EXISTS base64data;
                ALTER TABLE ss_entregable_tipo DROP COLUMN IF EXISTS aplica_a;
                ALTER TABLE ss_descanso_medico DROP COLUMN IF EXISTS es_recaida;
                ALTER TABLE ss_accidente_trabajo DROP COLUMN IF EXISTS fecha_reinduccion;
                ALTER TABLE ss_accidente_trabajo DROP COLUMN IF EXISTS flash_report_id;
                ALTER TABLE ss_accidente_trabajo DROP COLUMN IF EXISTS reinduccion_completada;
                ALTER TABLE ss_accidente_trabajo DROP COLUMN IF EXISTS reinduccion_por_id;
                ALTER TABLE ss_accidente_trabajo DROP COLUMN IF EXISTS requiere_reinduccion;
                ALTER TABLE ss_accidente_incidente DROP COLUMN IF EXISTS atencion_medica;
                ALTER TABLE ss_accidente_incidente DROP COLUMN IF EXISTS centro_atencion;
                ALTER TABLE ss_accidente_incidente DROP COLUMN IF EXISTS danio_proceso_flag;
                ALTER TABLE ss_accidente_incidente DROP COLUMN IF EXISTS tipo_contacto;
                ALTER TABLE ss_accidente_incidente DROP COLUMN IF EXISTS turno;
                """);
        }
    }
}
