using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Abril_Backend.Migrations
{
    /// <inheritdoc />
    public partial class AddCatalogAndScope : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Drops idempotentes
            migrationBuilder.Sql("ALTER TABLE ss_alertas_emo DROP CONSTRAINT IF EXISTS fk_ss_alertas_emo_worker_emos_emo_id");
            migrationBuilder.Sql("ALTER TABLE ss_alertas_emo DROP CONSTRAINT IF EXISTS fk_ss_alertas_emo_workers_worker_id");
            migrationBuilder.Sql("ALTER TABLE workers DROP COLUMN IF EXISTS apellido_nombre");
            migrationBuilder.Sql("ALTER TABLE workers DROP COLUMN IF EXISTS dni");
            migrationBuilder.Sql("ALTER TABLE workers DROP COLUMN IF EXISTS ruc");
            migrationBuilder.Sql("ALTER TABLE project_sub_contractor DROP COLUMN IF EXISTS contract_id");

            // AddColumn idempotentes
            migrationBuilder.Sql("ALTER TABLE workers ADD COLUMN IF NOT EXISTS contributor_id integer");
            migrationBuilder.Sql("ALTER TABLE workers ADD COLUMN IF NOT EXISTS person_id integer");
            migrationBuilder.Sql("ALTER TABLE work_item_category ADD COLUMN IF NOT EXISTS instructivos_folder_id text");
            migrationBuilder.Sql("ALTER TABLE work_item_category ADD COLUMN IF NOT EXISTS instructivos_folder_name text");
            migrationBuilder.Sql("ALTER TABLE work_item_category ADD COLUMN IF NOT EXISTS instructivos_sync_status integer");
            migrationBuilder.Sql("ALTER TABLE work_item_category ADD COLUMN IF NOT EXISTS instructivos_synced_at timestamptz");
            migrationBuilder.Sql("ALTER TABLE ss_programacion_emos ADD COLUMN IF NOT EXISTS check_in_hora time without time zone");
            migrationBuilder.Sql("ALTER TABLE ss_programacion_emos ADD COLUMN IF NOT EXISTS fecha_notificacion timestamptz");
            migrationBuilder.Sql("ALTER TABLE ss_programacion_emos ADD COLUMN IF NOT EXISTS motivo_rechazo text");
            migrationBuilder.Sql("ALTER TABLE ss_programacion_emos ADD COLUMN IF NOT EXISTS origen text NOT NULL DEFAULT 'Manual'");
            migrationBuilder.Sql("ALTER TABLE ss_clinicas ADD COLUMN IF NOT EXISTS password_hash text NOT NULL DEFAULT ''");
            migrationBuilder.Sql("ALTER TABLE ss_alertas_emo ALTER COLUMN worker_id DROP NOT NULL");
            migrationBuilder.Sql("ALTER TABLE ss_alertas_emo ALTER COLUMN emo_id DROP NOT NULL");
            migrationBuilder.Sql("ALTER TABLE project_sub_contractor ADD COLUMN IF NOT EXISTS contract_modality_id integer");
            migrationBuilder.Sql("ALTER TABLE project_sub_contractor ADD COLUMN IF NOT EXISTS guarantee_fund_days integer");
            migrationBuilder.Sql("ALTER TABLE project_sub_contractor ADD COLUMN IF NOT EXISTS guarantee_fund_percentage integer");
            migrationBuilder.Sql("ALTER TABLE project_sub_contractor ADD COLUMN IF NOT EXISTS project_sub_contractor_instructivo_id integer");
            migrationBuilder.Sql("ALTER TABLE project_sub_contractor ADD COLUMN IF NOT EXISTS project_sub_contractor_non_conforming_output_id integer");
            migrationBuilder.Sql("ALTER TABLE project_sub_contractor ADD COLUMN IF NOT EXISTS project_sub_contractor_tolerance_chart_id integer");
            migrationBuilder.Sql("ALTER TABLE project ADD COLUMN IF NOT EXISTS abbreviation text");
            migrationBuilder.Sql("ALTER TABLE phase_stage_sub_stage_sub_specialty ADD COLUMN IF NOT EXISTS partida_id integer");
            migrationBuilder.Sql("ALTER TABLE lesson ADD COLUMN IF NOT EXISTS catalog_item_id integer");
            migrationBuilder.Sql("ALTER TABLE lesson ADD COLUMN IF NOT EXISTS sub_area_id integer");
            migrationBuilder.Sql("ALTER TABLE contractor_email ADD COLUMN IF NOT EXISTS contractor_person_type_id integer");
            migrationBuilder.Sql("ALTER TABLE contractor ADD COLUMN IF NOT EXISTS activation_token text");
            migrationBuilder.Sql("ALTER TABLE contractor ADD COLUMN IF NOT EXISTS activation_token_expiry timestamptz");
            migrationBuilder.Sql("ALTER TABLE contractor ADD COLUMN IF NOT EXISTS logo_file_url text");
            migrationBuilder.Sql("ALTER TABLE ac_actividades ADD COLUMN IF NOT EXISTS categoria_id integer");
            migrationBuilder.Sql("ALTER TABLE ac_actividades ADD COLUMN IF NOT EXISTS especialidad_id integer");

            // --- CreateTable idempotentes ---
            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS cat_jefatura (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text NOT NULL,
    email text,
    activo boolean NOT NULL
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS catalog_type (
    catalog_type_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_type_name text NOT NULL,
    catalog_type_code text NOT NULL,
    active boolean NOT NULL
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS contract_modality (
    contract_modality_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_modality_description text NOT NULL,
    state boolean NOT NULL,
    created_datetime timestamptz NOT NULL,
    updated_datetime timestamptz
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS contractor_person_type (
    contractor_person_type_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description text NOT NULL,
    state boolean NOT NULL
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS contractor_user (
    contractor_user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contractor_id integer NOT NULL REFERENCES contractor(contractor_id) ON DELETE RESTRICT,
    user_id integer NOT NULL REFERENCES app_user(user_id) ON DELETE RESTRICT,
    created_date_time timestamptz NOT NULL,
    created_user_id integer,
    active boolean NOT NULL,
    state boolean NOT NULL
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS ga_hora_opcion (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hora time NOT NULL,
    etiqueta text NOT NULL,
    activo boolean NOT NULL
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS ga_lugar (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo text NOT NULL,
    nombre text,
    project_id integer,
    activo boolean NOT NULL,
    orden integer NOT NULL,
    created_at timestamptz NOT NULL
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS ga_motivo_salida (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion text NOT NULL,
    activo boolean NOT NULL,
    created_at timestamptz NOT NULL
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS ga_solicitud_salida (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id integer NOT NULL,
    fecha_salida date NOT NULL,
    hora_salida time NOT NULL,
    hora_retorno time,
    motivo_id integer NOT NULL,
    lugar_origen_id integer,
    lugar_origen_libre text,
    lugar_destino_id integer,
    lugar_destino_libre text,
    estado text NOT NULL,
    registrado_por_id integer,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS partida (
    partida_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partida_description text NOT NULL,
    state boolean NOT NULL,
    active boolean NOT NULL,
    created_date_time timestamptz NOT NULL,
    created_user_id integer,
    updated_date_time timestamptz,
    updated_user_id integer
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS project_sub_contractor_instructivo (
    project_sub_contractor_instructivo_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_url text,
    original_file_name text,
    sharepoint_item_id text,
    project_sub_contractor_file_status_id integer REFERENCES project_sub_contractor_file_status(project_sub_contractor_file_status_id),
    observation text,
    created_datetime timestamptz NOT NULL,
    created_user_id integer NOT NULL,
    updated_datetime timestamptz,
    updated_user_id integer,
    active boolean NOT NULL,
    state boolean NOT NULL
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS project_sub_contractor_non_conforming_output (
    project_sub_contractor_non_conforming_output_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_url text,
    original_file_name text,
    sharepoint_item_id text,
    project_sub_contractor_file_status_id integer REFERENCES project_sub_contractor_file_status(project_sub_contractor_file_status_id),
    observation text,
    created_datetime timestamptz NOT NULL,
    created_user_id integer NOT NULL,
    updated_datetime timestamptz,
    updated_user_id integer,
    active boolean NOT NULL,
    state boolean NOT NULL
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS project_sub_contractor_tolerance_chart (
    project_sub_contractor_tolerance_chart_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_url text,
    original_file_name text,
    sharepoint_item_id text,
    project_sub_contractor_file_status_id integer REFERENCES project_sub_contractor_file_status(project_sub_contractor_file_status_id),
    observation text,
    created_datetime timestamptz NOT NULL,
    created_user_id integer NOT NULL,
    updated_datetime timestamptz,
    updated_user_id integer,
    active boolean NOT NULL,
    state boolean NOT NULL
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS psss_scope (
    psss_scope_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phase_stage_sub_stage_sub_specialty_id integer NOT NULL,
    area_id integer,
    sub_area_id integer,
    state boolean NOT NULL
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS psss_template (
    psss_template_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_name text NOT NULL,
    description text,
    state boolean NOT NULL,
    active boolean NOT NULL,
    created_date_time timestamptz NOT NULL,
    created_user_id integer,
    updated_date_time timestamptz,
    updated_user_id integer
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS psss_template_detail (
    psss_template_detail_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    psss_template_id integer NOT NULL,
    phase_stage_sub_stage_sub_specialty_id integer NOT NULL,
    state boolean NOT NULL
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS ss_clinica_emails (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinica_id integer NOT NULL REFERENCES ss_clinicas(id) ON DELETE CASCADE,
    nombre text,
    email text NOT NULL,
    activo boolean NOT NULL
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS ss_clinica_reset_token (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinica_id integer NOT NULL REFERENCES ss_clinicas(id) ON DELETE CASCADE,
    token text NOT NULL,
    expira_en timestamptz NOT NULL,
    usado boolean NOT NULL,
    created_at timestamptz NOT NULL
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS sub_area (
    sub_area_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_id integer NOT NULL REFERENCES area(area_id) ON DELETE CASCADE,
    sub_area_description text NOT NULL,
    active boolean NOT NULL,
    state boolean NOT NULL,
    created_date_time timestamptz NOT NULL,
    created_user_id integer NOT NULL,
    updated_date_time timestamptz,
    updated_user_id integer
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS work_item_category_clause (
    work_item_category_clause_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_item_category_id integer NOT NULL REFERENCES work_item_category(work_item_category_id) ON DELETE CASCADE,
    clause_text text NOT NULL,
    sort_order integer NOT NULL,
    state boolean NOT NULL,
    created_datetime timestamptz NOT NULL,
    created_user_id integer NOT NULL,
    updated_datetime timestamptz,
    updated_user_id integer
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS catalog_item (
    catalog_item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_type_id integer NOT NULL REFERENCES catalog_type(catalog_type_id) ON DELETE CASCADE,
    catalog_item_parent_id integer REFERENCES catalog_item(catalog_item_id) ON DELETE RESTRICT,
    catalog_item_description text NOT NULL,
    catalog_item_code text,
    active boolean NOT NULL
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS area_subarea (
    area_subarea_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_id integer NOT NULL REFERENCES area(area_id) ON DELETE CASCADE,
    sub_area_id integer REFERENCES sub_area(sub_area_id)
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS scope_item (
    scope_item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_subarea_id integer NOT NULL REFERENCES area_subarea(area_subarea_id) ON DELETE CASCADE,
    catalog_item_id integer NOT NULL REFERENCES catalog_item(catalog_item_id) ON DELETE CASCADE,
    scope_item_parent_id integer REFERENCES scope_item(scope_item_id) ON DELETE RESTRICT,
    display_order integer NOT NULL,
    active boolean NOT NULL
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS scope_template (
    scope_template_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_subarea_id integer NOT NULL REFERENCES area_subarea(area_subarea_id) ON DELETE CASCADE,
    template_name text NOT NULL,
    active boolean NOT NULL,
    created_date_time timestamptz NOT NULL,
    created_user_id integer,
    updated_date_time timestamptz,
    updated_user_id integer
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS scope_template_item (
    scope_template_item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_template_id integer NOT NULL REFERENCES scope_template(scope_template_id) ON DELETE CASCADE,
    scope_item_id integer NOT NULL REFERENCES scope_item(scope_item_id) ON DELETE CASCADE,
    active boolean NOT NULL
)");

            // --- CreateIndex idempotentes (con manejo de excepciones por columnas faltantes) ---
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_workers_contributor_id ON workers(contributor_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_workers_person_id ON workers(person_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_project_sub_contractor_project_sub_contractor_instructivo_id ON project_sub_contractor(project_sub_contractor_instructivo_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_project_sub_contractor_project_sub_contractor_non_conformin ON project_sub_contractor(project_sub_contractor_non_conforming_output_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_project_sub_contractor_project_sub_contractor_tolerance_cha ON project_sub_contractor(project_sub_contractor_tolerance_chart_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_contractor_email_contractor_person_type_id ON contractor_email(contractor_person_type_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE UNIQUE INDEX IF NOT EXISTS ix_area_subarea_area_id_sub_area_id ON area_subarea(area_id, sub_area_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_area_subarea_sub_area_id ON area_subarea(sub_area_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_catalog_item_catalog_item_parent_id ON catalog_item(catalog_item_parent_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_catalog_item_catalog_type_id ON catalog_item(catalog_type_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_contractor_user_contractor_id ON contractor_user(contractor_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_contractor_user_user_id ON contractor_user(user_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_project_sub_contractor_instructivo_project_sub_contractor_f ON project_sub_contractor_instructivo(project_sub_contractor_file_status_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_project_sub_contractor_non_conforming_output_project_sub_co ON project_sub_contractor_non_conforming_output(project_sub_contractor_file_status_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_project_sub_contractor_tolerance_chart_project_sub_contract ON project_sub_contractor_tolerance_chart(project_sub_contractor_file_status_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_scope_item_area_subarea_id ON scope_item(area_subarea_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_scope_item_catalog_item_id ON scope_item(catalog_item_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_scope_item_scope_item_parent_id ON scope_item(scope_item_parent_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_scope_template_area_subarea_id ON scope_template(area_subarea_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_scope_template_item_scope_item_id ON scope_template_item(scope_item_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_scope_template_item_scope_template_id ON scope_template_item(scope_template_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_ss_clinica_emails_clinica_id ON ss_clinica_emails(clinica_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_ss_clinica_reset_token_clinica_id ON ss_clinica_reset_token(clinica_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_sub_area_area_id ON sub_area(area_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_work_item_category_clause_work_item_category_id ON work_item_category_clause(work_item_category_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");

            // --- AddForeignKey idempotentes ---
            migrationBuilder.Sql(@"DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contractor_email_contractor_person_type_contractor_person_t') THEN
        ALTER TABLE contractor_email ADD CONSTRAINT fk_contractor_email_contractor_person_type_contractor_person_t FOREIGN KEY (contractor_person_type_id) REFERENCES contractor_person_type(contractor_person_type_id) ON DELETE RESTRICT;
    END IF;
EXCEPTION WHEN OTHERS THEN NULL;
END $$");

            migrationBuilder.Sql(@"DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_project_sub_contractor_project_sub_contractor_instructivo_p') THEN
        ALTER TABLE project_sub_contractor ADD CONSTRAINT fk_project_sub_contractor_project_sub_contractor_instructivo_p FOREIGN KEY (project_sub_contractor_instructivo_id) REFERENCES project_sub_contractor_instructivo(project_sub_contractor_instructivo_id);
    END IF;
EXCEPTION WHEN OTHERS THEN NULL;
END $$");

            migrationBuilder.Sql(@"DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_project_sub_contractor_project_sub_contractor_non_conformin') THEN
        ALTER TABLE project_sub_contractor ADD CONSTRAINT fk_project_sub_contractor_project_sub_contractor_non_conformin FOREIGN KEY (project_sub_contractor_non_conforming_output_id) REFERENCES project_sub_contractor_non_conforming_output(project_sub_contractor_non_conforming_output_id);
    END IF;
EXCEPTION WHEN OTHERS THEN NULL;
END $$");

            migrationBuilder.Sql(@"DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_project_sub_contractor_project_sub_contractor_tolerance_cha') THEN
        ALTER TABLE project_sub_contractor ADD CONSTRAINT fk_project_sub_contractor_project_sub_contractor_tolerance_cha FOREIGN KEY (project_sub_contractor_tolerance_chart_id) REFERENCES project_sub_contractor_tolerance_chart(project_sub_contractor_tolerance_chart_id);
    END IF;
EXCEPTION WHEN OTHERS THEN NULL;
END $$");

            migrationBuilder.Sql(@"DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_ss_alertas_emo_worker_emos_emo_id') THEN
        ALTER TABLE ss_alertas_emo ADD CONSTRAINT fk_ss_alertas_emo_worker_emos_emo_id FOREIGN KEY (emo_id) REFERENCES worker_emos(id);
    END IF;
EXCEPTION WHEN OTHERS THEN NULL;
END $$");

            migrationBuilder.Sql(@"DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_ss_alertas_emo_workers_worker_id') THEN
        ALTER TABLE ss_alertas_emo ADD CONSTRAINT fk_ss_alertas_emo_workers_worker_id FOREIGN KEY (worker_id) REFERENCES workers(id);
    END IF;
EXCEPTION WHEN OTHERS THEN NULL;
END $$");

            migrationBuilder.Sql(@"DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_workers_contributor_contributor_id') THEN
        ALTER TABLE workers ADD CONSTRAINT fk_workers_contributor_contributor_id FOREIGN KEY (contributor_id) REFERENCES contributor(contributor_id);
    END IF;
EXCEPTION WHEN OTHERS THEN NULL;
END $$");

            migrationBuilder.Sql(@"DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_workers_person_person_id') THEN
        ALTER TABLE workers ADD CONSTRAINT fk_workers_person_person_id FOREIGN KEY (person_id) REFERENCES person(person_id);
    END IF;
EXCEPTION WHEN OTHERS THEN NULL;
END $$");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_contractor_email_contractor_person_type_contractor_person_t",
                table: "contractor_email");

            migrationBuilder.DropForeignKey(
                name: "fk_project_sub_contractor_project_sub_contractor_instructivo_p",
                table: "project_sub_contractor");

            migrationBuilder.DropForeignKey(
                name: "fk_project_sub_contractor_project_sub_contractor_non_conformin",
                table: "project_sub_contractor");

            migrationBuilder.DropForeignKey(
                name: "fk_project_sub_contractor_project_sub_contractor_tolerance_cha",
                table: "project_sub_contractor");

            migrationBuilder.DropForeignKey(
                name: "fk_ss_alertas_emo_worker_emos_emo_id",
                table: "ss_alertas_emo");

            migrationBuilder.DropForeignKey(
                name: "fk_ss_alertas_emo_workers_worker_id",
                table: "ss_alertas_emo");

            migrationBuilder.DropForeignKey(
                name: "fk_workers_contributor_contributor_id",
                table: "workers");

            migrationBuilder.DropForeignKey(
                name: "fk_workers_person_person_id",
                table: "workers");

            migrationBuilder.DropTable(
                name: "cat_jefatura");

            migrationBuilder.DropTable(
                name: "contract_modality");

            migrationBuilder.DropTable(
                name: "contractor_person_type");

            migrationBuilder.DropTable(
                name: "contractor_user");

            migrationBuilder.DropTable(
                name: "ga_hora_opcion");

            migrationBuilder.DropTable(
                name: "ga_lugar");

            migrationBuilder.DropTable(
                name: "ga_motivo_salida");

            migrationBuilder.DropTable(
                name: "ga_solicitud_salida");

            migrationBuilder.DropTable(
                name: "partida");

            migrationBuilder.DropTable(
                name: "project_sub_contractor_instructivo");

            migrationBuilder.DropTable(
                name: "project_sub_contractor_non_conforming_output");

            migrationBuilder.DropTable(
                name: "project_sub_contractor_tolerance_chart");

            migrationBuilder.DropTable(
                name: "psss_scope");

            migrationBuilder.DropTable(
                name: "psss_template");

            migrationBuilder.DropTable(
                name: "psss_template_detail");

            migrationBuilder.DropTable(
                name: "scope_template_item");

            migrationBuilder.DropTable(
                name: "ss_clinica_emails");

            migrationBuilder.DropTable(
                name: "ss_clinica_reset_token");

            migrationBuilder.DropTable(
                name: "work_item_category_clause");

            migrationBuilder.DropTable(
                name: "scope_item");

            migrationBuilder.DropTable(
                name: "scope_template");

            migrationBuilder.DropTable(
                name: "catalog_item");

            migrationBuilder.DropTable(
                name: "area_subarea");

            migrationBuilder.DropTable(
                name: "catalog_type");

            migrationBuilder.DropTable(
                name: "sub_area");

            migrationBuilder.DropIndex(
                name: "ix_workers_contributor_id",
                table: "workers");

            migrationBuilder.DropIndex(
                name: "ix_workers_person_id",
                table: "workers");

            migrationBuilder.DropIndex(
                name: "ix_project_sub_contractor_project_sub_contractor_instructivo_id",
                table: "project_sub_contractor");

            migrationBuilder.DropIndex(
                name: "ix_project_sub_contractor_project_sub_contractor_non_conformin",
                table: "project_sub_contractor");

            migrationBuilder.DropIndex(
                name: "ix_project_sub_contractor_project_sub_contractor_tolerance_cha",
                table: "project_sub_contractor");

            migrationBuilder.DropIndex(
                name: "ix_contractor_email_contractor_person_type_id",
                table: "contractor_email");

            migrationBuilder.DropColumn(
                name: "contributor_id",
                table: "workers");

            migrationBuilder.DropColumn(
                name: "person_id",
                table: "workers");

            migrationBuilder.DropColumn(
                name: "instructivos_folder_id",
                table: "work_item_category");

            migrationBuilder.DropColumn(
                name: "instructivos_folder_name",
                table: "work_item_category");

            migrationBuilder.DropColumn(
                name: "instructivos_sync_status",
                table: "work_item_category");

            migrationBuilder.DropColumn(
                name: "instructivos_synced_at",
                table: "work_item_category");

            migrationBuilder.DropColumn(
                name: "check_in_hora",
                table: "ss_programacion_emos");

            migrationBuilder.DropColumn(
                name: "fecha_notificacion",
                table: "ss_programacion_emos");

            migrationBuilder.DropColumn(
                name: "motivo_rechazo",
                table: "ss_programacion_emos");

            migrationBuilder.DropColumn(
                name: "origen",
                table: "ss_programacion_emos");

            migrationBuilder.DropColumn(
                name: "password_hash",
                table: "ss_clinicas");

            migrationBuilder.DropColumn(
                name: "contract_modality_id",
                table: "project_sub_contractor");

            migrationBuilder.DropColumn(
                name: "guarantee_fund_days",
                table: "project_sub_contractor");

            migrationBuilder.DropColumn(
                name: "guarantee_fund_percentage",
                table: "project_sub_contractor");

            migrationBuilder.DropColumn(
                name: "project_sub_contractor_instructivo_id",
                table: "project_sub_contractor");

            migrationBuilder.DropColumn(
                name: "project_sub_contractor_non_conforming_output_id",
                table: "project_sub_contractor");

            migrationBuilder.DropColumn(
                name: "project_sub_contractor_tolerance_chart_id",
                table: "project_sub_contractor");

            migrationBuilder.DropColumn(
                name: "abbreviation",
                table: "project");

            migrationBuilder.DropColumn(
                name: "partida_id",
                table: "phase_stage_sub_stage_sub_specialty");

            migrationBuilder.DropColumn(
                name: "catalog_item_id",
                table: "lesson");

            migrationBuilder.DropColumn(
                name: "sub_area_id",
                table: "lesson");

            migrationBuilder.DropColumn(
                name: "contractor_person_type_id",
                table: "contractor_email");

            migrationBuilder.DropColumn(
                name: "activation_token",
                table: "contractor");

            migrationBuilder.DropColumn(
                name: "activation_token_expiry",
                table: "contractor");

            migrationBuilder.DropColumn(
                name: "logo_file_url",
                table: "contractor");

            migrationBuilder.DropColumn(
                name: "categoria_id",
                table: "ac_actividades");

            migrationBuilder.DropColumn(
                name: "especialidad_id",
                table: "ac_actividades");

            migrationBuilder.AddColumn<string>(
                name: "apellido_nombre",
                table: "workers",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "dni",
                table: "workers",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "ruc",
                table: "workers",
                type: "text",
                nullable: true);

            migrationBuilder.AlterColumn<int>(
                name: "worker_id",
                table: "ss_alertas_emo",
                type: "integer",
                nullable: false,
                defaultValue: 0,
                oldClrType: typeof(int),
                oldType: "integer",
                oldNullable: true);

            migrationBuilder.AlterColumn<int>(
                name: "emo_id",
                table: "ss_alertas_emo",
                type: "integer",
                nullable: false,
                defaultValue: 0,
                oldClrType: typeof(int),
                oldType: "integer",
                oldNullable: true);

            migrationBuilder.AddColumn<int>(
                name: "contract_id",
                table: "project_sub_contractor",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddForeignKey(
                name: "fk_ss_alertas_emo_worker_emos_emo_id",
                table: "ss_alertas_emo",
                column: "emo_id",
                principalTable: "worker_emos",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_ss_alertas_emo_workers_worker_id",
                table: "ss_alertas_emo",
                column: "worker_id",
                principalTable: "workers",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
