using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Abril_Backend.Migrations
{
    /// <inheritdoc />
    public partial class AddEvAsignacionSupervisor : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // RenameColumn idempotente: sub_area_id -> lesson_area_id
            migrationBuilder.Sql(@"DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='lesson' AND column_name='sub_area_id')
       AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='lesson' AND column_name='lesson_area_id') THEN
        ALTER TABLE lesson RENAME COLUMN sub_area_id TO lesson_area_id;
    END IF;
END $$");

            // AddColumn idempotentes
            migrationBuilder.Sql("ALTER TABLE project ADD COLUMN IF NOT EXISTS staff_email text");
            migrationBuilder.Sql("ALTER TABLE lesson ADD COLUMN IF NOT EXISTS catalog_item_id integer");

            // CreateTable idempotentes
            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS area_type (
    area_type_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_type_name text NOT NULL,
    active boolean NOT NULL,
    state boolean NOT NULL
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS catalog_type (
    catalog_type_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_type_name text NOT NULL,
    active boolean NOT NULL
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS ev_asignacion_supervisor (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supervisor_worker_id integer NOT NULL,
    project_id integer NOT NULL,
    activo boolean NOT NULL,
    created_at timestamptz NOT NULL
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS ev_periodo (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mes integer NOT NULL,
    anio integer NOT NULL,
    fecha_apertura date NOT NULL,
    fecha_cierre date NOT NULL,
    activo boolean NOT NULL,
    created_at timestamptz NOT NULL
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS ev_plantilla (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_nombre text NOT NULL,
    criterio text NOT NULL,
    orden integer NOT NULL,
    activo boolean NOT NULL,
    version integer NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz,
    updated_by integer
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS ev_recordatorio_log (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    periodo_id integer NOT NULL,
    user_id integer,
    tipo text NOT NULL,
    email_destino text,
    cc_jefatura boolean NOT NULL,
    cc_gerencia boolean NOT NULL,
    enviado_at timestamptz NOT NULL
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS lesson_area (
    lesson_area_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_scope_id integer NOT NULL,
    active boolean NOT NULL,
    created_at timestamptz NOT NULL
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS project_staff_reminder (
    project_staff_reminder_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id integer NOT NULL,
    active boolean NOT NULL,
    created_at timestamptz NOT NULL
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS scope_template (
    scope_template_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_name text NOT NULL,
    active boolean NOT NULL,
    created_date_time timestamptz NOT NULL,
    created_user_id integer,
    updated_date_time timestamptz,
    updated_user_id integer
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS area_item (
    area_item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_item_name text NOT NULL,
    area_type_id integer NOT NULL REFERENCES area_type(area_type_id) ON DELETE RESTRICT,
    active boolean NOT NULL,
    state boolean NOT NULL
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS catalog_item (
    catalog_item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_type_id integer NOT NULL REFERENCES catalog_type(catalog_type_id) ON DELETE CASCADE,
    catalog_item_description text NOT NULL,
    active boolean NOT NULL
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS ev_evaluacion_residente (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    periodo_id integer NOT NULL REFERENCES ev_periodo(id) ON DELETE CASCADE,
    evaluador_user_id integer,
    evaluador_person_id integer,
    evaluado_user_id integer NOT NULL,
    project_id integer REFERENCES project(project_id),
    area_nombre text NOT NULL,
    nota numeric,
    comentario text,
    no_aplica boolean NOT NULL,
    no_aplica_motivo text,
    created_at timestamptz NOT NULL,
    updated_at timestamptz
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS ev_no_aplica (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    periodo_id integer NOT NULL REFERENCES ev_periodo(id) ON DELETE CASCADE,
    evaluado_user_id integer NOT NULL,
    project_id integer,
    motivo text NOT NULL,
    registrado_por integer,
    created_at timestamptz NOT NULL
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS area_scope (
    area_scope_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_item_id integer NOT NULL REFERENCES area_item(area_item_id) ON DELETE RESTRICT,
    area_scope_parent_id integer REFERENCES area_scope(area_scope_id) ON DELETE RESTRICT,
    display_order integer NOT NULL,
    active boolean NOT NULL,
    state boolean NOT NULL
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS scope_item (
    scope_item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_area_id integer NOT NULL REFERENCES lesson_area(lesson_area_id) ON DELETE CASCADE,
    catalog_item_id integer NOT NULL REFERENCES catalog_item(catalog_item_id) ON DELETE CASCADE,
    scope_item_parent_id integer REFERENCES scope_item(scope_item_id) ON DELETE RESTRICT,
    display_order integer NOT NULL,
    active boolean NOT NULL
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS scope_template_item (
    scope_template_item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_template_id integer NOT NULL REFERENCES scope_template(scope_template_id) ON DELETE CASCADE,
    catalog_item_id integer NOT NULL REFERENCES catalog_item(catalog_item_id) ON DELETE CASCADE,
    scope_template_item_parent_id integer REFERENCES scope_template_item(scope_template_item_id) ON DELETE RESTRICT,
    display_order integer NOT NULL,
    active boolean NOT NULL
)");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS ev_evaluacion_residente_detalle (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluacion_id integer NOT NULL REFERENCES ev_evaluacion_residente(id) ON DELETE CASCADE,
    plantilla_id integer REFERENCES ev_plantilla(id),
    criterio text NOT NULL,
    puntaje integer,
    es_na boolean NOT NULL
)");

            // CreateIndex idempotentes (con manejo de excepciones)
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_area_item_area_type_id ON area_item(area_type_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_area_scope_area_item_id ON area_scope(area_item_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_area_scope_area_scope_parent_id ON area_scope(area_scope_parent_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_catalog_item_catalog_type_id ON catalog_item(catalog_type_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_ev_evaluacion_residente_periodo_id ON ev_evaluacion_residente(periodo_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_ev_evaluacion_residente_project_id ON ev_evaluacion_residente(project_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_ev_evaluacion_residente_detalle_evaluacion_id ON ev_evaluacion_residente_detalle(evaluacion_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_ev_evaluacion_residente_detalle_plantilla_id ON ev_evaluacion_residente_detalle(plantilla_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_ev_no_aplica_periodo_id ON ev_no_aplica(periodo_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_scope_item_catalog_item_id ON scope_item(catalog_item_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_scope_item_lesson_area_id ON scope_item(lesson_area_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_scope_item_scope_item_parent_id ON scope_item(scope_item_parent_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_scope_template_item_catalog_item_id ON scope_template_item(catalog_item_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_scope_template_item_scope_template_id ON scope_template_item(scope_template_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
            migrationBuilder.Sql(@"DO $$ BEGIN CREATE INDEX IF NOT EXISTS ix_scope_template_item_scope_template_item_parent_id ON scope_template_item(scope_template_item_parent_id); EXCEPTION WHEN OTHERS THEN NULL; END $$");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "area_scope");

            migrationBuilder.DropTable(
                name: "ev_asignacion_supervisor");

            migrationBuilder.DropTable(
                name: "ev_evaluacion_residente_detalle");

            migrationBuilder.DropTable(
                name: "ev_no_aplica");

            migrationBuilder.DropTable(
                name: "ev_recordatorio_log");

            migrationBuilder.DropTable(
                name: "project_staff_reminder");

            migrationBuilder.DropTable(
                name: "scope_item");

            migrationBuilder.DropTable(
                name: "scope_template_item");

            migrationBuilder.DropTable(
                name: "area_item");

            migrationBuilder.DropTable(
                name: "ev_evaluacion_residente");

            migrationBuilder.DropTable(
                name: "ev_plantilla");

            migrationBuilder.DropTable(
                name: "lesson_area");

            migrationBuilder.DropTable(
                name: "catalog_item");

            migrationBuilder.DropTable(
                name: "scope_template");

            migrationBuilder.DropTable(
                name: "area_type");

            migrationBuilder.DropTable(
                name: "ev_periodo");

            migrationBuilder.DropTable(
                name: "catalog_type");

            migrationBuilder.DropColumn(
                name: "staff_email",
                table: "project");

            migrationBuilder.DropColumn(
                name: "catalog_item_id",
                table: "lesson");

            migrationBuilder.RenameColumn(
                name: "lesson_area_id",
                table: "lesson",
                newName: "sub_area_id");
        }
    }
}
