using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Abril_Backend.Migrations
{
    /// <inheritdoc />
    public partial class AddControlSemanaLinea : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                -- invoice_folder: eliminar columna name huérfana (idempotente)
                ALTER TABLE invoice_folder DROP COLUMN IF EXISTS name;

                -- invoice: agregar signed_document_url (idempotente)
                ALTER TABLE invoice ADD COLUMN IF NOT EXISTS signed_document_url text;

                -- manager_signature: tabla singleton de firma del gerente (idempotente)
                CREATE TABLE IF NOT EXISTS manager_signature (
                    manager_signature_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    image_bytes          bytea NOT NULL,
                    mime                 text NOT NULL,
                    created_date_time    timestamp with time zone NOT NULL,
                    created_user_id      integer NOT NULL,
                    updated_date_time    timestamp with time zone,
                    updated_user_id      integer,
                    active               boolean NOT NULL,
                    state                boolean NOT NULL
                );

                -- ss_control_semana: corregir DEFAULT faltante en registrado_en
                -- CrearSemanaAsync (Dapper) no incluye registrado_en en el INSERT
                ALTER TABLE ss_control_semana ALTER COLUMN registrado_en SET DEFAULT NOW();

                -- ss_control_semana_linea: tabla principal faltante (idempotente)
                CREATE TABLE IF NOT EXISTS ss_control_semana_linea (
                    id              integer GENERATED BY DEFAULT AS IDENTITY,
                    control_id      integer NOT NULL,
                    familia_id      integer NOT NULL,
                    cantidad_real   numeric NOT NULL,
                    precio_unitario numeric,
                    total_real      numeric GENERATED ALWAYS AS (cantidad_real * COALESCE(precio_unitario, 0)) STORED,
                    notas           text,
                    CONSTRAINT pk_ss_control_semana_linea PRIMARY KEY (id),
                    CONSTRAINT fk_ss_control_semana_linea_control_id
                        FOREIGN KEY (control_id) REFERENCES ss_control_semana (id) ON DELETE CASCADE,
                    CONSTRAINT fk_ss_control_semana_linea_familia_id
                        FOREIGN KEY (familia_id) REFERENCES ss_material_familia (id)
                );
                CREATE INDEX IF NOT EXISTS ix_ss_control_semana_linea_control_id  ON ss_control_semana_linea (control_id);
                CREATE INDEX IF NOT EXISTS ix_ss_control_semana_linea_familia_id  ON ss_control_semana_linea (familia_id);
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS ss_control_semana_linea;
                DROP TABLE IF EXISTS manager_signature;
                ALTER TABLE invoice DROP COLUMN IF EXISTS signed_document_url;
                ALTER TABLE ss_control_semana ALTER COLUMN registrado_en DROP DEFAULT;
                """);
        }
    }
}
