using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Abril_Backend.Migrations
{
    /// <inheritdoc />
    public partial class AddAmonestaciones : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Agregar columna a workers solo si no existe
            migrationBuilder.Sql("""
                DO $$ BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                                   WHERE table_name='workers' AND column_name='apellido_nombre') THEN
                        ALTER TABLE workers ADD COLUMN apellido_nombre text;
                    END IF;
                END $$;
                """);

            // holiday_type y holiday — pueden ya existir en dev
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS holiday_type (
                    holiday_type_id integer GENERATED BY DEFAULT AS IDENTITY,
                    holiday_type_name text NOT NULL,
                    active boolean NOT NULL,
                    state boolean NOT NULL,
                    CONSTRAINT pk_holiday_type PRIMARY KEY (holiday_type_id)
                );
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS holiday (
                    holiday_id integer GENERATED BY DEFAULT AS IDENTITY,
                    holiday_type_id integer NOT NULL,
                    holiday_date date NOT NULL,
                    description text NOT NULL,
                    recurring_yearly boolean NOT NULL,
                    created_date_time timestamptz NOT NULL,
                    updated_date_time timestamptz,
                    active boolean NOT NULL,
                    state boolean NOT NULL,
                    CONSTRAINT pk_holiday PRIMARY KEY (holiday_id),
                    CONSTRAINT fk_holiday_holiday_type_holiday_type_id
                        FOREIGN KEY (holiday_type_id) REFERENCES holiday_type (holiday_type_id)
                        ON DELETE RESTRICT
                );
                CREATE INDEX IF NOT EXISTS ix_holiday_holiday_type_id ON holiday (holiday_type_id);
                """);

            // ssoma_auditoria_ats — puede ya existir
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS ssoma_auditoria_ats (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    fecha date NOT NULL,
                    auditor_worker_id integer NOT NULL,
                    auditado_worker_id integer NOT NULL,
                    proyecto_id integer,
                    email_auditado text,
                    actividad text,
                    lugar text,
                    puntaje_promedio numeric,
                    nivel text,
                    observaciones text,
                    estado text NOT NULL,
                    created_at timestamptz NOT NULL,
                    updated_at timestamptz NOT NULL,
                    CONSTRAINT pk_ssoma_auditoria_ats PRIMARY KEY (id)
                );
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS ssoma_auditoria_ats_pregunta (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    orden smallint NOT NULL,
                    texto text NOT NULL,
                    activo boolean NOT NULL,
                    created_at timestamptz NOT NULL,
                    CONSTRAINT pk_ssoma_auditoria_ats_pregunta PRIMARY KEY (id)
                );
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS ssoma_auditoria_ats_foto (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    auditoria_id integer NOT NULL,
                    foto_base64 text NOT NULL,
                    orden smallint NOT NULL,
                    CONSTRAINT pk_ssoma_auditoria_ats_foto PRIMARY KEY (id),
                    CONSTRAINT fk_ssoma_auditoria_ats_foto_ssoma_auditoria_ats_auditoria_id
                        FOREIGN KEY (auditoria_id) REFERENCES ssoma_auditoria_ats (id)
                        ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS ix_ssoma_auditoria_ats_foto_auditoria_id ON ssoma_auditoria_ats_foto (auditoria_id);
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS ssoma_auditoria_ats_respuesta (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    auditoria_id integer NOT NULL,
                    pregunta_id integer NOT NULL,
                    puntaje smallint NOT NULL,
                    comentario text,
                    CONSTRAINT pk_ssoma_auditoria_ats_respuesta PRIMARY KEY (id),
                    CONSTRAINT fk_ssoma_auditoria_ats_respuesta_ssoma_auditoria_ats_auditoria
                        FOREIGN KEY (auditoria_id) REFERENCES ssoma_auditoria_ats (id)
                        ON DELETE CASCADE,
                    CONSTRAINT fk_ssoma_auditoria_ats_respuesta_ssoma_auditoria_ats_pregunta_
                        FOREIGN KEY (pregunta_id) REFERENCES ssoma_auditoria_ats_pregunta (id)
                        ON DELETE CASCADE
                );
                CREATE UNIQUE INDEX IF NOT EXISTS ix_ssoma_auditoria_ats_respuesta_auditoria_id_pregunta_id
                    ON ssoma_auditoria_ats_respuesta (auditoria_id, pregunta_id);
                CREATE INDEX IF NOT EXISTS ix_ssoma_auditoria_ats_respuesta_pregunta_id
                    ON ssoma_auditoria_ats_respuesta (pregunta_id);
                """);

            // ── NUEVAS tablas de Amonestaciones ──

            migrationBuilder.CreateTable(
                name: "ssoma_amonestacion_infraccion_tipos",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    nombre = table.Column<string>(type: "text", nullable: false),
                    state = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_ssoma_amonestacion_infraccion_tipos", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "ssoma_amonestacion_tipo_sanciones",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    nombre = table.Column<string>(type: "text", nullable: false),
                    nivel_gravedad = table.Column<string>(type: "text", nullable: false),
                    genera_suspension = table.Column<bool>(type: "boolean", nullable: false),
                    state = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_ssoma_amonestacion_tipo_sanciones", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "ssoma_amonestaciones",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    codigo = table.Column<string>(type: "text", nullable: false),
                    proyecto_id = table.Column<int>(type: "integer", nullable: false),
                    fecha = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    worker_id = table.Column<int>(type: "integer", nullable: false),
                    partida_id = table.Column<int>(type: "integer", nullable: true),
                    tipo_sancion_id = table.Column<int>(type: "integer", nullable: false),
                    infraccion_tipo_id = table.Column<int>(type: "integer", nullable: false),
                    descripcion = table.Column<string>(type: "text", nullable: false),
                    aplica_penalizacion = table.Column<bool>(type: "boolean", nullable: false),
                    sancion_infraccion_id = table.Column<int>(type: "integer", nullable: true),
                    monto_calculado = table.Column<decimal>(type: "numeric", nullable: false),
                    uit_referencia = table.Column<decimal>(type: "numeric", nullable: false),
                    puntos_infraccion = table.Column<int>(type: "integer", nullable: false),
                    dias_suspension = table.Column<int>(type: "integer", nullable: true),
                    fecha_inicio_suspension = table.Column<DateOnly>(type: "date", nullable: true),
                    fecha_fin_suspension = table.Column<DateOnly>(type: "date", nullable: true),
                    persona_reporta_id = table.Column<int>(type: "integer", nullable: true),
                    pdf_url = table.Column<string>(type: "text", nullable: true),
                    created_by = table.Column<int>(type: "integer", nullable: true),
                    created_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    state = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_ssoma_amonestaciones", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "ssoma_amonestacion_fotos",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    amonestacion_id = table.Column<int>(type: "integer", nullable: false),
                    url = table.Column<string>(type: "text", nullable: false),
                    sp_id = table.Column<string>(type: "text", nullable: true),
                    nombre_archivo = table.Column<string>(type: "text", nullable: true),
                    orden = table.Column<int>(type: "integer", nullable: false),
                    created_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_ssoma_amonestacion_fotos", x => x.id);
                    table.ForeignKey(
                        name: "fk_ssoma_amonestacion_fotos_ssoma_amonestaciones_amonestacion_",
                        column: x => x.amonestacion_id,
                        principalTable: "ssoma_amonestaciones",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_ssoma_amonestacion_fotos_amonestacion_id",
                table: "ssoma_amonestacion_fotos",
                column: "amonestacion_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "ssoma_amonestacion_fotos");
            migrationBuilder.DropTable(name: "ssoma_amonestacion_infraccion_tipos");
            migrationBuilder.DropTable(name: "ssoma_amonestacion_tipo_sanciones");
            migrationBuilder.DropTable(name: "ssoma_amonestaciones");

            migrationBuilder.Sql("ALTER TABLE workers DROP COLUMN IF EXISTS apellido_nombre;");
        }
    }
}
