namespace Abril_Backend.Features.SsomaModule.DesempenoSupervisorFeature.Application.Dtos;

public record DesempenoSupervisorDto(
    int SupervisorId,
    string SupervisorNombre,
    int ProyectoId,
    string ProyectoNombre,
    int Mes,
    int Anio,
    int MetaRacs,
    int MetaOpt,
    int MetaInspecciones,
    int MetaCharlas,
    int MetaLeccion,
    int MetaEvalContratista,
    int MetaEvalResidente,
    int ActualRacs,
    int ActualOpt,
    int ActualInspecciones,
    int ActualCharlas,
    int ActualLeccion,
    int ActualEvalContratista,
    int ActualEvalResidente,
    decimal PctRacs,
    decimal PctOpt,
    decimal PctInspecciones,
    decimal PctCharlas,
    decimal PctLeccion,
    decimal PctEvalContratista,
    decimal PctEvalResidente,
    decimal PctGeneral,
    DateTime? FechaLogro100,
    bool EsPrimeroEnProyecto,
    decimal? PctGeneralMesAnterior,
    bool EsResidente,
    bool EsOculto = false,
    bool PuedeOcultarse = false
);
