-- ═══════════════════════════════════════════════════════════════════════════
-- workers.estado normalizado + el finalista aprobado entra a workers
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Contexto: al aprobar a un finalista, Reclutamiento ya no cierra el proceso.
-- GTH tiene que programarle el EMO de Ingreso desde SSOMA · Salud Ocupacional,
-- y para eso la persona necesita una ficha en `workers` (worker_emos y
-- ss_programacion_emos apuntan a workers.id). Pero todavia NO es trabajador:
-- puede rechazar la carta oferta o el contrato.
--
-- La ficha se distingue por su estado, y el aislamiento real lo da la AUSENCIA
-- de fila en worker_vinculaciones: la vinculacion es el contrato, y las
-- consultas de EMOs, auto-programacion, habilitacion y dashboards ya exigen
-- vinculacion vigente con empresa Abril, asi que un finalista no aparece en
-- ninguna de ellas sin tocar una sola de esas queries.
--
-- Que agrega:
--   1) workers_estado — catalogo de los 5 estados. REINGRESO no entra: nunca
--      fue un estado de workers, es un tipo de evento de worker_eventos
--      (WorkerTipoEvento.Reingreso) y HabTrabajadorRepository.ReingresoAsync
--      deja al trabajador en ACTIVO. En dev no hay ni una fila con ese valor.
--   2) workers.workers_estado_id — la FK, poblada desde el texto actual.
--   3) Trigger de sincronizacion workers.estado <-> workers_estado_id. Es una
--      AYUDA DE MIGRACION con fecha de caducidad: mientras exista la columna
--      `estado` (texto) el SQL crudo de Dapper que todavia la lea sigue viendo
--      el dato fresco, y una escritura legacy que solo toque el texto no deja
--      la FK desincronizada. Se borra junto con la columna en el deploy
--      siguiente (ver "PENDIENTE" al final).
--   4) gth_estado_requerimiento EMO_INGRESO — la fase nueva entre "Seleccion
--      jefatura" y "Cerrado". Aprobar al finalista ya no cierra: deja el
--      requerimiento aca hasta que GTH programe el EMO de ingreso.
--
-- Idempotente: se puede correr mas de una vez sin duplicar nada.
-- ═══════════════════════════════════════════════════════════════════════════

BEGIN;

-- ───────────────────────────────────────────────────────────────────────────
-- 1) Catalogo de estados de la ficha de trabajador
-- ───────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS workers_estado (
    workers_estado_id integer                  GENERATED BY DEFAULT AS IDENTITY,
    codigo            text                     NOT NULL,
    nombre            text                     NOT NULL,
    orden             integer                  NOT NULL DEFAULT 0,
    -- Hecho ya consumado, no condicion actual: una vez true no vuelve a false.
    -- Un RETIRADO tiene true (si llego a ingresar, y despues salio); un
    -- FINALISTA_APROBADO tiene false (todavia no) y un NO_INGRESO tambien
    -- (nunca llego). Sin DEFAULT a proposito: agregar un estado nuevo obliga a
    -- decidir el valor en vez de heredar en silencio el true, que es la
    -- direccion que filtraria fichas de pre-ingreso al resto del sistema.
    llego_a_ingresar  boolean                  NOT NULL,
    created_date_time timestamp with time zone NOT NULL DEFAULT now(),
    created_user_id   integer,
    updated_date_time timestamp with time zone,
    updated_user_id   integer,
    active            boolean                  NOT NULL DEFAULT true,
    state             boolean                  NOT NULL DEFAULT true,
    CONSTRAINT pk_workers_estado PRIMARY KEY (workers_estado_id)
);

-- Un solo registro vigente por codigo (multiples con state = false).
CREATE UNIQUE INDEX IF NOT EXISTS ux_workers_estado_codigo_vigente
    ON workers_estado (codigo)
    WHERE state;

-- Con id explicito a proposito: al ser identicos en dev y prod se pueden usar
-- como constantes en el codigo (Shared/Constants/WorkersEstadoIds.cs), igual
-- que workers_obra_oficina_staff. Un catalogo sembrado a mano con ids
-- autogenerados termina con ids distintos por ambiente y obliga a resolver
-- por texto en cada consulta.
INSERT INTO workers_estado (workers_estado_id, codigo, nombre, orden, llego_a_ingresar) VALUES
    (1, 'ACTIVO',             'Activo',                 1, true),
    (2, 'RETIRADO',           'Retirado',               2, true),
    (3, 'INHABILITADO_SSOMA', 'Inhabilitado por SSOMA', 3, true),
    (4, 'FINALISTA_APROBADO', 'Finalista aprobado',     4, false),
    (5, 'NO_INGRESO',         'No ingreso',             5, false)
ON CONFLICT (codigo) WHERE state DO NOTHING;

-- La secuencia queda por encima de los ids sembrados a mano, para que un
-- INSERT futuro sin id explicito no choque contra ellos.
SELECT setval(
    pg_get_serial_sequence('workers_estado', 'workers_estado_id'),
    GREATEST((SELECT max(workers_estado_id) FROM workers_estado), 1)
);

-- ───────────────────────────────────────────────────────────────────────────
-- 2) workers.workers_estado_id
-- ───────────────────────────────────────────────────────────────────────────
ALTER TABLE workers ADD COLUMN IF NOT EXISTS workers_estado_id integer;

-- Backfill desde el texto. upper()+btrim() absorbe la basura historica de
-- mayusculas ('Activo' vs 'ACTIVO', que ya rompia en silencio a
-- MicrosoftLoginRepository); NULL/vacio se toma como ACTIVO, igual que el
-- DEFAULT de la columna vieja y que el coalesce() de WorkerSearchRepository.
UPDATE workers w
SET    workers_estado_id = e.workers_estado_id
FROM   workers_estado e
WHERE  e.state
  AND  e.codigo = CASE upper(coalesce(nullif(btrim(w.estado), ''), 'ACTIVO'))
                    -- Por si prod tuviera alguna: era tipo de evento, no estado,
                    -- y el reingreso siempre termina dejando al worker ACTIVO.
                    WHEN 'REINGRESO' THEN 'ACTIVO'
                    ELSE upper(coalesce(nullif(btrim(w.estado), ''), 'ACTIVO'))
                  END
  AND  w.workers_estado_id IS DISTINCT FROM e.workers_estado_id;

-- Freno: si prod tuviera un valor de estado que no esta en el catalogo, el
-- script aborta en vez de dejar filas a medio migrar y una FK NOT NULL rota.
DO $$
DECLARE v_faltan integer; v_valores text;
BEGIN
    SELECT count(*) INTO v_faltan FROM workers WHERE workers_estado_id IS NULL;
    IF v_faltan > 0 THEN
        SELECT string_agg(DISTINCT coalesce(estado, '(null)'), ', ')
          INTO v_valores
          FROM workers WHERE workers_estado_id IS NULL;
        RAISE EXCEPTION
            'Quedaron % filas de workers sin workers_estado_id. Valores de estado sin equivalencia en workers_estado: %',
            v_faltan, v_valores;
    END IF;
END $$;

ALTER TABLE workers ALTER COLUMN workers_estado_id SET NOT NULL;

ALTER TABLE workers DROP CONSTRAINT IF EXISTS fk_workers_estado;
ALTER TABLE workers
    ADD CONSTRAINT fk_workers_estado
    FOREIGN KEY (workers_estado_id) REFERENCES workers_estado (workers_estado_id);

CREATE INDEX IF NOT EXISTS ix_workers_workers_estado_id
    ON workers (workers_estado_id);

-- ───────────────────────────────────────────────────────────────────────────
-- 3) Sincronizacion workers.estado <-> workers_estado_id  (AYUDA DE MIGRACION)
-- ───────────────────────────────────────────────────────────────────────────
-- El CHECK viejo ya no puede quedarse: no conoce FINALISTA_APROBADO ni
-- NO_INGRESO y rechazaria los INSERT nuevos. Quien valida ahora es la FK.
ALTER TABLE workers DROP CONSTRAINT IF EXISTS workers_estado_check;

-- El indice unico del correo corporativo lee el texto `estado`. Como el
-- trigger lo mantiene fresco, sigue funcionando tal cual durante la
-- transicion; se rehace contra la FK en el deploy que borre la columna.

CREATE OR REPLACE FUNCTION workers_estado_sync() RETURNS trigger AS $$
DECLARE v_codigo text; v_id integer;
BEGIN
    -- Escritura legacy: alguien actualizo solo el texto (SQL crudo o un
    -- call site que se nos paso). Se deriva la FK para que no quede vieja.
    IF TG_OP = 'UPDATE'
       AND NEW.workers_estado_id IS NOT DISTINCT FROM OLD.workers_estado_id
       AND NEW.estado            IS DISTINCT FROM OLD.estado
    THEN
        SELECT e.workers_estado_id INTO v_id
          FROM workers_estado e
         WHERE e.state AND e.codigo = upper(btrim(coalesce(NEW.estado, '')));
        IF v_id IS NOT NULL THEN
            NEW.workers_estado_id := v_id;
        END IF;
    END IF;

    -- La FK es la fuente de verdad: el texto siempre se reescribe desde ella.
    SELECT e.codigo INTO v_codigo
      FROM workers_estado e
     WHERE e.workers_estado_id = NEW.workers_estado_id;
    NEW.estado := v_codigo;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_workers_estado_sync ON workers;
CREATE TRIGGER trg_workers_estado_sync
    BEFORE INSERT OR UPDATE ON workers
    FOR EACH ROW EXECUTE FUNCTION workers_estado_sync();

-- ───────────────────────────────────────────────────────────────────────────
-- 4) Reclutamiento: fase EMO_INGRESO antes de CERRADO
-- ───────────────────────────────────────────────────────────────────────────
-- El pipeline visible del seguimiento se arma con los estados active = true
-- ordenados por `orden`, asi que la fase nueva se intercala corriendo la cola.
-- Ningun comparador de `orden` del repositorio mira estos valores altos: los
-- umbrales son PUBLICACION (4), LONG_LIST (5), LONG_LIST_ENVIADA (6),
-- LONG_LIST_APROBADA (7) y ENTREVISTAS (8).
UPDATE gth_estado_requerimiento SET orden = 12, updated_date_time = now()
 WHERE codigo IN ('OFERTA_CIERRE', 'RECHAZADO_GG') AND state AND orden <> 12;

UPDATE gth_estado_requerimiento SET orden = 11, updated_date_time = now()
 WHERE codigo = 'CERRADO' AND state AND orden <> 11;

INSERT INTO gth_estado_requerimiento (codigo, nombre, descripcion, orden, active, state) VALUES
    ('EMO_INGRESO',
     'EMO de ingreso',
     'GTH le programa el examen medico de ingreso al finalista aprobado antes de cerrar el proceso.',
     10, true, true)
ON CONFLICT (codigo) WHERE state DO NOTHING;

COMMIT;

-- ═══════════════════════════════════════════════════════════════════════════
-- PENDIENTE para el deploy SIGUIENTE (no correr ahora)
-- ═══════════════════════════════════════════════════════════════════════════
-- Una vez que este release lleve un tiempo arriba y se confirme que ningun
-- SQL crudo lee `workers.estado` (grepear la columna antes: el build no ve el
-- SQL de Dapper), soltar la ayuda de migracion:
--
--   BEGIN;
--   DROP TRIGGER IF EXISTS trg_workers_estado_sync ON workers;
--   DROP FUNCTION IF EXISTS workers_estado_sync();
--   -- El indice del correo corporativo se rehace contra la FK:
--   DROP INDEX IF EXISTS ux_workers_email_corporativo_vigente;
--   CREATE UNIQUE INDEX ux_workers_email_corporativo_vigente
--       ON workers (lower(btrim(email_corporativo)))
--       WHERE email_corporativo IS NOT NULL
--         AND btrim(email_corporativo) <> ''
--         AND workers_estado_id <> (SELECT workers_estado_id FROM workers_estado
--                                    WHERE codigo = 'RETIRADO' AND state)
--         AND (lower(btrim(email_corporativo)) LIKE '%@abril.pe'
--              OR (contrata_casa = 'Casa' AND obra_oficina_staff_id = ANY (ARRAY[2, 3])));
--   ALTER TABLE workers DROP COLUMN estado;
--   COMMIT;
--
-- (El indice nuevo necesita el id literal de RETIRADO, no un subselect, porque
--  los indices exigen expresiones IMMUTABLE — resolverlo al escribir el script.)
-- ═══════════════════════════════════════════════════════════════════════════
