-- ═══════════════════════════════════════════════════════════════════════════
-- Reclutamiento · archivos del informe de la entrevista (por candidato)
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Al enviar a un candidato como finalista, GTH puede adjuntar dos documentos:
-- el informe final y los resultados de la evaluación de conocimientos. Los dos
-- son OPCIONALES. Viajan adjuntos en el correo al solicitante y quedan
-- visibles en su pantalla (Solicitud de Personal → Finalistas).
--
-- Qué agrega:
--   1) gth_evaluacion_archivo_tipo — catálogo de los dos documentos. Es un
--      catálogo y no dos pares de columnas sueltas por la regla de la base:
--      los tipos viven en su propia tabla y se apuntan por FK. Sumar un tercer
--      documento mañana es un INSERT, no un ALTER TABLE.
--   2) gth_candidato_evaluacion_archivo — el archivo subido a SharePoint,
--      colgado de la evaluación del candidato (no del requerimiento): cada
--      vuelta de long list tiene sus propias evaluaciones y sus archivos se van
--      con ellas.
--
-- Un solo archivo vivo por evaluación y tipo: volver a subir el informe final
-- reemplaza al anterior (el viejo queda con state = false, nunca se borra).
--
-- Idempotente: se puede correr más de una vez sin duplicar nada.
-- ═══════════════════════════════════════════════════════════════════════════

BEGIN;

SET client_encoding TO 'UTF8';

-- 1) Catálogo de los documentos del informe.
CREATE TABLE IF NOT EXISTS gth_evaluacion_archivo_tipo (
    gth_evaluacion_archivo_tipo_id integer GENERATED BY DEFAULT AS IDENTITY,
    codigo                         text                     NOT NULL,
    nombre                         text                     NOT NULL,
    orden                          integer                  NOT NULL DEFAULT 0,
    created_date_time              timestamp with time zone NOT NULL DEFAULT now(),
    created_user_id                integer,
    updated_date_time              timestamp with time zone,
    updated_user_id                integer,
    active                         boolean                  NOT NULL DEFAULT true,
    state                          boolean                  NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_evaluacion_archivo_tipo PRIMARY KEY (gth_evaluacion_archivo_tipo_id)
);

-- Un solo registro vivo por código (los de baja quedan con state = false).
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_evaluacion_archivo_tipo_codigo_vivo
    ON gth_evaluacion_archivo_tipo (codigo) WHERE state = true;

INSERT INTO gth_evaluacion_archivo_tipo (codigo, nombre, orden)
SELECT v.codigo, v.nombre, v.orden
FROM (VALUES
    ('INFORME_FINAL',            'Informe final',                           1),
    ('EVALUACION_CONOCIMIENTOS', 'Resultados de evaluación de conocimientos', 2)
) AS v(codigo, nombre, orden)
WHERE NOT EXISTS (
    SELECT 1 FROM gth_evaluacion_archivo_tipo t WHERE t.codigo = v.codigo AND t.state = true
);

-- 2) El archivo en sí (mismas columnas de SharePoint que gth_candidato_anexo).
CREATE TABLE IF NOT EXISTS gth_candidato_evaluacion_archivo (
    gth_candidato_evaluacion_archivo_id integer GENERATED BY DEFAULT AS IDENTITY,
    gth_candidato_evaluacion_id         integer                  NOT NULL,
    gth_evaluacion_archivo_tipo_id      integer                  NOT NULL,
    nombre                              text                     NOT NULL,
    nombre_original                     text,
    url                                 text,
    item_id                             text,
    drive_id                            text,
    created_date_time                   timestamp with time zone NOT NULL DEFAULT now(),
    created_user_id                     integer,
    updated_date_time                   timestamp with time zone,
    updated_user_id                     integer,
    active                              boolean                  NOT NULL DEFAULT true,
    state                               boolean                  NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_candidato_evaluacion_archivo PRIMARY KEY (gth_candidato_evaluacion_archivo_id)
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_gth_candidato_evaluacion_archivo_evaluacion'
    ) THEN
        ALTER TABLE gth_candidato_evaluacion_archivo
            ADD CONSTRAINT fk_gth_candidato_evaluacion_archivo_evaluacion
            FOREIGN KEY (gth_candidato_evaluacion_id)
            REFERENCES gth_candidato_evaluacion (gth_candidato_evaluacion_id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_gth_candidato_evaluacion_archivo_tipo'
    ) THEN
        ALTER TABLE gth_candidato_evaluacion_archivo
            ADD CONSTRAINT fk_gth_candidato_evaluacion_archivo_tipo
            FOREIGN KEY (gth_evaluacion_archivo_tipo_id)
            REFERENCES gth_evaluacion_archivo_tipo (gth_evaluacion_archivo_tipo_id);
    END IF;
END $$;

-- Un archivo vivo por evaluación y tipo: volver a subirlo reemplaza al anterior.
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_candidato_evaluacion_archivo_vivo
    ON gth_candidato_evaluacion_archivo (gth_candidato_evaluacion_id, gth_evaluacion_archivo_tipo_id)
    WHERE state = true;

COMMIT;

-- Verificación
-- SELECT codigo, nombre, orden FROM gth_evaluacion_archivo_tipo WHERE state ORDER BY orden;
-- SELECT column_name FROM information_schema.columns
-- WHERE table_name = 'gth_candidato_evaluacion_archivo' ORDER BY ordinal_position;
