-- ═══════════════════════════════════════════════════════════════════════════
-- Reclutamiento · el candidato confirma o rechaza la entrevista desde el correo
-- ═══════════════════════════════════════════════════════════════════════════
--
-- La invitación a entrevista pasa a llevar dos botones (Confirmar / Rechazar).
-- El candidato responde desde el correo, sin login, y GTH recibe un aviso con
-- su respuesta; el estado queda visible en el modal del requerimiento.
--
-- Qué agrega:
--   1) gth_entrevista_respuesta — catálogo CONFIRMADA / RECHAZADA. Es un
--      catálogo y no un texto suelto en gth_entrevista por la regla de la base:
--      los estados y tipos viven en su propia tabla y se apuntan por FK.
--   2) gth_entrevista.token — acceso público a la respuesta (mismo mecanismo
--      que el token del formulario del postulante). Se regenera en cada envío:
--      al reprogramar, los botones del correo viejo dejan de responder por una
--      cita que ya cambió de fecha.
--   3) gth_entrevista.gth_entrevista_respuesta_id + respuesta_date_time — qué
--      respondió y cuándo. NULL = todavía no responde.
--   4) gth_correo_tipo ENTREVISTA_RESPUESTA — el aviso a GTH, administrable
--      desde Reclutamiento → Configuración como los otros diez correos. Va con
--      principal_automatico = true: el destinatario principal es SIEMPRE el
--      área de GTH (area_scope.email del nodo 58), que lo pone el backend al
--      enviar; acá solo se agregan principales adicionales y copias.
--
-- El token queda NULL en las entrevistas ya programadas antes de este script:
-- esas invitaciones se enviaron sin botones y no hay nada que responder. La
-- próxima vez que GTH reprograme y reenvíe, la fila recibe su token.
--
-- Idempotente: se puede correr más de una vez sin duplicar nada.
-- ═══════════════════════════════════════════════════════════════════════════

BEGIN;

-- 1) Catálogo de la respuesta del candidato.
CREATE TABLE IF NOT EXISTS gth_entrevista_respuesta (
    gth_entrevista_respuesta_id integer GENERATED BY DEFAULT AS IDENTITY,
    codigo                      text                     NOT NULL,
    nombre                      text                     NOT NULL,
    orden                       integer                  NOT NULL DEFAULT 0,
    created_date_time           timestamp with time zone NOT NULL DEFAULT now(),
    created_user_id             integer,
    updated_date_time           timestamp with time zone,
    updated_user_id             integer,
    active                      boolean                  NOT NULL DEFAULT true,
    state                       boolean                  NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_entrevista_respuesta PRIMARY KEY (gth_entrevista_respuesta_id)
);

-- Un solo registro vivo por código (los de baja quedan con state = false).
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_entrevista_respuesta_codigo_vivo
    ON gth_entrevista_respuesta (codigo) WHERE state = true;

INSERT INTO gth_entrevista_respuesta (codigo, nombre, orden)
SELECT v.codigo, v.nombre, v.orden
FROM (VALUES
    ('CONFIRMADA', 'Confirmada por el candidato', 1),
    ('RECHAZADA',  'Rechazada por el candidato',  2)
) AS v(codigo, nombre, orden)
WHERE NOT EXISTS (
    SELECT 1 FROM gth_entrevista_respuesta r WHERE r.codigo = v.codigo AND r.state = true
);

-- 2 y 3) Columnas de la respuesta en la entrevista.
ALTER TABLE gth_entrevista
    ADD COLUMN IF NOT EXISTS token                       text,
    ADD COLUMN IF NOT EXISTS gth_entrevista_respuesta_id integer,
    ADD COLUMN IF NOT EXISTS respuesta_date_time         timestamp with time zone;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_gth_entrevista_respuesta'
    ) THEN
        ALTER TABLE gth_entrevista
            ADD CONSTRAINT fk_gth_entrevista_respuesta
            FOREIGN KEY (gth_entrevista_respuesta_id)
            REFERENCES gth_entrevista_respuesta (gth_entrevista_respuesta_id);
    END IF;
END $$;

-- El token identifica la entrevista en el enlace público: único entre las vivas.
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_entrevista_token_vivo
    ON gth_entrevista (token) WHERE state = true AND token IS NOT NULL;

-- 4) El aviso a GTH, en la pantalla de Configuración. Va después de la
--    invitación a entrevista (9) y antes de la decisión de finalista.
UPDATE gth_correo_tipo SET orden = 11 WHERE codigo = 'FINALISTA_DECISION' AND state = true AND orden <> 11;
UPDATE gth_correo_tipo SET orden = 12 WHERE codigo = 'AGRADECIMIENTO'     AND state = true AND orden <> 12;

INSERT INTO gth_correo_tipo (codigo, nombre, descripcion, principal_automatico, orden, active, state, created_date_time)
SELECT 'ENTREVISTA_RESPUESTA',
       'Respuesta del candidato a la entrevista',
       'Se envía a GTH cuando el candidato confirma o rechaza su entrevista desde los botones del correo de invitación. El destinatario principal es SIEMPRE el área de Gestión del Talento Humano (el correo configurado en el árbol de áreas); acá solo se definen principales adicionales y copias.',
       true, 10, true, true, now()
WHERE NOT EXISTS (
    SELECT 1 FROM gth_correo_tipo t WHERE t.codigo = 'ENTREVISTA_RESPUESTA' AND t.state = true
);

COMMIT;

-- Verificación
-- SELECT codigo, nombre, orden, principal_automatico, active FROM gth_correo_tipo WHERE state ORDER BY orden;
-- SELECT codigo, nombre, orden FROM gth_entrevista_respuesta WHERE state ORDER BY orden;
-- SELECT column_name FROM information_schema.columns WHERE table_name = 'gth_entrevista' ORDER BY ordinal_position;
