-- ============================================================================
-- Gestión GTH · Reclutamiento — Aprobación de Gerencia General
--
-- Nuevo primer paso del flujo de "Solicitud de personal": antes de que GTH vea
-- nada, la solicitud completa (1..10 vacantes) se le manda al Gerente General en
-- UN SOLO correo con tres acciones (aprobar todas / elegir algunas / rechazar
-- todas). El correo lleva un enlace con token a una página pública (sin login)
-- donde el GG confirma su decisión. Solo las vacantes APROBADAS generan el correo
-- y la notificación a GTH (antes se enviaban al crear la solicitud).
--
--   Catálogo:
--     • gth_aprobacion_gg_estado  : PENDIENTE / APROBADA / APROBADA_PARCIAL / RECHAZADA
--   Tablas:
--     • gth_aprobacion_gg         : 1:1 con gth_solicitud; token de acceso público,
--                                    snapshot de los correos a los que se envió y
--                                    la decisión (cuándo y con qué comentario).
--     • gth_aprobacion_gg_detalle : decisión por vacante (aprobado true/false;
--                                    null = todavía sin decidir). Es el registro
--                                    de auditoría de lo que decidió el GG, aparte
--                                    del estado que el requerimiento vaya tomando.
--   Catálogos existentes que se amplían:
--     • gth_estado_requerimiento  : + RECHAZADO_GG (estado terminal). Se siembra con
--                                    active = false a propósito: es un estado válido
--                                    del requerimiento, pero NO una fase del pipeline,
--                                    así que no debe aparecer en la línea de tiempo del
--                                    seguimiento (esa consulta filtra por active).
--     • gth_correo_tipo           : + APROBACION_GG (destinatarios Para/CC del correo
--                                    al Gerente General, configurables desde la UI).
--                                    Se reordena el catálogo en orden cronológico del
--                                    flujo (orden no es llave, solo ordena consultas).
--     • notificacion_tipo         : + GTH_APROBACION_GG (campanita, para los
--                                    destinatarios del correo del GG que sí sean
--                                    usuarios del sistema).
--
-- ⚠️ Tras correr este script hay que configurar los destinatarios del nuevo correo
--    desde la UI (Solicitud de Personal → Configuración → pestaña "Aprobación GG").
--    Sin un destinatario principal la solicitud se registra pero queda en
--    "Aprobación Gerencia General" sin correo enviado (el solicitante lo puede
--    reintentar con el botón "Reenviar a Gerencia General").
--
-- Los requerimientos que ya existían se quedan como están (en NUEVO o más
-- adelante): el nuevo paso solo aplica a las solicitudes que se registren desde
-- ahora. Por eso los contadores siguen contando NUEVO además de los estados nuevos.
--
-- Idempotente: se puede correr múltiples veces sin duplicar ni romper nada.
-- ============================================================================

BEGIN;

-- ============================================================================
-- 1) Catálogo del estado de la aprobación
-- ============================================================================
CREATE TABLE IF NOT EXISTS gth_aprobacion_gg_estado (
    gth_aprobacion_gg_estado_id integer GENERATED BY DEFAULT AS IDENTITY,
    codigo            text        NOT NULL,
    nombre            text        NOT NULL,
    orden             integer     NOT NULL DEFAULT 0,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer     NULL,
    updated_date_time timestamptz NULL,
    updated_user_id   integer     NULL,
    active            boolean     NOT NULL DEFAULT true,
    state             boolean     NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_aprobacion_gg_estado PRIMARY KEY (gth_aprobacion_gg_estado_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_aprobacion_gg_estado_codigo_vivo
    ON gth_aprobacion_gg_estado (codigo) WHERE (state = true);

INSERT INTO gth_aprobacion_gg_estado (codigo, nombre, orden, created_date_time, active, state)
VALUES
    ('PENDIENTE',        'Pendiente de decisión',       1, now(), true, true),
    ('APROBADA',         'Aprobada (todas)',            2, now(), true, true),
    ('APROBADA_PARCIAL', 'Aprobada parcialmente',       3, now(), true, true),
    ('RECHAZADA',        'Rechazada (todas)',           4, now(), true, true)
ON CONFLICT (codigo) WHERE (state = true)
DO UPDATE SET nombre = EXCLUDED.nombre, orden = EXCLUDED.orden, active = true, updated_date_time = now();

-- ============================================================================
-- 2) Aprobación (una por solicitud)
-- ============================================================================
CREATE TABLE IF NOT EXISTS gth_aprobacion_gg (
    gth_aprobacion_gg_id        integer GENERATED BY DEFAULT AS IDENTITY,
    gth_solicitud_id            integer NOT NULL,
    token                       text    NOT NULL,
    gth_aprobacion_gg_estado_id integer NOT NULL,

    -- Snapshot de a quién se le envió el correo (Para y CC, separados por "; ").
    -- Es la única traza de quién pudo decidir: el GG no inicia sesión.
    correo_envio      text        NULL,
    correo_copia      text        NULL,
    enviado_date_time timestamptz NULL,
    -- Último reenvío ("Reenviar a Gerencia General"). El token no cambia.
    reenviado_date_time timestamptz NULL,

    decidido_date_time timestamptz NULL,
    comentario         text        NULL,

    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer     NULL,
    updated_date_time timestamptz NULL,
    updated_user_id   integer     NULL,
    active            boolean     NOT NULL DEFAULT true,
    state             boolean     NOT NULL DEFAULT true,

    CONSTRAINT pk_gth_aprobacion_gg PRIMARY KEY (gth_aprobacion_gg_id),
    CONSTRAINT fk_gag_solicitud
        FOREIGN KEY (gth_solicitud_id) REFERENCES gth_solicitud(gth_solicitud_id),
    CONSTRAINT fk_gag_estado
        FOREIGN KEY (gth_aprobacion_gg_estado_id) REFERENCES gth_aprobacion_gg_estado(gth_aprobacion_gg_estado_id)
);

-- Una sola aprobación viva por solicitud y token único entre las vigentes.
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_aprobacion_gg_solicitud_vivo
    ON gth_aprobacion_gg (gth_solicitud_id) WHERE (state = true);
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_aprobacion_gg_token_vivo
    ON gth_aprobacion_gg (token) WHERE (state = true);

-- ============================================================================
-- 3) Detalle: decisión por vacante
-- ============================================================================
CREATE TABLE IF NOT EXISTS gth_aprobacion_gg_detalle (
    gth_aprobacion_gg_detalle_id integer GENERATED BY DEFAULT AS IDENTITY,
    gth_aprobacion_gg_id         integer NOT NULL,
    gth_requerimiento_id         integer NOT NULL,
    -- true = aprobada, false = rechazada, null = el GG todavía no decide.
    aprobado           boolean     NULL,
    decidido_date_time timestamptz NULL,

    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer     NULL,
    updated_date_time timestamptz NULL,
    updated_user_id   integer     NULL,
    active            boolean     NOT NULL DEFAULT true,
    state             boolean     NOT NULL DEFAULT true,

    CONSTRAINT pk_gth_aprobacion_gg_detalle PRIMARY KEY (gth_aprobacion_gg_detalle_id),
    CONSTRAINT fk_gagd_aprobacion
        FOREIGN KEY (gth_aprobacion_gg_id) REFERENCES gth_aprobacion_gg(gth_aprobacion_gg_id),
    CONSTRAINT fk_gagd_requerimiento
        FOREIGN KEY (gth_requerimiento_id) REFERENCES gth_requerimiento(gth_requerimiento_id)
);

-- Una sola fila viva por (aprobación, requerimiento).
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_aprobacion_gg_detalle_par_vivo
    ON gth_aprobacion_gg_detalle (gth_aprobacion_gg_id, gth_requerimiento_id) WHERE (state = true);
CREATE INDEX IF NOT EXISTS ix_gth_aprobacion_gg_detalle_requerimiento
    ON gth_aprobacion_gg_detalle (gth_requerimiento_id);

-- ============================================================================
-- 4) Estado terminal del requerimiento rechazado por Gerencia General
--    active = false: es un estado del requerimiento, no una fase del pipeline
--    (la línea de tiempo del seguimiento solo muestra las fases active = true).
-- ============================================================================
INSERT INTO gth_estado_requerimiento (codigo, nombre, descripcion, orden, created_date_time, active, state)
VALUES (
    'RECHAZADO_GG',
    'Rechazado por Gerencia General',
    'Gerencia General no aprobó la vacante. El requerimiento no continúa: para volver a pedirla hay que registrar una nueva solicitud.',
    13, now(), false, true
)
ON CONFLICT (codigo) WHERE (state = true)
DO UPDATE SET
    nombre            = EXCLUDED.nombre,
    descripcion       = EXCLUDED.descripcion,
    orden             = EXCLUDED.orden,
    active            = false,
    updated_date_time = now();

-- ============================================================================
-- 5) Tipo de correo configurable del GG + reorden cronológico del catálogo
-- ============================================================================
INSERT INTO gth_correo_tipo (codigo, nombre, orden, created_date_time, active, state)
VALUES ('APROBACION_GG', 'Aprobación de Gerencia General', 1, now(), true, true)
ON CONFLICT (codigo) WHERE (state = true)
DO UPDATE SET nombre = EXCLUDED.nombre, orden = EXCLUDED.orden, active = true, updated_date_time = now();

-- Orden = secuencia real del flujo (solo afecta el ORDER BY de las consultas).
UPDATE gth_correo_tipo SET orden = 2, updated_date_time = now() WHERE codigo = 'SOLICITUD'          AND state = true AND orden <> 2;
UPDATE gth_correo_tipo SET orden = 3, updated_date_time = now() WHERE codigo = 'LONG_LIST'          AND state = true AND orden <> 3;
UPDATE gth_correo_tipo SET orden = 4, updated_date_time = now() WHERE codigo = 'LONG_LIST_DECISION' AND state = true AND orden <> 4;
UPDATE gth_correo_tipo SET orden = 5, updated_date_time = now() WHERE codigo = 'FINALISTA_DECISION' AND state = true AND orden <> 5;

-- ============================================================================
-- 6) Tipo de notificación in-app de la campanita
-- ============================================================================
INSERT INTO notificacion_tipo (codigo, nombre, orden, created_date_time, active, state)
VALUES ('GTH_APROBACION_GG', 'Solicitud de personal por aprobar', 2, now(), true, true)
ON CONFLICT (codigo) WHERE (state = true)
DO UPDATE SET nombre = EXCLUDED.nombre, orden = EXCLUDED.orden, active = true, updated_date_time = now();

COMMIT;
