-- ============================================================================
-- Unificación de categoría / ocupación / puesto
-- ============================================================================
-- Antes había CINCO catálogos solapados para describir "qué hace" un trabajador:
--   • cat_categoria        (34) → desplegable CATEGORÍA del modal, escribía TEXTO en workers.categoria
--   • workers_category     (37) → FK workers.worker_category_id, usada por Salidas/Revisores/Lecciones
--   • cat_ocupacion        (83) → desplegable OCUPACIÓN del modal (workers.ocupacion / ocupacion_id)
--   • workers.puesto            → texto libre, autocompletado como "Categoría + Ocupación"
--   • gth_puesto            (9) → desplegable de puesto de Solicitud de Personal
--
-- Ahora hay DOS, y una sola fuente de verdad para cada cosa:
--   • categoria → TODO filtro/comparación/bloqueo/restricción interna
--   • puesto    → TODO lo que se muestra en UI (sin lógica). puesto → categoria (FK)
--
-- categoria_maestra (EMPLEADO/PRACTICANTE/RCC) NO entra acá: es el tipo de vínculo
-- laboral de la Data Maestra de GTH, otro eje. La detección de practicantes
-- (cupos de razón social, Vida Ley) sigue dependiendo de ella.
--
-- Las columnas viejas (workers.categoria, .ocupacion, .puesto, .worker_category_id,
-- .ocupacion_id) NO se borran: quedan congeladas para auditoría.
--
-- Idempotente: se puede correr más de una vez sin duplicar.
-- ============================================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS unaccent;

-- ── 1. Tablas ───────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS categoria (
    categoria_id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre            text        NOT NULL,
    orden             integer     NOT NULL DEFAULT 0,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer,
    updated_date_time timestamptz,
    updated_user_id   integer,
    active            boolean     NOT NULL DEFAULT true,
    state             boolean     NOT NULL DEFAULT true
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_categoria_nombre_vivo
    ON categoria (nombre) WHERE state;

CREATE TABLE IF NOT EXISTS puesto (
    puesto_id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre            text        NOT NULL,
    categoria_id      integer     REFERENCES categoria (categoria_id),
    orden             integer     NOT NULL DEFAULT 0,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer,
    updated_date_time timestamptz,
    updated_user_id   integer,
    active            boolean     NOT NULL DEFAULT true,
    state             boolean     NOT NULL DEFAULT true
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_puesto_nombre_vivo
    ON puesto (nombre) WHERE state;
CREATE INDEX IF NOT EXISTS ix_puesto_categoria ON puesto (categoria_id);

ALTER TABLE workers
    ADD COLUMN IF NOT EXISTS categoria_id integer REFERENCES categoria (categoria_id),
    ADD COLUMN IF NOT EXISTS puesto_id    integer REFERENCES puesto (puesto_id);
CREATE INDEX IF NOT EXISTS ix_workers_categoria_id ON workers (categoria_id);
CREATE INDEX IF NOT EXISTS ix_workers_puesto_id    ON workers (puesto_id);

ALTER TABLE gth_requerimiento
    ADD COLUMN IF NOT EXISTS puesto_id integer REFERENCES puesto (puesto_id);
CREATE INDEX IF NOT EXISTS ix_gth_requerimiento_puesto_id ON gth_requerimiento (puesto_id);

ALTER TABLE gth_postulante_formulario
    ADD COLUMN IF NOT EXISTS convocatoria_puesto_id integer REFERENCES puesto (puesto_id);

-- ── 2. categoria: unión de cat_categoria + workers_category ─────────────────
-- Se deduplica por nombre sin tildes (PEON/PEÓN, TECNICO/TÉCNICO, ASISTENTE/Asistente)
-- y se conserva como canónica la variante CON tildes, en mayúsculas.

WITH fuentes AS (
    SELECT nombre, orden          FROM cat_categoria   WHERE activo
    UNION ALL
    SELECT name,   1000           FROM workers_category WHERE state AND active
), normalizadas AS (
    SELECT upper(unaccent(trim(nombre)))                      AS clave,
           upper(trim(nombre))                                AS nombre_upper,
           -- prioridad 0 = conserva tildes, 1 = sin tildes
           CASE WHEN unaccent(nombre) <> nombre THEN 0 ELSE 1 END AS prioridad,
           min(orden) OVER (PARTITION BY upper(unaccent(trim(nombre)))) AS orden
    FROM fuentes
    WHERE nullif(trim(nombre), '') IS NOT NULL
), canonicas AS (
    SELECT DISTINCT ON (clave) clave, nombre_upper, orden
    FROM normalizadas
    ORDER BY clave, prioridad, nombre_upper
)
INSERT INTO categoria (nombre, orden)
SELECT c.nombre_upper, c.orden
FROM canonicas c
WHERE NOT EXISTS (
    SELECT 1 FROM categoria x
    WHERE upper(unaccent(x.nombre)) = c.clave AND x.state
);

-- 2b. Categorías que exigen los filtros internos que hoy miran OCUPACIÓN o
--     combinan categoría+ocupación (ver bloque 6). Sin estas, esas
--     funcionalidades no tendrían por dónde filtrar.
INSERT INTO categoria (nombre, orden)
SELECT v.nombre, 2000
FROM (VALUES
    ('GERENTE GENERAL'),
    ('GERENTE DE ADMINISTRACIÓN Y FINANZAS'),
    ('COORDINADOR SSOMA')
) AS v(nombre)
WHERE NOT EXISTS (
    SELECT 1 FROM categoria x
    WHERE upper(unaccent(x.nombre)) = upper(unaccent(v.nombre)) AND x.state
);

-- ── 3. puesto: unión de workers.puesto + cat_ocupacion + gth_puesto ─────────

-- Ojo: la ocupación no solo vive en cat_ocupacion. 287 trabajadores tienen en
-- workers.ocupacion texto libre que nunca llegó al catálogo ("Gasfitero",
-- "Cajero", "Tecnico II.EE"…). Ese texto también es dato de ocupación y entra.

WITH fuentes AS (
    SELECT puesto    AS nombre, 0 AS orden FROM workers        WHERE nullif(trim(puesto), '')    IS NOT NULL
    UNION ALL
    SELECT ocupacion AS nombre, 0 AS orden FROM workers        WHERE nullif(trim(ocupacion), '') IS NOT NULL
    UNION ALL
    SELECT nombre,              orden      FROM cat_ocupacion  WHERE activo
    UNION ALL
    SELECT nombre,              orden      FROM gth_puesto     WHERE state AND active
), normalizadas AS (
    SELECT upper(unaccent(trim(nombre)))                         AS clave,
           upper(trim(nombre))                                   AS nombre_upper,
           CASE WHEN unaccent(nombre) <> nombre THEN 0 ELSE 1 END AS prioridad
    FROM fuentes
    WHERE nullif(trim(nombre), '') IS NOT NULL
), canonicas AS (
    SELECT DISTINCT ON (clave) clave, nombre_upper
    FROM normalizadas
    ORDER BY clave, prioridad, nombre_upper
)
INSERT INTO puesto (nombre)
SELECT c.nombre_upper
FROM canonicas c
WHERE NOT EXISTS (
    SELECT 1 FROM puesto x
    WHERE upper(unaccent(x.nombre)) = c.clave AND x.state
);

-- ── 4. workers.categoria_id ─────────────────────────────────────────────────
-- Prevalece el TEXTO workers.categoria (es lo que escribe el modal y lo que
-- cubre a más trabajadores: 3003 vs 2478) y, si está vacío, la FK vieja
-- worker_category_id.

UPDATE workers w
SET categoria_id = c.categoria_id
FROM categoria c
WHERE w.categoria_id IS NULL
  AND nullif(trim(w.categoria), '') IS NOT NULL
  AND upper(unaccent(c.nombre)) = upper(unaccent(trim(w.categoria)))
  AND c.state;

UPDATE workers w
SET categoria_id = c.categoria_id
FROM workers_category wc
JOIN categoria c ON upper(unaccent(c.nombre)) = upper(unaccent(trim(wc.name))) AND c.state
WHERE w.categoria_id IS NULL
  AND w.worker_category_id = wc.workers_category_id;

-- ── 5. workers.puesto_id ────────────────────────────────────────────────────
-- El PUESTO prevalece sobre la OCUPACIÓN cuando el trabajador tiene ambos.

UPDATE workers w
SET puesto_id = p.puesto_id
FROM puesto p
WHERE w.puesto_id IS NULL
  AND nullif(trim(w.puesto), '') IS NOT NULL
  AND upper(unaccent(p.nombre)) = upper(unaccent(trim(w.puesto)))
  AND p.state;

UPDATE workers w
SET puesto_id = p.puesto_id
FROM puesto p
WHERE w.puesto_id IS NULL
  AND nullif(trim(w.ocupacion), '') IS NOT NULL
  AND upper(unaccent(p.nombre)) = upper(unaccent(trim(w.ocupacion)))
  AND p.state;

-- ── 6. Filtros internos que hoy miran OCUPACIÓN → pasan a CATEGORÍA ─────────
-- Cada UPDATE reproduce exactamente la condición que hoy vive en el código,
-- para que la funcionalidad siga alcanzando a la misma gente.

-- 6a. Evaluación de Residentes: EvRecordatorioRepository (reglas 2 y 3) y
--     EvEvaluacionResidenteRepository filtran por ocupacion = 'Residencia'.
UPDATE workers w
SET categoria_id = (SELECT categoria_id FROM categoria WHERE nombre = 'RESIDENTE' AND state)
WHERE upper(unaccent(trim(w.ocupacion))) = 'RESIDENCIA';

-- 6b. Flash Report (AccidenteIncidenteRepository.GetDestinatariosFlashReportAsync)
--     filtraba por ocupacion ILIKE '%medico%' / '%gerente%general%' / '%gerente%administr%'.
UPDATE workers w
SET categoria_id = (SELECT categoria_id FROM categoria WHERE nombre = 'MÉDICO' AND state)
WHERE unaccent(w.ocupacion) ILIKE '%medico%';

UPDATE workers w
SET categoria_id = (SELECT categoria_id FROM categoria WHERE nombre = 'GERENTE GENERAL' AND state)
WHERE unaccent(w.ocupacion) ILIKE '%gerente%general%';

UPDATE workers w
SET categoria_id = (SELECT categoria_id FROM categoria WHERE nombre = 'GERENTE DE ADMINISTRACIÓN Y FINANZAS' AND state)
WHERE unaccent(w.ocupacion) ILIKE '%gerente%administr%';

-- 6c. Desempeño de Supervisores (DesempenoSupervisorRepository.EsCoordinadorSsomaAsync)
--     combinaba categoría + ocupación: "Coordinador" Y "SSOMA" en cualquiera de los dos.
UPDATE workers w
SET categoria_id = (SELECT categoria_id FROM categoria WHERE nombre = 'COORDINADOR SSOMA' AND state)
WHERE (coalesce(w.categoria, '') || ' ' || coalesce(w.ocupacion, '')) ILIKE '%coordinador%'
  AND (coalesce(w.categoria, '') || ' ' || coalesce(w.ocupacion, '')) ILIKE '%ssoma%';

-- ── 7. puesto.categoria_id ──────────────────────────────────────────────────
-- Se deriva de los datos reales: la categoría más frecuente entre los
-- trabajadores que tienen ese puesto. Es la relación que ya existe de hecho.

WITH conteo AS (
    SELECT w.puesto_id, w.categoria_id, count(*) AS n
    FROM workers w
    WHERE w.puesto_id IS NOT NULL AND w.categoria_id IS NOT NULL
    GROUP BY 1, 2
), moda AS (
    SELECT DISTINCT ON (puesto_id) puesto_id, categoria_id
    FROM conteo
    ORDER BY puesto_id, n DESC, categoria_id
)
UPDATE puesto p
SET categoria_id = m.categoria_id
FROM moda m
WHERE p.puesto_id = m.puesto_id
  AND p.categoria_id IS NULL;

-- 7b. Un puesto puede quedarse sin moda porque los trabajadores que lo ejercen
--     terminaron apuntando a otro puesto más específico: los 8 de ocupación
--     "Call Center" tienen puesto "OPERADOR DE CONTACT CENTER", así que
--     CALL CENTER se quedaba huérfano. Se mira entonces la categoría de quienes
--     tienen esa OCUPACIÓN, sin importar a qué puesto hayan terminado apuntando.
WITH conteo_ocup AS (
    SELECT p.puesto_id, w.categoria_id, count(*) AS n
    FROM puesto p
    JOIN workers w ON upper(unaccent(trim(w.ocupacion))) = upper(unaccent(p.nombre))
    WHERE p.categoria_id IS NULL AND w.categoria_id IS NOT NULL
    GROUP BY 1, 2
), moda_ocup AS (
    SELECT DISTINCT ON (puesto_id) puesto_id, categoria_id
    FROM conteo_ocup
    ORDER BY puesto_id, n DESC, categoria_id
)
UPDATE puesto p
SET categoria_id = m.categoria_id
FROM moda_ocup m
WHERE p.puesto_id = m.puesto_id
  AND p.categoria_id IS NULL;

-- 7c. Los que no tienen trabajadores (ej. los de gth_puesto: "JEFE DE OBRA",
--     "RESIDENTE DE OBRA") se resuelven por prefijo, que es exactamente cómo
--     se construyó el texto de puesto en su momento ("Categoría + Ocupación").
--     Gana el prefijo más largo: "GERENTE GENERAL" antes que "GERENTE".
WITH prefijos AS (
    SELECT DISTINCT ON (p.puesto_id) p.puesto_id, c.categoria_id
    FROM puesto p
    JOIN categoria c
      ON c.state
     AND (upper(unaccent(p.nombre)) = upper(unaccent(c.nombre))
          OR upper(unaccent(p.nombre)) LIKE upper(unaccent(c.nombre)) || ' %')
    WHERE p.categoria_id IS NULL
    ORDER BY p.puesto_id, length(c.nombre) DESC
)
UPDATE puesto p
SET categoria_id = pr.categoria_id
FROM prefijos pr
WHERE p.puesto_id = pr.puesto_id
  AND p.categoria_id IS NULL;

-- ── 8. GTH: Solicitud de Personal pasa a la tabla puesto unificada ──────────

UPDATE gth_requerimiento r
SET puesto_id = p.puesto_id
FROM gth_puesto g
JOIN puesto p ON upper(unaccent(p.nombre)) = upper(unaccent(trim(g.nombre))) AND p.state
WHERE r.gth_puesto_id = g.gth_puesto_id
  AND r.puesto_id IS NULL;

UPDATE gth_postulante_formulario f
SET convocatoria_puesto_id = p.puesto_id
FROM gth_puesto g
JOIN puesto p ON upper(unaccent(p.nombre)) = upper(unaccent(trim(g.nombre))) AND p.state
WHERE f.convocatoria_gth_puesto_id = g.gth_puesto_id
  AND f.convocatoria_puesto_id IS NULL;

-- Los 9 puestos que ya venían de gth_puesto son los únicos que Solicitud de
-- Personal ofrecía; se marcan como los "sugeridos" de ese módulo manteniendo
-- su orden original, para no perder esa curaduría (el desplegable ordena por
-- `orden` y luego por nombre, así que siguen saliendo primero).
UPDATE puesto p
SET orden = g.orden
FROM gth_puesto g
WHERE upper(unaccent(p.nombre)) = upper(unaccent(trim(g.nombre)))
  AND g.state AND g.active;

-- gth_requerimiento.gth_puesto_id era NOT NULL y todos los requerimientos
-- quedaron mapeados, así que la columna nueva también lo es (el modelo la
-- declara `int`, no `int?`). Si algún requerimiento quedara sin puesto, este
-- ALTER falla y toda la migración se revierte: es la señal de que hay que
-- revisar ese caso antes de seguir.
ALTER TABLE gth_requerimiento ALTER COLUMN puesto_id SET NOT NULL;

COMMIT;

-- ============================================================================
-- Verificación (correr después; no modifica nada)
-- ============================================================================
-- SELECT count(*) FROM categoria WHERE state;
-- SELECT count(*) FROM puesto    WHERE state;
-- SELECT count(*) AS puestos_sin_categoria FROM puesto WHERE categoria_id IS NULL AND state;
-- SELECT count(*) AS workers_sin_categoria FROM workers WHERE categoria_id IS NULL;
-- SELECT count(*) AS workers_sin_puesto    FROM workers WHERE puesto_id    IS NULL;
