-- ============================================================================
-- Gestión GTH · Reclutamiento — Candidatos de la long list
--
-- Persiste los candidatos que GTH carga en la long list (antes solo se enviaban
-- por correo, sin guardarse), para que el solicitante los revise desde su vista
-- ("Gestión de candidatos" → "Revisar long list y CVs").
--
--   • gth_candidato_estado : catálogo del estado de revisión del candidato
--                            (PENDIENTE / APROBADO / RECHAZADO).
--   • gth_candidato        : un candidato de la long list de un requerimiento,
--                            con puesto, experiencia (años), disponibilidad,
--                            fuente (canal), comentario de GTH y CV/informe en
--                            SharePoint. La decisión aprobar/rechazar y la IA que
--                            prellenará estos campos se implementan después.
--
-- Los CVs/informes se suben a la carpeta de reclutamiento ya configurada
-- (gth_sustento_folder) — no requiere nueva configuración de SharePoint.
--
-- Idempotente: se puede correr múltiples veces sin duplicar ni romper nada.
-- ============================================================================

BEGIN;

-- ============================================================================
-- 1) gth_candidato_estado — estado de revisión del candidato
-- ============================================================================
CREATE TABLE IF NOT EXISTS gth_candidato_estado (
    gth_candidato_estado_id integer GENERATED BY DEFAULT AS IDENTITY,
    codigo            text        NOT NULL,
    nombre            text        NOT NULL,
    orden             integer     NOT NULL DEFAULT 0,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer     NULL,
    updated_date_time timestamptz NULL,
    updated_user_id   integer     NULL,
    active            boolean     NOT NULL DEFAULT true,
    state             boolean     NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_candidato_estado PRIMARY KEY (gth_candidato_estado_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_candidato_estado_codigo_vivo
    ON gth_candidato_estado (codigo) WHERE (state = true);

INSERT INTO gth_candidato_estado (codigo, nombre, orden, created_date_time, active, state)
VALUES
    ('PENDIENTE', 'Pendiente', 1, now(), true, true),
    ('APROBADO',  'Aprobado',  2, now(), true, true),
    ('RECHAZADO', 'Rechazado', 3, now(), true, true)
ON CONFLICT (codigo) WHERE (state = true)
DO UPDATE SET
    nombre            = EXCLUDED.nombre,
    orden             = EXCLUDED.orden,
    active            = true,
    updated_date_time = now();

-- ============================================================================
-- 2) gth_candidato — candidato de la long list de un requerimiento
-- ============================================================================
CREATE TABLE IF NOT EXISTS gth_candidato (
    gth_candidato_id           integer GENERATED BY DEFAULT AS IDENTITY,
    gth_requerimiento_id       integer NOT NULL,
    nombre                     text    NOT NULL,
    puesto                     text    NULL,
    experiencia_anios          integer NULL,
    disponibilidad             text    NULL,
    gth_canal_publicacion_id   integer NULL,
    comentario                 text    NULL,
    cv_nombre                  text    NULL,
    cv_url                     text    NULL,
    cv_item_id                 text    NULL,
    cv_drive_id                text    NULL,
    informe_nombre             text    NULL,
    informe_url                text    NULL,
    informe_item_id            text    NULL,
    informe_drive_id           text    NULL,
    gth_candidato_estado_id    integer NOT NULL,
    orden                      integer NOT NULL DEFAULT 0,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer     NULL,
    updated_date_time timestamptz NULL,
    updated_user_id   integer     NULL,
    active            boolean     NOT NULL DEFAULT true,
    state             boolean     NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_candidato PRIMARY KEY (gth_candidato_id),
    CONSTRAINT fk_gth_candidato_requerimiento
        FOREIGN KEY (gth_requerimiento_id) REFERENCES gth_requerimiento(gth_requerimiento_id),
    CONSTRAINT fk_gth_candidato_estado
        FOREIGN KEY (gth_candidato_estado_id) REFERENCES gth_candidato_estado(gth_candidato_estado_id),
    CONSTRAINT fk_gth_candidato_canal
        FOREIGN KEY (gth_canal_publicacion_id) REFERENCES gth_canal_publicacion(gth_canal_publicacion_id)
);

CREATE INDEX IF NOT EXISTS ix_gth_candidato_requerimiento
    ON gth_candidato (gth_requerimiento_id);

COMMIT;
