-- ============================================================================
-- Gestión GTH · Reclutamiento — Formulario de información del postulante
--
-- Traslada al sistema el formulario que hoy vive en Microsoft Forms
-- ("FORMULARIO POSTULANTE - ABRIL GRUPO INMOBILIARIO"). GTH envía el enlace al
-- correo de cada candidato APROBADO; el postulante lo llena desde una página
-- pública (acceso por token, sin login) y GTH lo revisa (aprueba/rechaza).
--
--   Catálogos (datos predefinidos normalizados en su propia tabla):
--     • gth_postulante_formulario_estado : ENVIADO / COMPLETADO / APROBADO / RECHAZADO
--     • gth_estado_civil                 : Soltero(a) … Conviviente
--     • gth_tipo_documento               : DNI / CE
--     • gth_grado_academico              : Egresado … No culminado o trunco
--     • gth_disponibilidad               : Inmediata … Más de 15 días
--     • gth_motivo_cese                  : Renuncia personal … Otras
--     • gth_universidad                  : universidades del país + Otras
--     • gth_distrito                     : distritos de Lima y Callao (provincia)
--   Tabla principal:
--     • gth_postulante_formulario        : 1:1 con gth_candidato; token de acceso
--                                          público + los campos de las 4 páginas.
--       La "convocatoria de interés" reutiliza el catálogo gth_puesto.
--
-- Idempotente: se puede correr múltiples veces sin duplicar ni romper nada.
-- ============================================================================

BEGIN;

-- ============================================================================
-- Catálogos simples (codigo/nombre/orden + auditoría, 1 registro vivo por codigo)
-- ============================================================================

-- 1) gth_postulante_formulario_estado
CREATE TABLE IF NOT EXISTS gth_postulante_formulario_estado (
    gth_postulante_formulario_estado_id integer GENERATED BY DEFAULT AS IDENTITY,
    codigo            text        NOT NULL,
    nombre            text        NOT NULL,
    orden             integer     NOT NULL DEFAULT 0,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer     NULL,
    updated_date_time timestamptz NULL,
    updated_user_id   integer     NULL,
    active            boolean     NOT NULL DEFAULT true,
    state             boolean     NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_postulante_formulario_estado PRIMARY KEY (gth_postulante_formulario_estado_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_postulante_formulario_estado_codigo_vivo
    ON gth_postulante_formulario_estado (codigo) WHERE (state = true);
INSERT INTO gth_postulante_formulario_estado (codigo, nombre, orden, created_date_time, active, state)
VALUES
    ('ENVIADO',    'Enviado',    1, now(), true, true),
    ('COMPLETADO', 'Completado', 2, now(), true, true),
    ('APROBADO',   'Aprobado',   3, now(), true, true),
    ('RECHAZADO',  'Rechazado',  4, now(), true, true)
ON CONFLICT (codigo) WHERE (state = true)
DO UPDATE SET nombre = EXCLUDED.nombre, orden = EXCLUDED.orden, active = true, updated_date_time = now();

-- 2) gth_estado_civil
CREATE TABLE IF NOT EXISTS gth_estado_civil (
    gth_estado_civil_id integer GENERATED BY DEFAULT AS IDENTITY,
    codigo            text        NOT NULL,
    nombre            text        NOT NULL,
    orden             integer     NOT NULL DEFAULT 0,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer     NULL,
    updated_date_time timestamptz NULL,
    updated_user_id   integer     NULL,
    active            boolean     NOT NULL DEFAULT true,
    state             boolean     NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_estado_civil PRIMARY KEY (gth_estado_civil_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_estado_civil_codigo_vivo
    ON gth_estado_civil (codigo) WHERE (state = true);
INSERT INTO gth_estado_civil (codigo, nombre, orden, created_date_time, active, state)
VALUES
    ('SOLTERO',     'Soltero(a)',     1, now(), true, true),
    ('CASADO',      'Casado(a)',      2, now(), true, true),
    ('DIVORCIADO',  'Divorciado(a)',  3, now(), true, true),
    ('VIUDO',       'Viudo(a)',       4, now(), true, true),
    ('CONVIVIENTE', 'Conviviente',    5, now(), true, true)
ON CONFLICT (codigo) WHERE (state = true)
DO UPDATE SET nombre = EXCLUDED.nombre, orden = EXCLUDED.orden, active = true, updated_date_time = now();

-- 3) gth_tipo_documento
CREATE TABLE IF NOT EXISTS gth_tipo_documento (
    gth_tipo_documento_id integer GENERATED BY DEFAULT AS IDENTITY,
    codigo            text        NOT NULL,
    nombre            text        NOT NULL,
    orden             integer     NOT NULL DEFAULT 0,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer     NULL,
    updated_date_time timestamptz NULL,
    updated_user_id   integer     NULL,
    active            boolean     NOT NULL DEFAULT true,
    state             boolean     NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_tipo_documento PRIMARY KEY (gth_tipo_documento_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_tipo_documento_codigo_vivo
    ON gth_tipo_documento (codigo) WHERE (state = true);
INSERT INTO gth_tipo_documento (codigo, nombre, orden, created_date_time, active, state)
VALUES
    ('DNI', 'DNI', 1, now(), true, true),
    ('CE',  'CE',  2, now(), true, true)
ON CONFLICT (codigo) WHERE (state = true)
DO UPDATE SET nombre = EXCLUDED.nombre, orden = EXCLUDED.orden, active = true, updated_date_time = now();

-- 4) gth_grado_academico
CREATE TABLE IF NOT EXISTS gth_grado_academico (
    gth_grado_academico_id integer GENERATED BY DEFAULT AS IDENTITY,
    codigo            text        NOT NULL,
    nombre            text        NOT NULL,
    orden             integer     NOT NULL DEFAULT 0,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer     NULL,
    updated_date_time timestamptz NULL,
    updated_user_id   integer     NULL,
    active            boolean     NOT NULL DEFAULT true,
    state             boolean     NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_grado_academico PRIMARY KEY (gth_grado_academico_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_grado_academico_codigo_vivo
    ON gth_grado_academico (codigo) WHERE (state = true);
INSERT INTO gth_grado_academico (codigo, nombre, orden, created_date_time, active, state)
VALUES
    ('EGRESADO',          'Egresado',              1, now(), true, true),
    ('BACHILLER',         'Bachiller',             2, now(), true, true),
    ('TITULADO',          'Titulado',              3, now(), true, true),
    ('MAGISTER',          'Magíster',              4, now(), true, true),
    ('DOCTOR',            'Doctor',                5, now(), true, true),
    ('TECNICO_SUPERIOR',  'Técnico Superior',      6, now(), true, true),
    ('BACHILLER_TECNICO', 'Bachiller Técnico',     7, now(), true, true),
    ('NO_CULMINADO',      'No culminado o trunco', 8, now(), true, true)
ON CONFLICT (codigo) WHERE (state = true)
DO UPDATE SET nombre = EXCLUDED.nombre, orden = EXCLUDED.orden, active = true, updated_date_time = now();

-- 5) gth_disponibilidad
CREATE TABLE IF NOT EXISTS gth_disponibilidad (
    gth_disponibilidad_id integer GENERATED BY DEFAULT AS IDENTITY,
    codigo            text        NOT NULL,
    nombre            text        NOT NULL,
    orden             integer     NOT NULL DEFAULT 0,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer     NULL,
    updated_date_time timestamptz NULL,
    updated_user_id   integer     NULL,
    active            boolean     NOT NULL DEFAULT true,
    state             boolean     NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_disponibilidad PRIMARY KEY (gth_disponibilidad_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_disponibilidad_codigo_vivo
    ON gth_disponibilidad (codigo) WHERE (state = true);
INSERT INTO gth_disponibilidad (codigo, nombre, orden, created_date_time, active, state)
VALUES
    ('INMEDIATA',    'Inmediata',          1, now(), true, true),
    ('UNA_SEMANA',   '1 semana',           2, now(), true, true),
    ('DIEZ_QUINCE',  '10 días a 15 días',  3, now(), true, true),
    ('MAS_QUINCE',   'Más de 15 días',     4, now(), true, true)
ON CONFLICT (codigo) WHERE (state = true)
DO UPDATE SET nombre = EXCLUDED.nombre, orden = EXCLUDED.orden, active = true, updated_date_time = now();

-- 6) gth_motivo_cese
CREATE TABLE IF NOT EXISTS gth_motivo_cese (
    gth_motivo_cese_id integer GENERATED BY DEFAULT AS IDENTITY,
    codigo            text        NOT NULL,
    nombre            text        NOT NULL,
    orden             integer     NOT NULL DEFAULT 0,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer     NULL,
    updated_date_time timestamptz NULL,
    updated_user_id   integer     NULL,
    active            boolean     NOT NULL DEFAULT true,
    state             boolean     NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_motivo_cese PRIMARY KEY (gth_motivo_cese_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_motivo_cese_codigo_vivo
    ON gth_motivo_cese (codigo) WHERE (state = true);
INSERT INTO gth_motivo_cese (codigo, nombre, orden, created_date_time, active, state)
VALUES
    ('SIGO_LABORANDO',   'Actualmente sigo laborando ahí', 1, now(), true, true),
    ('RENUNCIA',         'Renuncia personal',              2, now(), true, true),
    ('TERMINO_CONTRATO', 'Término de contrato',            3, now(), true, true),
    ('MUTUO_ACUERDO',    'Mutuo acuerdo',                  4, now(), true, true),
    ('CESE_COLECTIVO',   'Cese colectivo',                 5, now(), true, true),
    ('QUIEBRE_CIERRE',   'Quiebre o cierre del empleador', 6, now(), true, true),
    ('OTRAS',            'Otras',                          7, now(), true, true)
ON CONFLICT (codigo) WHERE (state = true)
DO UPDATE SET nombre = EXCLUDED.nombre, orden = EXCLUDED.orden, active = true, updated_date_time = now();

-- 7) gth_universidad
CREATE TABLE IF NOT EXISTS gth_universidad (
    gth_universidad_id integer GENERATED BY DEFAULT AS IDENTITY,
    codigo            text        NOT NULL,
    nombre            text        NOT NULL,
    orden             integer     NOT NULL DEFAULT 0,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer     NULL,
    updated_date_time timestamptz NULL,
    updated_user_id   integer     NULL,
    active            boolean     NOT NULL DEFAULT true,
    state             boolean     NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_universidad PRIMARY KEY (gth_universidad_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_universidad_codigo_vivo
    ON gth_universidad (codigo) WHERE (state = true);
INSERT INTO gth_universidad (codigo, nombre, orden, created_date_time, active, state)
VALUES
    ('PUCP',       'Pontificia Universidad Católica del Perú (PUCP)',        1,  now(), true, true),
    ('UNMSM',      'Universidad Nacional Mayor de San Marcos (UNMSM)',       2,  now(), true, true),
    ('UPCH',       'Universidad Peruana Cayetano Heredia (UPCH)',            3,  now(), true, true),
    ('UP',         'Universidad del Pacífico (UP)',                          4,  now(), true, true),
    ('ULIMA',      'Universidad de Lima',                                    5,  now(), true, true),
    ('UPC',        'Universidad Peruana de Ciencias Aplicadas (UPC)',        6,  now(), true, true),
    ('UNI',        'Universidad Nacional de Ingeniería (UNI)',               7,  now(), true, true),
    ('UNALM',      'Universidad Nacional Agraria La Molina (UNALM)',         8,  now(), true, true),
    ('USIL',       'Universidad San Ignacio de Loyola (USIL)',               9,  now(), true, true),
    ('UDEP',       'Universidad de Piura (UDEP)',                            10, now(), true, true),
    ('ESAN',       'Universidad ESAN',                                       11, now(), true, true),
    ('USMP',       'Universidad San Martín de Porres (USMP)',                12, now(), true, true),
    ('UNFV',       'Universidad Nacional Federico Villarreal (UNFV)',        13, now(), true, true),
    ('CIENTIFICA', 'Universidad Científica del Sur',                         14, now(), true, true),
    ('WIENER',     'Universidad Privada Norbert Wiener',                     15, now(), true, true),
    ('UCV',        'Universidad César Vallejo (UCV)',                        16, now(), true, true),
    ('UPN',        'Universidad Privada del Norte (UPN)',                    17, now(), true, true),
    ('URP',        'Universidad Ricardo Palma (URP)',                        18, now(), true, true),
    ('UPSJB',      'Universidad Privada San Juan Bautista (UPSJB)',          19, now(), true, true),
    ('UCSP',       'Universidad Católica San Pablo (UCSP)',                  20, now(), true, true),
    ('UNSA',       'Universidad Nacional de San Agustín de Arequipa (UNSA)', 21, now(), true, true),
    ('UNT',        'Universidad Nacional de Trujillo (UNT)',                 22, now(), true, true),
    ('UNSAAC',     'Universidad Nacional San Antonio Abad del Cusco (UNSAAC)', 23, now(), true, true),
    ('OTRAS',      'Otras',                                                  24, now(), true, true)
ON CONFLICT (codigo) WHERE (state = true)
DO UPDATE SET nombre = EXCLUDED.nombre, orden = EXCLUDED.orden, active = true, updated_date_time = now();

-- 8) gth_distrito (Lima Metropolitana + Provincia Constitucional del Callao)
CREATE TABLE IF NOT EXISTS gth_distrito (
    gth_distrito_id   integer GENERATED BY DEFAULT AS IDENTITY,
    codigo            text        NOT NULL,
    nombre            text        NOT NULL,
    provincia         text        NOT NULL,   -- LIMA | CALLAO
    orden             integer     NOT NULL DEFAULT 0,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer     NULL,
    updated_date_time timestamptz NULL,
    updated_user_id   integer     NULL,
    active            boolean     NOT NULL DEFAULT true,
    state             boolean     NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_distrito PRIMARY KEY (gth_distrito_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_distrito_codigo_vivo
    ON gth_distrito (codigo) WHERE (state = true);
INSERT INTO gth_distrito (codigo, nombre, provincia, orden, created_date_time, active, state)
VALUES
    ('LIMA_ANCON',                 'Ancón',                 'LIMA', 1,  now(), true, true),
    ('LIMA_ATE',                   'Ate',                   'LIMA', 2,  now(), true, true),
    ('LIMA_BARRANCO',              'Barranco',              'LIMA', 3,  now(), true, true),
    ('LIMA_BRENA',                 'Breña',                 'LIMA', 4,  now(), true, true),
    ('LIMA_CARABAYLLO',            'Carabayllo',            'LIMA', 5,  now(), true, true),
    ('LIMA_CHACLACAYO',            'Chaclacayo',            'LIMA', 6,  now(), true, true),
    ('LIMA_CHORRILLOS',            'Chorrillos',            'LIMA', 7,  now(), true, true),
    ('LIMA_CIENEGUILLA',           'Cieneguilla',           'LIMA', 8,  now(), true, true),
    ('LIMA_COMAS',                 'Comas',                 'LIMA', 9,  now(), true, true),
    ('LIMA_EL_AGUSTINO',           'El Agustino',           'LIMA', 10, now(), true, true),
    ('LIMA_INDEPENDENCIA',         'Independencia',         'LIMA', 11, now(), true, true),
    ('LIMA_JESUS_MARIA',           'Jesús María',           'LIMA', 12, now(), true, true),
    ('LIMA_LA_MOLINA',             'La Molina',             'LIMA', 13, now(), true, true),
    ('LIMA_LA_VICTORIA',           'La Victoria',           'LIMA', 14, now(), true, true),
    ('LIMA_CERCADO',               'Lima (Cercado)',        'LIMA', 15, now(), true, true),
    ('LIMA_LINCE',                 'Lince',                 'LIMA', 16, now(), true, true),
    ('LIMA_LOS_OLIVOS',            'Los Olivos',            'LIMA', 17, now(), true, true),
    ('LIMA_LURIGANCHO',            'Lurigancho (Chosica)',  'LIMA', 18, now(), true, true),
    ('LIMA_LURIN',                 'Lurín',                 'LIMA', 19, now(), true, true),
    ('LIMA_MAGDALENA',             'Magdalena del Mar',     'LIMA', 20, now(), true, true),
    ('LIMA_MIRAFLORES',            'Miraflores',            'LIMA', 21, now(), true, true),
    ('LIMA_PACHACAMAC',            'Pachacámac',            'LIMA', 22, now(), true, true),
    ('LIMA_PUCUSANA',              'Pucusana',              'LIMA', 23, now(), true, true),
    ('LIMA_PUEBLO_LIBRE',          'Pueblo Libre',          'LIMA', 24, now(), true, true),
    ('LIMA_PUENTE_PIEDRA',         'Puente Piedra',         'LIMA', 25, now(), true, true),
    ('LIMA_PUNTA_HERMOSA',         'Punta Hermosa',         'LIMA', 26, now(), true, true),
    ('LIMA_PUNTA_NEGRA',           'Punta Negra',           'LIMA', 27, now(), true, true),
    ('LIMA_RIMAC',                 'Rímac',                 'LIMA', 28, now(), true, true),
    ('LIMA_SAN_BARTOLO',           'San Bartolo',           'LIMA', 29, now(), true, true),
    ('LIMA_SAN_BORJA',             'San Borja',             'LIMA', 30, now(), true, true),
    ('LIMA_SAN_ISIDRO',            'San Isidro',            'LIMA', 31, now(), true, true),
    ('LIMA_SJL',                   'San Juan de Lurigancho', 'LIMA', 32, now(), true, true),
    ('LIMA_SJM',                   'San Juan de Miraflores', 'LIMA', 33, now(), true, true),
    ('LIMA_SAN_LUIS',              'San Luis',              'LIMA', 34, now(), true, true),
    ('LIMA_SMP',                   'San Martín de Porres',  'LIMA', 35, now(), true, true),
    ('LIMA_SAN_MIGUEL',            'San Miguel',            'LIMA', 36, now(), true, true),
    ('LIMA_SANTA_ANITA',           'Santa Anita',           'LIMA', 37, now(), true, true),
    ('LIMA_SANTA_MARIA',           'Santa María del Mar',   'LIMA', 38, now(), true, true),
    ('LIMA_SANTA_ROSA',            'Santa Rosa',            'LIMA', 39, now(), true, true),
    ('LIMA_SURCO',                 'Santiago de Surco',     'LIMA', 40, now(), true, true),
    ('LIMA_SURQUILLO',             'Surquillo',             'LIMA', 41, now(), true, true),
    ('LIMA_VES',                   'Villa El Salvador',     'LIMA', 42, now(), true, true),
    ('LIMA_VMT',                   'Villa María del Triunfo', 'LIMA', 43, now(), true, true),
    ('CALLAO_CALLAO',              'Callao',                'CALLAO', 44, now(), true, true),
    ('CALLAO_BELLAVISTA',          'Bellavista',            'CALLAO', 45, now(), true, true),
    ('CALLAO_CARMEN_LEGUA',        'Carmen de la Legua Reynoso', 'CALLAO', 46, now(), true, true),
    ('CALLAO_LA_PERLA',            'La Perla',              'CALLAO', 47, now(), true, true),
    ('CALLAO_LA_PUNTA',            'La Punta',              'CALLAO', 48, now(), true, true),
    ('CALLAO_VENTANILLA',          'Ventanilla',            'CALLAO', 49, now(), true, true),
    ('CALLAO_MI_PERU',             'Mi Perú',               'CALLAO', 50, now(), true, true)
ON CONFLICT (codigo) WHERE (state = true)
DO UPDATE SET nombre = EXCLUDED.nombre, provincia = EXCLUDED.provincia, orden = EXCLUDED.orden, active = true, updated_date_time = now();

-- ============================================================================
-- Tabla principal: gth_postulante_formulario (1:1 con gth_candidato)
-- ============================================================================
CREATE TABLE IF NOT EXISTS gth_postulante_formulario (
    gth_postulante_formulario_id        integer GENERATED BY DEFAULT AS IDENTITY,
    gth_candidato_id                    integer NOT NULL,
    token                               text    NOT NULL,
    gth_postulante_formulario_estado_id integer NOT NULL,
    correo_envio                        text    NOT NULL,

    enviado_date_time    timestamptz NULL,
    enviado_user_id      integer     NULL,
    completado_date_time timestamptz NULL,
    revisado_user_id     integer     NULL,
    revisado_nombre      text        NULL,
    revisado_date_time   timestamptz NULL,
    motivo_rechazo       text        NULL,

    -- Página 1 · Datos personales
    nombres_completos          text    NULL,
    fecha_nacimiento           date    NULL,
    gth_estado_civil_id        integer NULL,
    gth_tipo_documento_id      integer NULL,
    numero_documento           text    NULL,
    gth_distrito_id            integer NULL,
    correo_electronico         text    NULL,
    numero_celular             text    NULL,
    convocatoria_gth_puesto_id integer NULL,
    pretensiones_salariales    text    NULL,
    gth_disponibilidad_id      integer NULL,
    linkedin                   text    NULL,
    portafolio_link            text    NULL,

    -- Página 2 · Estudios realizados
    profesion             text    NULL,
    gth_universidad_id    integer NULL,
    gth_grado_academico_id integer NULL,
    numero_colegiatura    text    NULL,

    -- Página 3 · Experiencia laboral (más reciente)
    empresa                              text    NULL,
    area_trabajo                         text    NULL,
    cargo                                text    NULL,
    fecha_inicio                         date    NULL,
    fecha_termino                        date    NULL,
    gth_motivo_cese_id                   integer NULL,
    funciones_principales                text    NULL,
    logros                               text    NULL,
    ingreso_bruto_mensual                text    NULL,
    personas_a_cargo                     integer NULL,
    jefe_inmediato                       text    NULL,
    autoriza_verificacion_referencias    boolean NULL,

    -- Página 4 · Consentimiento y veracidad
    declaracion_veracidad   boolean NULL,
    confirmacion_documentos boolean NULL,

    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer     NULL,
    updated_date_time timestamptz NULL,
    updated_user_id   integer     NULL,
    active            boolean     NOT NULL DEFAULT true,
    state             boolean     NOT NULL DEFAULT true,

    CONSTRAINT pk_gth_postulante_formulario PRIMARY KEY (gth_postulante_formulario_id),
    CONSTRAINT fk_gpf_candidato
        FOREIGN KEY (gth_candidato_id) REFERENCES gth_candidato(gth_candidato_id),
    CONSTRAINT fk_gpf_estado
        FOREIGN KEY (gth_postulante_formulario_estado_id) REFERENCES gth_postulante_formulario_estado(gth_postulante_formulario_estado_id),
    CONSTRAINT fk_gpf_estado_civil
        FOREIGN KEY (gth_estado_civil_id) REFERENCES gth_estado_civil(gth_estado_civil_id),
    CONSTRAINT fk_gpf_tipo_documento
        FOREIGN KEY (gth_tipo_documento_id) REFERENCES gth_tipo_documento(gth_tipo_documento_id),
    CONSTRAINT fk_gpf_distrito
        FOREIGN KEY (gth_distrito_id) REFERENCES gth_distrito(gth_distrito_id),
    CONSTRAINT fk_gpf_convocatoria_puesto
        FOREIGN KEY (convocatoria_gth_puesto_id) REFERENCES gth_puesto(gth_puesto_id),
    CONSTRAINT fk_gpf_disponibilidad
        FOREIGN KEY (gth_disponibilidad_id) REFERENCES gth_disponibilidad(gth_disponibilidad_id),
    CONSTRAINT fk_gpf_universidad
        FOREIGN KEY (gth_universidad_id) REFERENCES gth_universidad(gth_universidad_id),
    CONSTRAINT fk_gpf_grado_academico
        FOREIGN KEY (gth_grado_academico_id) REFERENCES gth_grado_academico(gth_grado_academico_id),
    CONSTRAINT fk_gpf_motivo_cese
        FOREIGN KEY (gth_motivo_cese_id) REFERENCES gth_motivo_cese(gth_motivo_cese_id)
);

-- Un solo formulario vivo por candidato (1:1) y token único entre los vigentes.
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_postulante_formulario_candidato_vivo
    ON gth_postulante_formulario (gth_candidato_id) WHERE (state = true);
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_postulante_formulario_token_vivo
    ON gth_postulante_formulario (token) WHERE (state = true);

COMMIT;
