-- ============================================================================
-- Gestión GTH · Reclutamiento — Prioridad del requerimiento
--
-- 1) Crea el catálogo `gth_prioridad` y siembra Alta / Media / Baja.
-- 2) Agrega `gth_prioridad_id` (FK nullable) a `gth_requerimiento`.
-- 3) Backfill: los requerimientos existentes sin prioridad quedan en "Media".
--
-- La prioridad la asigna GTH desde la bandeja de reclutamiento; al crear una
-- solicitud el backend asigna "Media" por defecto.
--
-- Idempotente: se puede correr múltiples veces sin duplicar ni romper nada.
-- ============================================================================

BEGIN;

-- 1) Catálogo de prioridad ---------------------------------------------------
CREATE TABLE IF NOT EXISTS gth_prioridad (
    gth_prioridad_id  integer GENERATED BY DEFAULT AS IDENTITY,
    codigo            text        NOT NULL,
    nombre            text        NOT NULL,
    orden             integer     NOT NULL DEFAULT 0,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer     NULL,
    updated_date_time timestamptz NULL,
    updated_user_id   integer     NULL,
    active            boolean     NOT NULL DEFAULT true,
    state             boolean     NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_prioridad PRIMARY KEY (gth_prioridad_id)
);

-- Solo un registro "vivo" (state = true) por código.
CREATE UNIQUE INDEX IF NOT EXISTS ix_gth_prioridad_codigo_vivo
    ON gth_prioridad (codigo) WHERE (state = true);

-- Seed (upsert por código vivo). Orden semántico Alta→Media→Baja.
INSERT INTO gth_prioridad (codigo, nombre, orden, created_date_time, active, state)
VALUES
    ('ALTA',  'Alta',  1, now(), true, true),
    ('MEDIA', 'Media', 2, now(), true, true),
    ('BAJA',  'Baja',  3, now(), true, true)
ON CONFLICT (codigo) WHERE (state = true)
DO UPDATE SET
    nombre            = EXCLUDED.nombre,
    orden             = EXCLUDED.orden,
    active            = true,
    updated_date_time = now();

-- 2) FK en gth_requerimiento -------------------------------------------------
ALTER TABLE gth_requerimiento
    ADD COLUMN IF NOT EXISTS gth_prioridad_id integer NULL;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_gth_req_prioridad') THEN
        ALTER TABLE gth_requerimiento
            ADD CONSTRAINT fk_gth_req_prioridad
            FOREIGN KEY (gth_prioridad_id) REFERENCES gth_prioridad(gth_prioridad_id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS ix_gth_requerimiento_prioridad
    ON gth_requerimiento (gth_prioridad_id);

-- 3) Backfill: requerimientos existentes sin prioridad → Media ---------------
UPDATE gth_requerimiento r
SET gth_prioridad_id = p.gth_prioridad_id
FROM gth_prioridad p
WHERE p.codigo = 'MEDIA' AND p.state = true
  AND r.gth_prioridad_id IS NULL;

COMMIT;
