-- ============================================================================
-- Gestión GTH · Reclutamiento — Bitácora de fases del requerimiento
--
-- Problema que resuelve: `gth_requerimiento` solo guarda el estado ACTUAL y el
-- último `updated_user_id`/`updated_date_time`. Cuando la vacante pasa de
-- PUBLICACION a LONG_LIST se pierde quién la publicó y a qué hora, así que no
-- hay forma de responder cuánto se demora cada paso del proceso.
--
-- 1) Crea `gth_requerimiento_estado_historial`: una fila por cada cambio de
--    fase, con la fase de la que salió, a la que entró, quién lo hizo y cuándo.
-- 2) Reconstruye lo que se puede de los requerimientos que ya existen y los
--    marca con `reconstruido = true` para no confundirlos con traza real.
--
-- De acá en adelante las filas las escribe el backend en el mismo SaveChanges
-- que mueve la vacante (RequerimientoEstadoHistorialInterceptor), así que no
-- hay nada que ejecutar de nuevo después del deploy.
--
-- Idempotente: se puede correr varias veces sin duplicar ni romper nada.
-- ============================================================================

BEGIN;

-- 1) Tabla --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS gth_requerimiento_estado_historial (
    gth_requerimiento_estado_historial_id integer     GENERATED BY DEFAULT AS IDENTITY,
    gth_requerimiento_id                  integer     NOT NULL,
    -- Fase de la que salió. NULL solo en la primera fila de cada requerimiento
    -- (el alta: no venía de ninguna parte).
    estado_anterior_id                    integer     NULL,
    -- Fase a la que entró con este cambio.
    gth_estado_requerimiento_id           integer     NOT NULL,
    -- Momento del cambio (UTC). No es la hora de grabado de la fila: en las
    -- filas reconstruidas son distintas.
    cambio_date_time                      timestamptz NOT NULL,
    -- Usuario (app_user) que movió la vacante. NULL cuando el cambio no salió
    -- de una sesión. Sin FK, igual que el resto de *_user_id del proyecto.
    cambio_user_id                        integer     NULL,
    -- true = fila deducida de created_*/updated_* por esta migración, no
    -- capturada en el momento del cambio. Todo cálculo de demoras debería
    -- filtrarlas o tratarlas aparte: un requerimiento que pasó por seis fases
    -- aparece acá con dos o tres filas.
    reconstruido                          boolean     NOT NULL DEFAULT false,
    created_date_time                     timestamptz NOT NULL DEFAULT now(),
    active                                boolean     NOT NULL DEFAULT true,
    state                                 boolean     NOT NULL DEFAULT true,
    CONSTRAINT pk_gth_requerimiento_estado_historial
        PRIMARY KEY (gth_requerimiento_estado_historial_id)
);

-- La línea de tiempo de un requerimiento se lee siempre así: sus filas en orden.
CREATE INDEX IF NOT EXISTS ix_gth_req_estado_hist_requerimiento
    ON gth_requerimiento_estado_historial (gth_requerimiento_id, cambio_date_time);

CREATE INDEX IF NOT EXISTS ix_gth_req_estado_hist_estado
    ON gth_requerimiento_estado_historial (gth_estado_requerimiento_id);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_gth_req_estado_hist_requerimiento') THEN
        ALTER TABLE gth_requerimiento_estado_historial
            ADD CONSTRAINT fk_gth_req_estado_hist_requerimiento
            FOREIGN KEY (gth_requerimiento_id)
            REFERENCES gth_requerimiento(gth_requerimiento_id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_gth_req_estado_hist_estado') THEN
        ALTER TABLE gth_requerimiento_estado_historial
            ADD CONSTRAINT fk_gth_req_estado_hist_estado
            FOREIGN KEY (gth_estado_requerimiento_id)
            REFERENCES gth_estado_requerimiento(gth_estado_requerimiento_id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_gth_req_estado_hist_estado_anterior') THEN
        ALTER TABLE gth_requerimiento_estado_historial
            ADD CONSTRAINT fk_gth_req_estado_hist_estado_anterior
            FOREIGN KEY (estado_anterior_id)
            REFERENCES gth_estado_requerimiento(gth_estado_requerimiento_id);
    END IF;
END $$;

COMMENT ON TABLE gth_requerimiento_estado_historial IS
    'Bitacora de fases del requerimiento de reclutamiento: una fila por cambio de estado, con quien lo movio y cuando. La escribe el backend en el mismo SaveChanges que mueve la vacante.';

-- 2) Reconstrucción de los requerimientos que ya existen ----------------------
--
-- Lo que se puede saber sin haber estado ahí:
--   - el alta: created_date_time / created_user_id de la vacante;
--   - la decisión de la aprobación: fecha y usuario reales de
--     gth_aprobacion_gg(_detalle), que sí los guarda por nivel;
--   - el estado de hoy: updated_date_time / updated_user_id.
-- Las fases intermedias (publicación, long list, entrevistas...) no dejaron
-- rastro y no se inventan. Todo esto entra con reconstruido = true.
--
-- Solo toca los requerimientos que todavía no tienen ninguna fila: correrlo de
-- nuevo no agrega nada, y nunca pisa lo que el backend ya haya registrado.

WITH cat AS (
    SELECT codigo, gth_estado_requerimiento_id AS id, orden
    FROM gth_estado_requerimiento
),
base AS (
    SELECT r.gth_requerimiento_id                              AS req_id,
           r.created_date_time                                 AS creado,
           r.created_user_id                                   AS creado_por,
           COALESCE(r.updated_date_time, r.created_date_time)  AS actualizado,
           r.updated_user_id                                   AS actualizado_por,
           r.gth_estado_requerimiento_id                       AS estado_actual_id,
           ea.orden                                            AS estado_actual_orden,
           r.es_fft,
           -- Una solicitud sin fila en gth_aprobacion_gg es el FFT que registró
           -- el propio Gerente General: nace ya en manos de GTH, sin pasar por
           -- la pantalla de Aprobaciones.
           EXISTS (SELECT 1
                     FROM gth_aprobacion_gg a
                    WHERE a.gth_solicitud_id = r.gth_solicitud_id
                      AND a.state)                             AS con_aprobacion
      FROM gth_requerimiento r
      JOIN gth_estado_requerimiento ea
        ON ea.gth_estado_requerimiento_id = r.gth_estado_requerimiento_id
     WHERE NOT EXISTS (SELECT 1
                         FROM gth_requerimiento_estado_historial h
                        WHERE h.gth_requerimiento_id = r.gth_requerimiento_id)
),
inicio AS (
    SELECT b.*,
           CASE WHEN b.es_fft AND NOT b.con_aprobacion
                THEN (SELECT id FROM cat WHERE codigo = 'LONG_LIST_APROBADA')
                ELSE (SELECT id FROM cat WHERE codigo = 'APROBACION_GG')
           END AS inferido_id
      FROM base b
),
inicio_ok AS (
    -- La fase de arranque nunca puede ir por delante de la de hoy: los
    -- requerimientos anteriores al pipeline actual siguen parados en NUEVO.
    SELECT i.*,
           CASE WHEN i.estado_actual_orden < ci.orden
                THEN i.estado_actual_id
                ELSE i.inferido_id
           END AS estado_inicial_id
      FROM inicio i
      JOIN gth_estado_requerimiento ci
        ON ci.gth_estado_requerimiento_id = i.inferido_id
),
-- Las decisiones reales de la aprobación, aplanando los tres niveles (Gerencia
-- General, gerente del área y GTH) a una fila por firma.
firmas AS (
    SELECT d.gth_requerimiento_id AS req_id,
           x.aprobado,
           x.fecha,
           x.usuario
      FROM gth_aprobacion_gg_detalle d
      JOIN gth_aprobacion_gg a
        ON a.gth_aprobacion_gg_id = d.gth_aprobacion_gg_id
     CROSS JOIN LATERAL (VALUES
            (d.aprobado_gerente_general, d.gerente_general_decidido_date_time, a.gerente_general_decidido_user_id),
            (d.aprobado_gerente_area,    d.gerente_area_decidido_date_time,    a.gerente_area_decidido_user_id),
            (d.aprobado_gth,             d.gth_decidido_date_time,             a.gth_decidido_user_id)
     ) AS x(aprobado, fecha, usuario)
     WHERE d.state AND a.state
       AND x.aprobado IS NOT NULL
       AND x.fecha    IS NOT NULL
),
-- Qué firma movió la vacante: el primer rechazo la corta; si nadie rechazó, la
-- mueve la última aprobación (los reemplazos necesitan dos).
decision AS (
    SELECT req_id,
           bool_or(aprobado = false)                                                     AS hubo_rechazo,
           MIN(fecha) FILTER (WHERE aprobado = false)                                    AS fecha_rechazo,
           MAX(fecha) FILTER (WHERE aprobado = true)                                     AS fecha_aprobacion,
           (array_agg(usuario ORDER BY fecha)      FILTER (WHERE aprobado = false))[1]   AS user_rechazo,
           (array_agg(usuario ORDER BY fecha DESC) FILTER (WHERE aprobado = true))[1]    AS user_aprobacion
      FROM firmas
     GROUP BY req_id
),
paso_aprobacion AS (
    SELECT i.req_id,
           i.estado_inicial_id AS anterior_id,
           CASE WHEN d.hubo_rechazo THEN (SELECT id FROM cat WHERE codigo = 'RECHAZADO_GG')
                WHEN i.es_fft       THEN (SELECT id FROM cat WHERE codigo = 'LONG_LIST_APROBADA')
                ELSE                     (SELECT id FROM cat WHERE codigo = 'VALIDACION_GTH')
           END AS estado_id,
           GREATEST(i.creado,
                    CASE WHEN d.hubo_rechazo THEN d.fecha_rechazo ELSE d.fecha_aprobacion END) AS cuando,
           CASE WHEN d.hubo_rechazo THEN d.user_rechazo ELSE d.user_aprobacion END              AS quien
      FROM inicio_ok i
      JOIN decision d ON d.req_id = i.req_id
     WHERE i.estado_inicial_id = (SELECT id FROM cat WHERE codigo = 'APROBACION_GG')
       AND i.estado_actual_id <> (SELECT id FROM cat WHERE codigo = 'APROBACION_GG')
       AND (CASE WHEN d.hubo_rechazo THEN d.fecha_rechazo ELSE d.fecha_aprobacion END) IS NOT NULL
),
ultimo AS (
    SELECT i.req_id,
           i.estado_actual_id,
           i.actualizado,
           i.actualizado_por,
           COALESCE(p.estado_id, i.estado_inicial_id) AS ultimo_estado_id,
           COALESCE(p.cuando,    i.creado)            AS ultimo_cuando
      FROM inicio_ok i
      LEFT JOIN paso_aprobacion p ON p.req_id = i.req_id
),
paso_actual AS (
    SELECT u.req_id,
           u.ultimo_estado_id                       AS anterior_id,
           u.estado_actual_id                       AS estado_id,
           GREATEST(u.actualizado, u.ultimo_cuando) AS cuando,
           u.actualizado_por                        AS quien
      FROM ultimo u
     WHERE u.estado_actual_id <> u.ultimo_estado_id
),
pasos AS (
    SELECT req_id, NULL::integer AS anterior_id, estado_inicial_id AS estado_id,
           creado AS cuando, creado_por AS quien, 1 AS paso
      FROM inicio_ok
    UNION ALL
    SELECT req_id, anterior_id, estado_id, cuando, quien, 2 FROM paso_aprobacion
    UNION ALL
    SELECT req_id, anterior_id, estado_id, cuando, quien, 3 FROM paso_actual
)
INSERT INTO gth_requerimiento_estado_historial (
    gth_requerimiento_id, estado_anterior_id, gth_estado_requerimiento_id,
    cambio_date_time, cambio_user_id, reconstruido, created_date_time, active, state)
SELECT req_id, anterior_id, estado_id, cuando, quien, true, now(), true, true
  FROM pasos
 ORDER BY req_id, paso;

COMMIT;

-- ============================================================================
-- Comprobación (opcional): la línea de tiempo de cada requerimiento con lo que
-- duró cada fase. El último tramo de cada uno sale NULL porque sigue corriendo.
-- ============================================================================
-- SELECT r.codigo,
--        ea.nombre AS venia_de,
--        en.nombre AS paso_a,
--        h.cambio_date_time AT TIME ZONE 'America/Lima' AS cuando,
--        h.cambio_user_id,
--        h.reconstruido,
--        LEAD(h.cambio_date_time) OVER (PARTITION BY h.gth_requerimiento_id
--                                           ORDER BY h.cambio_date_time,
--                                                    h.gth_requerimiento_estado_historial_id)
--            - h.cambio_date_time AS duro_en_esta_fase
--   FROM gth_requerimiento_estado_historial h
--   JOIN gth_requerimiento r         ON r.gth_requerimiento_id = h.gth_requerimiento_id
--   JOIN gth_estado_requerimiento en ON en.gth_estado_requerimiento_id = h.gth_estado_requerimiento_id
--   LEFT JOIN gth_estado_requerimiento ea ON ea.gth_estado_requerimiento_id = h.estado_anterior_id
--  WHERE h.state
--  ORDER BY r.codigo, h.cambio_date_time, h.gth_requerimiento_estado_historial_id;
