-- ============================================================================
-- Notificaciones in-app (campanita del encabezado)
--
-- 1) `notificacion_tipo`: catálogo de tipos de notificación (normalizado, regla
--    del proyecto). Seed inicial: GTH_SOLICITUD_PERSONAL (se crea una
--    notificación por requerimiento cuando alguien registra una solicitud de
--    personal; los destinatarios son los correos configurados en
--    gth_correo_destinatario, los mismos del correo de notificación).
-- 2) `notificacion`: una fila por destinatario × evento. `leida` marca el
--    estado leído/no leído ("apagar colores" al hacer click); `origen_*`
--    identifica a quien generó el evento (para las iniciales del avatar).
--
-- Idempotente: se puede correr múltiples veces sin duplicar ni romper nada.
-- ============================================================================

BEGIN;

-- 1) Catálogo de tipos ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS notificacion_tipo (
    notificacion_tipo_id integer  GENERATED BY DEFAULT AS IDENTITY,
    codigo            text        NOT NULL,
    nombre            text        NOT NULL,
    orden             integer     NOT NULL DEFAULT 0,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer     NULL,
    updated_date_time timestamptz NULL,
    updated_user_id   integer     NULL,
    active            boolean     NOT NULL DEFAULT true,
    state             boolean     NOT NULL DEFAULT true,
    CONSTRAINT pk_notificacion_tipo PRIMARY KEY (notificacion_tipo_id)
);

-- Solo un registro "vivo" (state = true) por código.
CREATE UNIQUE INDEX IF NOT EXISTS ix_notificacion_tipo_codigo_vivo
    ON notificacion_tipo (codigo) WHERE (state = true);

INSERT INTO notificacion_tipo (codigo, nombre, orden, created_date_time, active, state)
VALUES
    ('GTH_SOLICITUD_PERSONAL', 'Nueva solicitud de personal', 1, now(), true, true)
ON CONFLICT (codigo) WHERE (state = true)
DO UPDATE SET
    nombre            = EXCLUDED.nombre,
    orden             = EXCLUDED.orden,
    active            = true,
    updated_date_time = now();

-- 2) Notificaciones ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS notificacion (
    notificacion_id   integer     GENERATED BY DEFAULT AS IDENTITY,
    user_id           integer     NOT NULL,   -- destinatario (app_user)
    notificacion_tipo_id integer  NOT NULL,
    titulo            text        NOT NULL,
    subtitulo         text        NULL,       -- p.ej. "Puesto — Área"
    descripcion       text        NULL,       -- p.ej. justificación de la solicitud
    referencia        text        NULL,       -- p.ej. REQ-AAAA-NNNN
    origen_user_id    integer     NULL,       -- quién generó el evento
    origen_nombre     text        NULL,       -- snapshot del nombre (iniciales del avatar)
    leida             boolean     NOT NULL DEFAULT false,
    leida_date_time   timestamptz NULL,
    created_date_time timestamptz NOT NULL DEFAULT now(),
    created_user_id   integer     NULL,
    updated_date_time timestamptz NULL,
    updated_user_id   integer     NULL,
    active            boolean     NOT NULL DEFAULT true,
    state             boolean     NOT NULL DEFAULT true,
    CONSTRAINT pk_notificacion PRIMARY KEY (notificacion_id),
    CONSTRAINT fk_notificacion_user FOREIGN KEY (user_id) REFERENCES app_user(user_id),
    CONSTRAINT fk_notificacion_tipo FOREIGN KEY (notificacion_tipo_id) REFERENCES notificacion_tipo(notificacion_tipo_id),
    CONSTRAINT fk_notificacion_origen_user FOREIGN KEY (origen_user_id) REFERENCES app_user(user_id)
);

CREATE INDEX IF NOT EXISTS ix_notificacion_user ON notificacion (user_id);
-- Acelera el contador de no leídas de la campanita.
CREATE INDEX IF NOT EXISTS ix_notificacion_user_no_leida
    ON notificacion (user_id) WHERE (leida = false AND state = true);

COMMIT;
