-- ============================================================================
-- Tabla filtro única de proyectos por funcionalidad (patrón lesson_area)
-- ============================================================================
-- project pasa a ser la tabla matriz/madre. Cada funcionalidad que lista
-- proyectos filtrando por project.active consulta ahora la tabla única
-- proyecto_filtro junto con el catálogo proyecto_filtro_funcionalidad:
--   - fila ausente          => el proyecto ES visible en esa funcionalidad
--   - fila con active=false => el proyecto NO aparece en esa funcionalidad
-- project.active sigue siendo el interruptor maestro global (si está en false,
-- el proyecto no aparece en ninguna funcionalidad, tenga o no fila filtro).
--
-- Los IDs del catálogo son fijos y se espejan en el backend en
-- Shared/Constants/ProyectoFiltroFuncionalidades.cs (mismo patrón que Roles).
--
-- Motivo: Oficina Central (project_id 36) estaba active=false y el commit
-- 55827e1f (18/07/2026) hizo que desapareciera del filtro de AC Actividades,
-- donde sí se necesita. Se reactiva en project y se oculta explícitamente en
-- las demás funcionalidades para no cambiarles el comportamiento.
-- Idempotente: se puede ejecutar más de una vez sin error.
-- ============================================================================

-- Limpieza de la versión anterior (13 tablas por funcionalidad); solo llegó a
-- aplicarse en dev, en producción estos DROP no hacen nada.
DROP TABLE IF EXISTS
    ac_actividad_proyecto_filtro,
    ac_observacion_proyecto_filtro,
    ac_revision_proyecto_filtro,
    hab_proyecto_filtro,
    shared_filters_proyecto_filtro,
    udp_cronograma_proyecto_filtro,
    udp_dashboard_proyecto_filtro,
    vecino_gestion_proyecto_filtro,
    vecino_croquis_proyecto_filtro,
    lesson_proyecto_filtro,
    residente_proyecto_filtro,
    ssoma_amonestacion_proyecto_filtro,
    ss_accidente_proyecto_filtro;

-- ----------------------------------------------------------------------------
-- Catálogo de funcionalidades (IDs fijos, espejo de las constantes del backend)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS proyecto_filtro_funcionalidad (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      text NOT NULL,
    nombre      text NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ux_proyecto_filtro_funcionalidad_codigo UNIQUE (codigo)
);

INSERT INTO proyecto_filtro_funcionalidad (id, codigo, nombre) VALUES
    (1,  'AC_ACTIVIDADES',       'Arquitectura Comercial — Actividades/Gantt/Dashboard'),
    (2,  'AC_OBSERVACIONES',     'Arquitectura Comercial — Observaciones'),
    (3,  'AC_REVISIONES',        'Arquitectura Comercial — Revisiones'),
    (4,  'HABILITACION',         'Habilitación'),
    (5,  'SHARED_FILTERS',       'Filtros compartidos (EMOs, Indicadores Proactivos, Charlas)'),
    (6,  'UDP_CRONOGRAMA',       'Unidad de Proyectos — Cronograma de Actividades'),
    (7,  'UDP_DASHBOARD',        'Unidad de Proyectos — Dashboard'),
    (8,  'VECINOS_GESTION',      'Vecinos — Gestión'),
    (9,  'VECINOS_CROQUIS',      'Vecinos — Croquis'),
    (10, 'LECCIONES_APRENDIDAS', 'Lecciones Aprendidas'),
    (11, 'RESIDENTES',           'Residentes (proyectos, incidencias, monitoreo)'),
    (12, 'SSOMA_AMONESTACIONES', 'SSOMA — Amonestaciones'),
    (13, 'SSOMA_ACCIDENTES',     'SSOMA — Accidentes/Incidentes (Flash Report)')
ON CONFLICT (id) DO NOTHING;

-- Alinear la secuencia de la identity con los IDs insertados a mano
SELECT setval(
    pg_get_serial_sequence('proyecto_filtro_funcionalidad', 'id'),
    GREATEST((SELECT MAX(id) FROM proyecto_filtro_funcionalidad), 1)
);

-- ----------------------------------------------------------------------------
-- Tabla filtro única
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS proyecto_filtro (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id        integer NOT NULL REFERENCES project(project_id),
    funcionalidad_id  integer NOT NULL REFERENCES proyecto_filtro_funcionalidad(id),
    active            boolean NOT NULL DEFAULT true,
    created_at        timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ux_proyecto_filtro UNIQUE (project_id, funcionalidad_id)
);

-- ----------------------------------------------------------------------------
-- Seed: se reactiva Oficina Central (36) en project y se oculta explícitamente
-- en todas las funcionalidades excepto AC Actividades (la que la necesita).
-- ----------------------------------------------------------------------------
UPDATE project SET active = true WHERE project_id = 36 AND active = false;

-- Oculto en todas las funcionalidades menos AC_ACTIVIDADES
INSERT INTO proyecto_filtro (project_id, funcionalidad_id, active)
SELECT 36, fn.id, false
FROM proyecto_filtro_funcionalidad fn
WHERE fn.codigo <> 'AC_ACTIVIDADES'
ON CONFLICT (project_id, funcionalidad_id) DO NOTHING;

-- Visible en AC Actividades (fila explícita solo como documentación del caso;
-- sin fila también sería visible)
INSERT INTO proyecto_filtro (project_id, funcionalidad_id, active)
SELECT 36, fn.id, true
FROM proyecto_filtro_funcionalidad fn
WHERE fn.codigo = 'AC_ACTIVIDADES'
ON CONFLICT (project_id, funcionalidad_id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- Post Venta (project_id 40) — mismo caso que Oficina Central (2026-07-24).
-- El proyecto estaba active=false y por el filtro p.Active de AC Actividades
-- (ArquitecturaComercialRepository.GetProyectosConActividades) dejó de aparecer
-- como opción de proyecto en Arquitectura Comercial, aunque sus actividades
-- (p. ej. "PINTADO DE SALA DE REUNIONES_OFICINA") siguen activas. Se reactiva en
-- project y se oculta explícitamente en las demás funcionalidades para no
-- cambiarles el comportamiento (solo debe reaparecer en AC Actividades).
-- ----------------------------------------------------------------------------
UPDATE project SET active = true WHERE project_id = 40 AND active = false;

-- Oculto en todas las funcionalidades menos AC_ACTIVIDADES
INSERT INTO proyecto_filtro (project_id, funcionalidad_id, active)
SELECT 40, fn.id, false
FROM proyecto_filtro_funcionalidad fn
WHERE fn.codigo <> 'AC_ACTIVIDADES'
ON CONFLICT (project_id, funcionalidad_id) DO NOTHING;

-- Visible en AC Actividades (fila explícita solo como documentación del caso;
-- sin fila también sería visible)
INSERT INTO proyecto_filtro (project_id, funcionalidad_id, active)
SELECT 40, fn.id, true
FROM proyecto_filtro_funcionalidad fn
WHERE fn.codigo = 'AC_ACTIVIDADES'
ON CONFLICT (project_id, funcionalidad_id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- HABILITACION_INDUCCION (2026-08-05) — se parte el filtro de Habilitación.
-- La funcionalidad HABILITACION (4) alimentaba a la vez cuatro desplegables:
-- el filtro de proyecto de la lista de Trabajadores, el modal de EMOs Programados,
-- la asignación de proyectos por empresa y el desplegable del modal "Programar
-- Inducción". Oficina Central (36) debe ser inducible sin reaparecer en los otros
-- tres, así que el modal de inducción pasa a tener su propio filtro (14) y la
-- funcionalidad 4 se queda con el resto.
-- Semántica de la tabla: fila ausente = visible. Por eso, para no cambiarle el
-- comportamiento a nadie, se copian a la 14 las filas active=false que hoy existen
-- en la 4 (hoy solo Oficina Central 36 y Post Venta 40) y se deja visible solo a 36.
-- ----------------------------------------------------------------------------
INSERT INTO proyecto_filtro_funcionalidad (id, codigo, nombre) VALUES
    (14, 'HABILITACION_INDUCCION', 'Habilitación — Programar Inducción')
ON CONFLICT (id) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('proyecto_filtro_funcionalidad', 'id'),
    GREATEST((SELECT MAX(id) FROM proyecto_filtro_funcionalidad), 1)
);

-- Todo proyecto oculto hoy en HABILITACION queda igual de oculto en la nueva
-- funcionalidad, salvo Oficina Central, que es justamente lo que se quiere abrir.
INSERT INTO proyecto_filtro (project_id, funcionalidad_id, active)
SELECT pf.project_id, 14, false
FROM proyecto_filtro pf
WHERE pf.funcionalidad_id = 4
  AND pf.active = false
  AND pf.project_id <> 36
ON CONFLICT (project_id, funcionalidad_id) DO NOTHING;

-- Oficina Central: visible solo aquí (sigue oculta en HABILITACION). La fila
-- explícita con active=true es documentación del caso; sin fila también sería visible.
INSERT INTO proyecto_filtro (project_id, funcionalidad_id, active)
VALUES (36, 14, true)
ON CONFLICT (project_id, funcionalidad_id) DO UPDATE SET active = true;
